### ISSUE TITLE
Duplicate analyser mappings produced

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#100]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Mappings should only be one per page layout

#### Observed Behaviour

Multiple mappings produced for the same page layout where there are multiple pages referring to the page layout.

#### Steps to Reproduce

Run the analyser against multiple pages referring to the SAME page layout (Custom). 
Mappings file contains a mapping for each page

**Comment by jansenbe** [comment]
Related to this one...we're today also generating mappings for OOB uncustomized page layouts...these should also be skipped in my opinion

**Comment by jansenbe** [comment]
Tested this and only see on page layout entry, even if I do have multiple pages based upon that page layout.

**Comment by pkbullock** [comment]
Are you using AnalyseAll or AnalysePageLayoutFromPublishingPage?

This occurs in the AnalysePageLayoutFromPublishingPage method, which makes sense why this may generate duplicates because AnalyseAll directly looks at the page layouts, the other looks at referenced layouts in pages.

**Comment by jansenbe** [comment]
PS cmdlet uses AnalyzeAll

**Comment by jansenbe** [comment]
Fixed by @pkbullock in https://github.com/SharePoint/sp-dev-modernization/commit/f1c09befc018512e17a70f3573654834f76fa882
