### ISSUE TITLE
Export-PnPClientSidePageMapping - object reference error

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#101]
Not sure if this is a best place for this issue (PnP-PowerShell??)

#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

```powershell
Export-PnPClientSidePageMapping -BuiltInPageLayoutMapping -CustomPageLayoutMapping -Folder c:\temp
```

#### Observed Behavior

See exception. OOB layouts are mapped, custom ones are not.

#### Steps to Reproduce

Connect to site run command - error
The fault is in the AnalyseAll method

I have written a bypass script in PowerShell based on https://docs.microsoft.com/en-gb/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing#using-net
using the AnalysePageLayoutFromPublishingPage method and that works fine and can generate the mapping.

## Exception (PnP-Exception

```
Message          : Object reference not set to an instance of an object.
Stacktrace       :    at SharePointPnP.Modernization.Framework.Publishing.PageLayoutAnalyser.AnalysePageLayout(ListItem pageLayoutItem)
                      at SharePointPnP.Modernization.Framework.Publishing.PageLayoutAnalyser.AnalyseAll()
                      at SharePointPnP.PowerShell.Commands.ClientSidePages.ExportClientSidePageMapping.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1
```

**Comment by jansenbe** [comment]
Just did test `Connect-PnPOnline -Url https://bertonline.sharepoint.com/sites/devportal/en-us -Credentials bertonline` on 2 of my test portals did not see an error. Seems like it's picking up a page layout which is invalid or so?

**Comment by pkbullock** [comment]
Wondering whether this is reproducible in our rigs, we may need more diagnostics in this, ill see if I can hook in the custom reporting to glean more information.

**Comment by jansenbe** [comment]
In your code you're using the PublishingHidden field in the query for page layouts...that maybe plays a role? Would suggest cross checking that query against your test site as we simply generate a layout for every item returned by the query...as you know :-)

**Comment by pkbullock** [comment]
Tested the AnalyseAll code (in powershell format) query checks out, but its returning images. Looking at the source site, there is some dirty data where images have been associated with the Page Layout content type that is being picked up by the caml query.

**Comment by jansenbe** [comment]
Fixed by @pkbullock  in https://github.com/SharePoint/sp-dev-modernization/pull/102
