### ISSUE TITLE
Provide summary result for publishing page conversions

### ISSUE THREAD

**Issue by berryst2** [SharePoint/sp-dev-modernization#113]
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: the use of page transformation from PnP PowerShell
We've a lot of publishing pages in the Pages library and during the transformation most of them succeeded but there were also few of them which failed.
It'd be good to have a sumary result of the operation such as how many success, errors and which page had encountered error during transformation

#### Expected or Desired Behavior

Provide a summary log which tells us the number of pages processed, succeeded, failed and which ones that failed.

#### Observed Behavior
It currently provides logging for each individual operation but this could be very tedious to go through each one of the operations for library with a lot of pages.

  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
3.8.1904.0

**Comment by pkbullock** [comment]
@jansenbe It seems there is a relationship between the number of reports from the script in #108 we could look at improving the Cmdlet and additionally having a summary report option. 

@berryst2 is markdown still a suitable output?

**Comment by jansenbe** [comment]
@berryst2 : thanks for providing feedback, this will help us make a better tool

@pkbullock : I think we indeed need to have some kind of a summary report. Let's think about how to best integrate this.

**Comment by pkbullock** [comment]
@jansenbe will start to look at this one soon. 

- default to summary param to observers and add verbose option (thought I had wrote that)
- in PnPPS already have the selectors -SkipFlush so if default to summary and only show verbose based on -LogVerbose option 
- the logging has been very helpful with debugging or spotting issues, so tempted to increase logging points or improve debug option. 

Anything you like to add? Or further thoughts?

**Comment by jansenbe** [comment]
Sounds good! Verbose logging is there, but we need to add more places where we use it.

**Comment by pkbullock** [comment]
@jansenbe id like to split this into 2 parts, I have done the summary out which I will create a PR shortly, then add more places in verbose as second PR depending on how close next release is - it took a bit longer than expected to write this change.

**Comment by jansenbe** [comment]
Thanks @pkbullock . May release will go out latest next week Friday. Adding more logging is safe change, meaning we could potentially merge this in on Thursday, do basic testing and then release on Friday.

**Comment by jansenbe** [comment]
Changes have been integrated
