### ISSUE TITLE
Adjustments to page layouts mapping file not taking affect

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#115]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[X] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Making adjustments to the Rows/Columns not taking affect when running ConvertTo-PnPClientSitePage cmdlet.

Params used: -PublishingPage -DontPublish -SkipItemLevelPermissionCopyToClientSidePage -ClearCache -LogVerbose -Overwrite -PageLayoutMapping XXX -TargetWebUrl XXX -LogFolder XXX -LogType File

Source data uses Custom Layouts. 

#### Observed Behavior

Follows 1/1 default row/column

Odd thing is that in some transformations the layout does reflect, almost feels like an hidden error occurred or caching is occurring. The markdown reports shows a line for XXXImageField mapping to WikiImagePart but that reference was removed from the mapping file.

### Steps to reproduce

- Transform
- Adjust Rows/Columns in mapping file
-Transform

**Comment by pkbullock** [comment]
Update CacheManager ClearAllCacheslacks option to clear publishing page mapping cache

**Comment by jansenbe** [comment]
Hi @pkbullock ,

Thanks for reporting this.

When the mapping is provided via a custom file it's not cached, meaning if you would change the custom mapping file the next time that should be used. A mapping is only cached when it was generated on the fly...but even then when you would provide a mapping in file that would take preference. My initial thinking is:
- There are 2 mappings with the same name in your file
- The page is using a different layout then you expected it to use

**Comment by pkbullock** [comment]
@jansenbe Your right it is using a different mapping - one mapping name has spaces, one has %20. 😒
e.g.
Article Page with Image
Article%20Page%20with%20Image
from in SharePoint pages library they both visually look the same.

Its mixed pages use which layout, does explain why some of the layouts were working. thanks for nudging me in the right direction. 😊

I'll give this a go mapping this and report if this is fixed.

**Comment by pkbullock** [comment]
Yeap, this works now so was another dirty data scenario.

**Comment by jansenbe** [comment]
ok, thanks for reporting back. Think we can close this now.
