### ISSUE TITLE
Custom Image field not transforming Metadata

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#116]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[X] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Goal: Trying to Get a PublishingImage field value into the Page Details > Thumbnail image field value to preserve an alternative thumbnail for the page. 

I'm trying to populate the BannerImageUrl with so mapped under 
```xml
<Metadata>
<field name="customimagefield" targetfieldname="BannerImageUrl" Functions="ToImageUrl({customimagefield})" />
</Metadata>
```
Image field:
```html
<img alt="this is alttext" src="/sites/publishingsite/subsite/subsite/PublishingImages/folder/image.jpg" style="BORDER: 0px solid; ">
```
#### Observed Behavior

Exception: Image URL is invalid: with error showing HTML img tag.
Stack trace shows error occurs when ExecuteQueryRetry in SharePointPnP.Modernization.Framework.Publishing.PublishingMetadataTransformator.Transform()

Either my approach is wrong or we are missing function processing from this class. Its present in the mapping XSD file.

**Comment by jansenbe** [comment]
Can you show the used mapping xml + the contents of the image field

**Comment by pkbullock** [comment]
Updated with image obfuscated

**Comment by jansenbe** [comment]
So this is about setting the modern page preview image field?

I would not recommend writing the banner image url like this as banner image url is not a server relative url. During a client side page save we'll try to set a preview image automatically (see https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs#L830)...we do take the page header image if defined, if not we'll get the first image on the page. 

Is setting this image as page header image not an option for you? Alternatively we need to provide some builtin function to handle this need

**Comment by pkbullock** [comment]
I'm trying to map custom image to the thumbnail image. My approach or field maybe wrong in the first place.

To give context: 
![2019-04-12_11-37-09](https://user-images.githubusercontent.com/8781041/56031521-aecfdd80-5d17-11e9-8e5a-b569d34da5e8.jpg)

**Comment by jansenbe** [comment]
It's a valid scenario especially since we now offer control for customers to change the page preview image. Let me think about it :-)

**Comment by pkbullock** [comment]
Looking at the URL structure we can calculate that address getpreview.ashx e.g.
* Transfer asset
* Get Guids for Site, Web, File and extension from new target location.

**Comment by jansenbe** [comment]
Hey @pkbullock,

Looking into this we need:
-Support for running functions on metadata (did not yet implement that, although the schema supports it)
-A function that can do the asset transfer + generate the correct URL

Will look into this as next thing to fix.

**Comment by pkbullock** [comment]
Morning @jansenbe, was thinking along similar lines, sounds good! Happy to work on this if you want, seems quite meaty.

**Comment by jansenbe** [comment]
It wasn't that hard after all as I could reuse a lot of existing components. @pkbullock: would be good if you could try the following approaches and verify if they work for you. 

Also adding @russgove here as he might need this as well.

```XML
<!-- When you do have a publishing image field that will need to be set as preview image -->
<Field Name="PreviewImage" TargetFieldName="BannerImageUrl" Functions="ToPreviewImageUrl({PreviewImage})" />

<!-- When you do have a hard coded preview image already available on the target site. Note that the source field name (PublishingContactEmail in below sample) must exist, although it's not used here  -->
<Field Name="PublishingContactEmail" TargetFieldName="BannerImageUrl" Functions="StaticString('https://bertonline.sharepoint.com/_layouts/15/getpreview.ashx?guidSite=88eebac1710b464cb6816639340fac55&amp;guidWeb=277fe40db9d24da5bbc6827714184958&amp;guidFile=91bf17fd54e849149a3ad6b4f006304e&amp;ext=jpg')" />

<!-- When you want to refer a static image living in the source site  -->
<Field Name="PreviewImage" TargetFieldName="BannerImageUrl" Functions="ToPreviewImageUrl('/sites/sourcesite/siteassets/myimage.jpg')" />
```
Above was for the preview image, but with the recent changes you now can also set the page header to a static value. Below shows the typical page banner approaches:

```XML

<!-- Use an publishing image field as page banner image (note: you can pick another publishing image field besides PublishingRollupImage if that's desired) -->
<Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="ToImageUrl({PublishingRollupImage})" />

<!-- Use a hard coded, server relative image url. Image may live on either source or target site -->
<Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="StaticString('/sites/ModernizationTarget/SiteAssets/sitepages/Michael-Freedman/ms-stories-station-q-freedman-michael-12-1024x683.jpg')" />
```

Will add some documentation on this, as controlling the visuals of a page is common request.

**Comment by jansenbe** [comment]
@pkbullock : did you find time to try this?

**Comment by pkbullock** [comment]
Morning @jansenbe lol I didn't, but had a play this morning with this mapping and works really well:

**Comment by jansenbe** [comment]
Great! Thanks for confirming @pkbullock.
