### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#118]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[x] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Getting error transforming a few of the publishing pages in a libraryy. Others work fine. ConvertTo-PnPClientSidePage : Exception has been thrown by the target of an invocation.

I debugged through it and error is being thrown in method   
private Table NormalizeTable(IElement table)

A screenshot of the error:
![image](https://user-images.githubusercontent.com/2412956/56068916-a8a92380-5d4e-11e9-8589-197c5149d06f.png)

**Comment by russgove** [comment]
Nothe that the command used is 
ConvertTo-PnPClientSidePage -Folder "Operations" -TargetWebUrl "https://xxx.sharepoint.com/sites/tronetaupublishingpages" -Library pages  -Identity "Legal.aspx" -Overwrite -LogType File -LogFolder "C:\temp" -PublishingPage

**Comment by russgove** [comment]
In that methodm the table.OuterHtml is 
<table class="ms-rteFontSize-2 ms-rteTable-1" cellspacing="0" style="font-size: 1em; width: 100%;"><tbody><tr class="ms-rteFontSize-2 ms-rteTableHeaderRow-1" style="text-align: left;"><th class="ms-rteFontSize-2 ms-rteTableHeaderFirstCol-1" style="text-align: left;">Name</th>
<th class="ms-rteFontSize-2 ms-rteTableHeaderOddCol-1" style="text-align: left;">Licence</th>
<th class="ms-rteFontSize-2 ms-rteTableHeaderEvenCol-1" style="text-align: left;">Expiry Date</th>
<th class="ms-rteFontSize-2 ms-rteTableHeaderOddCol-1" style="text-align: left;">Purpose</th></tr>
<tr class="ms-rteFontSize-2 ms-rteTableOddRow-1" style="text-align: left;"><th class="ms-rteTableFirstCol-1" style="text-align: left;">Keith Mascarenhas</th>
<td class="ms-rteTableOddCol-1"><div><a title="Opens external link in new window" class="external-link-new-window" href="http://kwiweb/contdoc/licencesandregos/licences/GasAuthorisation%2018%20GF18842.pdf" target="_blank">GF18842</a></div></td>
<td class="ms-rteTableEvenCol-1"><div>11&nbsp;Oct&nbsp;2018</div></td>
<td class="ms-rteTableOddCol-1">Specified Gas Fitting Work</td></tr>
<tr class="ms-rteFontSize-2 ms-rteTableEvenRow-1" style="text-align: left;"><th class="ms-rteTableFirstCol-1" style="text-align: left;">Keith Mascarenhas</th>
<td class="ms-rteTableOddCol-1"><a href="http://kwiweb/contdoc/licencesandregos/licences/SupervisingGasFitter.pdf">GF</a>18842</td>
<td class="ms-rteTableEvenCol-1">11&nbsp;Oct 2018</td>
<td class="ms-rteTableOddCol-1">Supervising Gas Fitter</td></tr>
<tr class="ms-rteFontSize-2 ms-rteTableOddRow-1" style="text-align: left;"><th class="ms-rteTableFirstCol-1" rowspan="1" style="text-align: left;">Hayden Edmonds</th>
<td class="ms-rteTableOddCol-1" rowspan="1"><a href="http://kwiweb/contdoc/licencesandregos/licences/ElectricalInstallingLicence2019.pdf">IH050277</a><br></td>
<td class="ms-rteTableEvenCol-1" rowspan="1">11&nbsp;Nov 2019</td>
<td class="ms-rteTableOddCol-1" rowspan="1">In-House Electrical Installing Work Licence</td></tr>
<tr class="ms-rteFontSize-2 ms-rteTableFooterRow-1" style="text-align: left;"><th class="ms-rteTableFooterFirstCol-1" rowspan="1" style="text-align: left;">Joel Fitch</th>
<td class="ms-rteTableFooterOddCol-1" rowspan="1"><a href="http://kwiweb/contdoc/licencesandregos/licences/ElectricalInstallingLicence2019.pdf">IH050277</a></td>
<td class="ms-rteTableFooterEvenCol-1" rowspan="1">11 Nov 2019</td>
<td class="ms-rteTableFooterOddCol-1" rowspan="1">In-House Electrical Installing Work Licence</td></tr></tbody></table>

**Comment by russgove** [comment]
`<table class="ms-rteFontSize-2 ms-rteTable-1" cellspacing="0" style="font-size: 1em; width: 100%;">
    <tbody>
        <tr class="ms-rteFontSize-2 ms-rteTableHeaderRow-1" style="text-align: left;">
            <th class="ms-rteFontSize-2 ms-rteTableHeaderFirstCol-1" style="text-align: left;">Name</th>
            <th class="ms-rteFontSize-2 ms-rteTableHeaderOddCol-1" style="text-align: left;">Licence</th>
            <th class="ms-rteFontSize-2 ms-rteTableHeaderEvenCol-1" style="text-align: left;">Expiry Date</th>
            <th class="ms-rteFontSize-2 ms-rteTableHeaderOddCol-1" style="text-align: left;">Purpose</th>
        </tr>
        <tr class="ms-rteFontSize-2 ms-rteTableOddRow-1" style="text-align: left;">
            <th class="ms-rteTableFirstCol-1" style="text-align: left;">Keith Mascarenhas</th>
            <td class="ms-rteTableOddCol-1">
                <div><a title="Opens external link in new window" class="external-link-new-window"
                        href="http://kwiweb/contdoc/licencesandregos/licences/GasAuthorisation%2018%20GF18842.pdf"
                        target="_blank">GF18842</a></div>
            </td>
            <td class="ms-rteTableEvenCol-1">
                <div>11&nbsp;Oct&nbsp;2018</div>
            </td>
            <td class="ms-rteTableOddCol-1">Specified Gas Fitting Work</td>
        </tr>
        <tr class="ms-rteFontSize-2 ms-rteTableEvenRow-1" style="text-align: left;">
            <th class="ms-rteTableFirstCol-1" style="text-align: left;">Keith Mascarenhas</th>
            <td class="ms-rteTableOddCol-1"><a
                    href="http://kwiweb/contdoc/licencesandregos/licences/SupervisingGasFitter.pdf">GF</a>18842</td>
            <td class="ms-rteTableEvenCol-1">11&nbsp;Oct 2018</td>
            <td class="ms-rteTableOddCol-1">Supervising Gas Fitter</td>
        </tr>
        <tr class="ms-rteFontSize-2 ms-rteTableOddRow-1" style="text-align: left;">
            <th class="ms-rteTableFirstCol-1" rowspan="1" style="text-align: left;">Hayden Edmonds</th>
            <td class="ms-rteTableOddCol-1" rowspan="1"><a
                    href="http://kwiweb/contdoc/licencesandregos/licences/ElectricalInstallingLicence2019.pdf">IH050277</a><br>
            </td>
            <td class="ms-rteTableEvenCol-1" rowspan="1">11&nbsp;Nov 2019</td>
            <td class="ms-rteTableOddCol-1" rowspan="1">In-House Electrical Installing Work Licence</td>
        </tr>
        <tr class="ms-rteFontSize-2 ms-rteTableFooterRow-1" style="text-align: left;">
            <th class="ms-rteTableFooterFirstCol-1" rowspan="1" style="text-align: left;">Joel Fitch</th>
            <td class="ms-rteTableFooterOddCol-1" rowspan="1"><a
                    href="http://kwiweb/contdoc/licencesandregos/licences/ElectricalInstallingLicence2019.pdf">IH050277</a>
            </td>
            <td class="ms-rteTableFooterEvenCol-1" rowspan="1">11 Nov 2019</td>
            <td class="ms-rteTableFooterOddCol-1" rowspan="1">In-House Electrical Installing Work Licence</td>
        </tr>
    </tbody>
</table>`

**Comment by russgove** [comment]
OK, I  guess i need to upload the file:
[Next.txt](https://github.com/SharePoint/sp-dev-modernization/files/3075364/Next.txt)

**Comment by jansenbe** [comment]
@russgove , thanks for providing the details...it helped fix the issue :-)  See https://github.com/SharePoint/sp-dev-modernization/commit/8fd8370ef44b8a3e89ee5914def503983d614df7.

Problem was related due to mixed usage of TD and TH tags in the same TR.

**Comment by russgove** [comment]
Thanks Bert. That was fast!!!!
