### ISSUE TITLE
How to set custom background image on Header of Migrated PublishingPages

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#119]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[x ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ x] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Hi., Trying to put a simple banner image as on the Background of all the Publishing pages I migrate.

The Mapping template looks like this:
<PageLayout Name="BlankWebPartPage" AssociatedContentType="" PageLayoutTemplate="AutoDetect" PageHeader="Custom">
      <Header Type="FullWidthImage" Alignment="Left" ShowPublishedDate="false">
        <Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl"  Functions="ToImageUrl('/sites/TRonetAUPublishingPages/SiteAssets/Banner.Png')"  />
        <Field Name="ArticleByLine" HeaderProperty="TopicHeader" Functions="" />
        <Field Name="PublishingContact" HeaderProperty="Authors" Functions="ReturnFalse()" />
      </Header>
      <MetaData>
        <Field Name="Title" TargetFieldName="" Functions="" />

        <Field Name="Comments" TargetFieldName="" Functions="" />
        <Field Name="PublishingStartDate" TargetFieldName="" Functions="" />
        <Field Name="PublishingExpirationDate" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactEmail" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactName" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactPicture" TargetFieldName="" Functions="" />
        <Field Name="PublishingIsFurlPage" TargetFieldName="" Functions="" />
      </MetaData>
....

The migrated pages all use the standard backgound image.

How can I get a custom background image on the header of all my migrated publishing pages?

THX

**Comment by jansenbe** [comment]
Hi @russgove ,

You can specify that in the page header section. Below sample shows how the PublishingRollupImage is used to configure the page header image. You need to have PageHeader set to "Custom" and Header Type to "FullWidthImage".

```XML
<PageLayout Name="VolvoArticleLeft" AssociatedContentType="CustomPage1" PageLayoutTemplate="AutoDetect" PageHeader="Custom">
      <Header Type="FullWidthImage" Alignment="Left" ShowPublishedDate="true">
        <Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="ToImageUrl({PublishingRollupImage})" />
        <Field Name="ArticleByLine" HeaderProperty="TopicHeader" Functions=""/>
        <Field Name="PublishingContact" HeaderProperty="Authors" Functions="ToAuthors({PublishingContact})"/>
      </Header>
```

**Comment by russgove** [comment]
Hi,
I dont have a PublishingRollupImage, I'm trying to have all the pages use a standard header background image. I have this in my mapping file:
 <PageLayout Name="BlankWebPartPage" AssociatedContentType="" PageLayoutTemplate="AutoDetect" PageHeader="Custom">
      <Header Type="FullWidthImage" Alignment="Left" ShowPublishedDate="false">
        <Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl"  Functions="ToImageUrl('/sites/TRonetAUPublishingPages/SiteAssets/Banner.Png')"  />
        <Field Name="ArticleByLine" HeaderProperty="TopicHeader" Functions="" />
        <Field Name="PublishingContact" HeaderProperty="Authors" Functions="ReturnFalse()" />
      </Header>
      <MetaData>


I have a hardcoded link to the image instead of using the PublishingRollupImage. I need the same image on all pages for now.

**Comment by jansenbe** [comment]
Hi @russgove , the screenshot you pasted is not visible...can you also past the actual mapping file xml? Want to understand your scenario better...

**Comment by russgove** [comment]
Hi, Mapping file attached. On the BlankWebPartPage PageLayout I'm trying to specify a  hadcodce image:
<Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl"  Functions="ToImageUrl('/sites/TRonetAUPublishingPages/SiteAssets/Banner.Png')"  />
        


[custompagelayoutmapping-fb3f93e7-46a5-4af4-a088-dee15d12f100.txt](https://github.com/SharePoint/sp-dev-modernization/files/3077523/custompagelayoutmapping-fb3f93e7-46a5-4af4-a088-dee15d12f100.txt)

**Comment by jansenbe** [comment]
I understand your scenario now. Currently there's no support for hardcoded values, but it makes sense to have this. I'll look into this.

**Comment by jansenbe** [comment]
Would also recommend only keeping the  page layouts which you've customized...if you provide a mapping for a default layout then that overrides the default, embedded, one.

**Comment by russgove** [comment]
Thanks., I'll do that! Any idea if we can change the out-of-the-box default background image?

**Comment by jansenbe** [comment]
I'll need to a change for that. An alternative is that you use/set the PublishingRollupImage field on the source page. I think I'll be able to fix this soon, just need to foresee support for hardcoded values in the function evaluator logic.

**Comment by jansenbe** [comment]
So your header would be this, assuming you set your preview image as PublishingRollupImage:

```XML
<PageLayout Name="BlankWebPartPage" AssociatedContentType="" PageLayoutTemplate="AutoDetect" PageHeader="Custom">
      <Header Type="FullWidthImage" Alignment="Left" ShowPublishedDate="true">
        <Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="ToImageUrl({PublishingRollupImage})" />
        <Field Name="ArticleByLine" HeaderProperty="TopicHeader" Functions=""/>
      </Header>
```

Note that I've removed the PublishingContact field from the header mapping, the approach you've used is not optimal.

**Comment by russgove** [comment]
Thanks again, I can set the PublishingRollupImage on the source. just didn't know if it was possible with the modernization librarary.

**Comment by jansenbe** [comment]
Implemented a change for this. Now you can use the following syntax in functions to provide a static input:

```XML
<Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="StaticString('/sites/TRonetAUPublishingPages/SiteAssets/Banner.Png')" />
```
Important to note is that you'll need to specify the **StaticString** function if you want provide a static string.

**Comment by jansenbe** [comment]
@russgove : did you find time to try this?

**Comment by russgove** [comment]
doesnt seem to be working for me. its showing the standard image.  Let me do some debigging.....

**Comment by russgove** [comment]
Ah, looking at your PR. Do i need to create a new mapping file for this to work?

**Comment by jansenbe** [comment]
Yes, you need to update your mapping to make this work. Add below in your header of the page layout mappings you're testing with:

```XML
<Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="StaticString('/sites/TRonetAUPublishingPages/SiteAssets/Banner.Png')" />
```

**Comment by russgove** [comment]
Yeah, that part I knew. Was wondering if there was something else.
When I added the above , the image did not appear in the banner background.
I got the default image.

**Comment by jansenbe** [comment]
Some questions:
- Can you enable logging and share that output? 
- Can you also verify the used page layout is the one you need and share the complete mapping for that page layout?
- Is the used hardcoded url an image in the source or target site collection?

**Comment by jansenbe** [comment]
Hi @russgove ,

Wanted to check up on this one. Did you get an option to further test this?

**Comment by russgove** [comment]
Hi Bert,
I tried to test this again today but now i am getting hit with a new error 'Version Conflict' .
Opening a new issue for that. Once i get that resolved I'll retest this.

**Comment by russgove** [comment]
Ok, managed to run a test on a different documemt. the log file is attached.
[Page-Transformation-Report-4-23-2019-11-07-31-AM.md.txt](https://github.com/SharePoint/sp-dev-modernization/files/3108216/Page-Transformation-Report-4-23-2019-11-07-31-AM.md.txt)

it has a message in there "**An issue occurred in transferring an asset, falling back to orignal reference.**"

The layout mapping is attached here:

[custompagelayoutmapping-btly.xml.txt](https://github.com/SharePoint/sp-dev-modernization/files/3108226/custompagelayoutmapping-btly.xml.txt)

The layout used is  PageFromDocLayout.

The script used is 
$siteWitPublishingPages="https://tenant.sharepoint.com/sites/TronetAU20190422-D-Temp/btly"  
$destinationSite="https://tenant.sharepoint.com/sites/TronetAU20190422-D/btly"


#Connect-PnPOnline -Url $siteWitPublishingPages 
$list = Get-PnPList -Identity Pages
$pages = Get-PnPListItem -List Pages

ConvertTo-PnPClientSidePage   -Folder "Finance" `
    -Identity "Accounts-payable-staff.aspx" `
    -TargetWebUrl  $destinationSite `
    -Library pages  `
    -PageLayoutMapping "c:\temp\custompagelayoutmapping-btly.xml" `
    -WebPartMappingFile "C:\temp\webpartmapping-btly.xml" `
    -Overwrite `
    -LogType File `
    -LogFolder "C:\temp" `
    -PublishingPage  `
    -DisablePageComments `
    -ClearCache  -Verbose

**Comment by jansenbe** [comment]
Hi @russgove, the version conflict happens if you try to set a header image that does not exist. That might be the reason why it now works.

**Comment by jansenbe** [comment]
Based upon your mapping the header file lives in the source site collection: StaticString('/sites/TronetAU20190422-D-Temp/SiteAssets/Intro.png')...the reason why it's not working is because the asset transfer for that file failed. This is not expected and I'll do some checking.

In the meanwhile can you try to copy the intro.png to the target site and then update the mapping to 

StaticString('/sites/TronetAU20190422-D/SiteAssets/Intro.png')

and try again

**Comment by jansenbe** [comment]
Hi @russgove ,

Problem found: we've done some performance optimization in the asset transfer code and that included a case sensitive URL compare...resulting in asset transfer failure in case the provided URL did not match. Since we allowed adding static values (like StaticString('/sites/TronetAU20190422-D/SiteAssets/Intro.png')) this resulted in this issue. 

Can you retry with either the the latest dev version or update the casing in the static url to match the actual case and let us know.

**Comment by russgove** [comment]
OK , got it working. Image needs to be in same relative location in both sites, and the mapping needs to point to the item in the source site,

**Comment by jansenbe** [comment]
thx for the confirmation. Closing this one now

**Comment by KVSolutions** [comment]
Hi @jansenbe ,
We want a hardcoded banner image on all the migrated pages and I tried with your approach  as below in the Header tag of my custom page layout mapping file

<Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="StaticString('/sites/Venu/SiteAssets/SitePages/Asphalt.jpg')" />

However the image is not appearing as banner image and the image does exist in the target site under that url and the case is also matching exactly.

Content is migrated successfully without any issues.Would there be anything else to check ?
