### ISSUE TITLE
Ensure the correct wiki page library (sitepages) is loaded in the PowerShell ConvertTo-ClientSidePage cmdlet

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#12]
The cmdlet currently assumes the page always lives in the first wiki page library it finds, which might not be the case if you've created additional libraries

**Comment by JohnGGeo** [comment]
This looks like it's still occurring even after updating modules.
Thoughts on why this issue still seems to be occurring?
![image](https://user-images.githubusercontent.com/7240495/51542961-144fb480-1e22-11e9-9ebc-02de4f040896.png)

**Comment by jansenbe** [comment]
What output do you get from `get-module -Name SharePointPnPPowerShellOnline`?

**Comment by JohnGGeo** [comment]
This appears to be working once I re-imported again. Thanks!
