### ISSUE TITLE
Division by 0 in GetDefaultCellTableCellWidths

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#123]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ x] Bug
[ ] Enhancement

#### Problem Area

[x] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Hi, I'm getting a divide by 0 error within GetDefaultTableCellWidths:
![image](https://user-images.githubusercontent.com/2412956/56292961-2c1f9780-60f6-11e9-836b-6f45eed96b70.png)

going up the stack, when the transform method is called with the text in the attached file as the text parameter , it ends up calling  GetDefaultCellTableCellWidths with a 0 in the columns parameter

[error.txt](https://github.com/SharePoint/sp-dev-modernization/files/3089955/error.txt)

**Comment by jansenbe** [comment]
Fixed, there was a bug when a table had a TR but no TD or TH inside...

**Comment by jansenbe** [comment]
@russgove : closing, fix was just commited
