### ISSUE TITLE
Index Out of Range exception in NormalizeTable

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#124]
#### Category

[x] Bug
[ ] Enhancement

#### Problem Area

[X] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Getting an index out of range exception in NormalizeTable:
![image](https://user-images.githubusercontent.com/2412956/56294063-48bccf00-60f8-11e9-9a24-d3bd165ef55a.png)

This occurs if the transform method is called with the text in the attached file as the text parameter.
[error.txt](https://github.com/SharePoint/sp-dev-modernization/files/3090009/error.txt)

**Comment by russgove** [comment]
Hold on.... I'm using the maping file i used from the prvious site. Let me see if generating a new mapping fixes it.

**Comment by russgove** [comment]
This issue also happens when I use NO mapping files

**Comment by jansenbe** [comment]
Hi @russgove , the provided repro does not have a table and as such never gets in the normalizetable code. Might it be that this is the same as #123?

**Comment by russgove** [comment]
Hi, here is the correct one:
[error2.txt](https://github.com/SharePoint/sp-dev-modernization/files/3094545/error2.txt)

**Comment by jansenbe** [comment]
Fixed. Thanks for sharing these @russgove , really helps improve the transformation logic

**Comment by russgove** [comment]
Thank YOU bert.
