### ISSUE TITLE
Hyperlinks in ListviewWebpart show Url instead of text

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#126]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ x] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[x] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

If a listview on a publishing page has a hyperlink, the text of the hyperlink should be displayed,

#### Observed Behavior
If a listview on a publishing page has a hyperlink, the url of the hyperlink is displayed

Here is a screenshot of the classic publishing page:
![image](https://user-images.githubusercontent.com/2412956/56374102-6b221b80-61d0-11e9-8ae2-8c1269a9aa7b.png)

Here is a screenshot of the modern page after migration 

![image](https://user-images.githubusercontent.com/2412956/56374219-a3295e80-61d0-11e9-8b48-245fcef148a3.png)

I did not user a webpart mapping file. 
The URL field is defined like this:
![image](https://user-images.githubusercontent.com/2412956/56374337-eb488100-61d0-11e9-965a-96a31ece9c7a.png)

_

**Comment by jansenbe** [comment]
Hi @russgove , can you let me know what the base type of the list is that you're using?

**Comment by russgove** [comment]
Its a Links list

**Comment by russgove** [comment]
I found out after reporting this issue  that links lists are not supporting
in modern experience. So this is not a modernization issue.it  is an issue
with the modern UI itself.
So I guess we should close this issue.

I'lll  write some posershell to convert my Links List into a Custom list
and then the views will work.

Any idea if MS is working on enablin Links lists to be shown in the modern
Lists webpart?

Would be nice to have a utility to convert these 'classic' list types to be
just generic lists. Links is one of them. Access Lists (like if you
imported a list from MS ACCESS) is another. They dont behave well in
modern. Would be nice to have a command to convert them to plain Custom
Lists!

**Comment by jansenbe** [comment]
@russgove : I've a discussion on going for links (it is in our backlog).

**Comment by jansenbe** [comment]
I'll close this question for now, once we release updated capabilities I'll update the mappings (if needed) to take those in account
