### ISSUE TITLE
Error: Index was out of range. Must be non-negative and less than the size of the collection.  Parameter name: index

### ISSUE THREAD

**Issue by cueball59** [SharePoint/sp-dev-modernization#127]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[x ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Creation of modern version of page (home.aspx). 

#### Observed Behavior

Received the following error:
Error: Index was out of range. Must be non-negative and less than the size of the collection.
 Parameter name: index

#### Steps to Reproduce

1. Go to home.aspx of classic site. 
2. Click Create Modern Version
3. Goes to Modernization site and then produces the error

I was able to convert other pages just not this one.

**Comment by jansenbe** [comment]
Hi @cueball59 ,

Can you share the HTML of your home page?

We've fixed a couple of bugs related to table handling...do you happen to have tables on your home page? Is it possible to try with the current dev build?

**Comment by cueball59** [comment]
Hi @jansenbe TBH its just the default home.aspx page you get when you spin up the classic team site with a comments web part and a document library web part. Nothing more. I can certainly test out the dev build.

**Comment by jansenbe** [comment]
Hmm...wierd...but I'll give it a try

**Comment by jansenbe** [comment]
Just created a default home page (see below) and this works fine. Can you paste the html of the three sections of your home page, might be that something was added there.

![image](https://user-images.githubusercontent.com/7451219/56442531-77ea6080-62f1-11e9-8965-6612c3a6b9ce.png)

**Comment by jansenbe** [comment]
Hi @cueball59 , would it be possible to share your home page html so we can verify the issue you see?

**Comment by jansenbe** [comment]
Hi @cueball59 ,

I'm closing this issue as there has not been any feedback in the last 10 days. Feel free to re-open the issue if you still have the problem and if so then please provide the page html so we can try to reproduce the problem.
