### ISSUE TITLE
Page Does not exist when page exists in parent and child folder

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#129]
#### Category

[x] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

In my Pages library I have a folder called 'Information Management' and within that folder I have a subfolder called Archive. Each of these two folders has a file called Cats.aspx.  

When I run the migration to convert the Cats.aspx file in the Folder 'Information Management' it fails with the message 'Page CATS.aspx does not exist.

Debugging through, i see this is beacause in PagePipeBind.cs the Caml query foundd the two files and its only expecting one:
![image](https://user-images.githubusercontent.com/2412956/56503496-944def00-64e3-11e9-81d5-58ec9134d63f.png)

f I have a file named CATS.aspx _If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

#### Observed Behavior

_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce

_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

#### Submission Guidelines

_Delete this section after reading_

- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you checked the **"Page Transformation: Error during the setup/use of the Page Transformation UI solution"** checkbox then please provide:
  - The output of the following 2 PnP PowerShell statements: `Get-PnPStorageEntity` and `Get-PnPTenantServicePrincipalPermissionGrants`
  - The errors listed inside the browser's developer tools window (F12), if possible tested with Chrome as browser
  - The versions of the **sharepointpnp-pagetransformation-client-solution** and **sharepointpnp-pagetransformation-central-solution** solutions in your SharePoint tenant app catalog
- If you checked the **"Page Transformation: Error during the use of page transformation from PnP PowerShell"** checkbox then please provide:
  - The output you see in your PowerShell session
  - The output generated by calling `Get-PnPException`
  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
- If you checked the **"Page Transformation: Error during the use of page transformation from .Net"** checkbox then please provide:
  - The exact error message you get
  - The stack trace of the error
  - The version of the **SharePointPnP.Modernization.Framework.dll** assembly

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi @russgove ,

For the page in the lowest level you could add `-Folder "Information Management\Archive"` but specifying `-Folder "Information Management"` indeed does still find both pages. This is a bug that we should address for the  next release

**Comment by jansenbe** [comment]
Fixed in PS dev version: https://github.com/SharePoint/PnP-PowerShell/commit/4ca7952fc1c34a85a96dd0c27207bcace443a0d7

We now take the first page we see, so below two commands to take the correct page:
![image](https://user-images.githubusercontent.com/7451219/56600673-87bbba80-65f9-11e9-83c7-bf645b04e60d.png)

**Comment by russgove** [comment]
Thankyou!
