### ISSUE TITLE
capacity was less than the current size.

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#130]
#### Category

[x ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Hi,
Im getting an error  stating capacity was less than the current size:
![image](https://user-images.githubusercontent.com/2412956/56509192-560cfb80-64f4-11e9-9bcc-8d3acdd97b91.png)

I get this error when i try to transform a publishing page with the attached content.
[test.txt](https://github.com/SharePoint/sp-dev-modernization/files/3103913/test.txt)

**Comment by russgove** [comment]
btw, I think this is only happenning on the current dev branch.

**Comment by jansenbe** [comment]
In can repro this with your html content and appears to be related to regex going wrong on **?​$​0**. Updating the 8 locations unblocks this file, will search for a fix for this.

**Comment by jansenbe** [comment]
Fixed in https://github.com/SharePoint/sp-dev-modernization/commit/2e4bbb4fd153e11426da01672377b218435edad3

**Comment by russgove** [comment]
that fix worked for me. Thansk!

**Comment by russgove** [comment]
The fix worked for me , thanks!
