### ISSUE TITLE
Issue transforming default.aspx then accessing default view in library

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#134]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Library defaults are unaltered preferably

#### Observed Behavior

When transforming a page named default.aspx, this alters the default view (to the page) for transformed library when accessing via site Contents the default isn't the view its the page itself.

#### Steps to Reproduce

* Create page called default.aspx in source (its not relevant if this is set as a welcome page)
* Transform this page
* Try to go to Site Pages via Site Contents where the URL is the library not direct to the view like default navigation - this no longer load the default view e.g. ByAuthor but this transformed page.

**Comment by jansenbe** [comment]
@pkbullock: You can set the targetname property to override the name, there's also an equivalent PublishingTargetPageName property for the PnP PS cmdlet in the dev branch. Are you more looking at preventing the default.aspx name?

**Comment by pkbullock** [comment]
Yes, your right, raised in error, the previous enhancement was to work around this, so this can be closed.
