### ISSUE TITLE
Error  when rewriting url if is server relative

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#136]
### Category

[x ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[x ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Working with the new Url rewrite. I am getting the following error
![image](https://user-images.githubusercontent.com/2412956/56742958-b3e35280-6743-11e9-9ed7-f97979147932.png)

This is the input to the RewrireUrl method:
[error.txt](https://github.com/SharePoint/sp-dev-modernization/files/3117375/error.txt)

The source site is  TronetAU20190424-A-Temp 
Destination is TronetAU20190424-A

**Comment by russgove** [comment]
the text attached to above was wrong. The input to the RewriteUrl Method is /sites/TronetAU20190424-A/btly/sitepages.

This happens at line 115. The url is already relative:
![image](https://user-images.githubusercontent.com/2412956/56744479-9c599900-6746-11e9-9b56-2c76c9e4dbaa.png)

**Comment by jansenbe** [comment]
Thanks for logging this @russgove, will fix it asap

**Comment by pkbullock** [comment]
I apologise to you both for not acting on this, I spotted this possibility last night and made a comment in a commit rather than just fixing it.

**Comment by jansenbe** [comment]
Just fixed it

**Comment by jansenbe** [comment]
Closing this...please re-open if the problem still occurs
