### ISSUE TITLE
How do i have the titles of Summary Links webpart on Publishing pages carried over to modern when using  -SummaryLinksToHtml?

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#137]
[ ] Bug
[x ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ x] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

Summary Link  webparts on classic pages have the title set in the webpart properties and the Chrome Type set to Title Only.
Webpart title should be displayed after page is migrated and using  -SummaryLinksToHtml.

this is related to issue https://github.com/SharePoint/sp-dev-modernization/issues/120

**Comment by jansenbe** [comment]
Fixed.
