### ISSUE TITLE
Modernize older version of publishing pages

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#138]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug
[x] Enhancement

#### Problem Area

Hi, when migrating publishing pages, would it be possible to migrate prior versions of those pages as well. Users want the ability to view/roll back to the prior version of a page.

**Comment by jansenbe** [comment]
Hi @russgove ,

I'll have to some more investigation but this is a fairly complex chance which will have a potentially large performance hit. Isn't keeping the old portal around and then doing a manual update on the generated page an alternative?

**Comment by russgove** [comment]
Thanks @jansenbe 
keeping the old portal around and then doing a manual update on the generated page is an alternative for me and that's what I'm going to do in my upgrade. 

I'm a corporate dev, so I will [hopefully] be around to do manual updates in the future.  This might be an issue for others who do modernizations for a customer and wants to let the customer roll back the page to a prior version after their contract has completed. 

We can close if you like.
Thanks again,
Russell

**Comment by jansenbe** [comment]
Ok, thanks for you understanding. Will close the question now but I'll keep this request in the back of my head for a future version
