### ISSUE TITLE
Are there other reasons to  Communications site rather than a Team Site for modernization

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#139]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug
[ ] Enhancement
[x] Question

Hi @jansenbe 
Thanks for the video series on modernization (https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-videos). It was very helful.

I have a question. In all the videos you mentioed that the target of a modernization should typically be a communications site.  I have been doing the migration to a modern teamsite rather than a communications site and am trying to determine  if I should change to a communications site.

I create my target site with New-PNPTenant site with the STS#3 template, so I don't have the group or other articacts created.  Its my understanding that security in a site created this way is the same as my sharepoint on-prem site (It uses sharepoint groups rather than an O365 group to control permissions). 

My users are used to the left nav, so thats a plus to the team site. 

Are there other reasons to  Communications site rather than a Team Site. 

I found this conversation: 
https://techcommunity.microsoft.com/t5/SharePoint/Communication-Site-vs-Team-Site/td-p/84148

Do you know if the upcoming "Custom Page templates" will be available on modern "team  sites"?

Thanks in advance for any advice you can offer.

**Comment by jansenbe** [comment]
Both can work but I would have a light preference for communication sites over STS#3 because:
- This site is more meant to function as one to many communication site (so like a publishing portal)
- It does support full width pages which you do not get in modern team sites

Page templates will work in both modern team as communication sites.

**Comment by russgove** [comment]
Thankyou!
