### ISSUE TITLE
Page UI - Support for Publishing Pages

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#142]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

Desired behaviour to have a feature to allow users to request transform in the UI to modern including option for a feedback loop, conversion reports in centre and configuration. 

My thinking:

- Publishing sites still have modern page libraries, that an SPFX command could be created for this request by user. 
- SME would need to have defined mapping files so user does not get involved in that aspect - or option for User to select from a predefined (by SME) mapping.
- User can target Transform sites could be one or multiple sites e.g. option when selecting transform they can choose which site to target predefined by SME. 
- Basic operations such as Target Page Name, Overwrite are options for user
- Feedback bar in target site deployed by SME to raise transformation issues allow user feedback loop - since pages have embedded pnptransform property might be possible to show only to transformed pages

__We could use SPFX for much of this for UI even in source sites - but that's up for discussion__

This is primarily to support multi-team scenarios where the business are involved in the process, able to review the results, selectively transform pages and feedback any issues.

**Comment by jansenbe** [comment]
There are no current plans to work on the page transformation UI. The preferred option for doing page transformation is using PnP PowerShell or .Net. Check out the guidance at https://aka.ms/sppnp-pagetransformation.

This issue will be closed but can be re-opened if we restart the work on the page transformation UI.
