### ISSUE TITLE
Page UI - Support List Queue in SharePoint

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#143]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

Add support for storing transformation requests in SharePoint Lists to:

A) Log of requests and outcomes
B) Ability to have a script running anywhere e.g. not azure perhaps a Scheduled task in Server
C) For those implementations where azure subscription isn't an option or desired by business

Related to #142

**Comment by jansenbe** [comment]
There are no current plans to work on the page transformation UI. The preferred option for doing page transformation is using PnP PowerShell or .Net. Check out the guidance at https://aka.ms/sppnp-pagetransformation.

This issue will be closed but can be re-opened if we restart the work on the page transformation UI.
