### ISSUE TITLE
ConvertTo-PnPClientSidePage : Metadata mapping causing "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by MartinHatch** [SharePoint/sp-dev-modernization#145]
#### Category
[X] Bug

#### Problem Area
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell

#### Expected or Desired Behavior
Metadata is correctly copied over from the source page, according to the mappings file, to the new modern page after being created and/or overwritten

#### Observed Behavior
I have a custom mappings file to migrate a classic publishing page from a custom page layout and content type to a modern communication site. It is working FINE if I don't specify any TargetFieldName attributes to the Metadata Fields. The page gets created, web parts are added / converted .. the page title, banner image, author, HTML and summary links all get migrated. 

BUT ... when I try to define a Metadata entry in the mappings file then I get "Object reference not set to an instance of an object"

Mappings entry:
<Field Name="PFP_ShowLikes" TargetFieldName="PFP_ShowLikes" Functions="" />

Field "PFP_ShowLikes" is both the Internal and Display names of the field in *both* the source "Pages" library and target "Site Pages" library. It is also associated with the source and target content types (in the case of the target site, I am not using a custom content type, I just added the field to the library).

The field is configured (in both environments) as a Boolean (Yes/No) fields with no default value. 
I can successfully set the value in both the source and target pages through the UI without issue.

**Comment by jansenbe** [comment]
Thanks for reporting this @MartinHatch .

Can you provide a stacktrace? If you're running this from PnP PS then you can call Get-PnPException. Also interested to understand the type of the PFP_ShowLikes field?

**Comment by MartinHatch** [comment]
"The field is configured (in both environments) as a Boolean (Yes/No) field"

Ok - For some bizarre reason the next time I go to run the command (to return the exception message) it works!? Must have tried this 20 times and got the above error before it automagically working now?

Is there some kind of lag or caching involved which would mean the values were not being retrieved the first time? 

When creating new fields do we need to wait (e.g. for a search index?) before running these tools?

**Comment by jansenbe** [comment]
There's caching of field lists to improve performance, which most likely caused this. It's recommended to restart your PS window after updating the fields. There's also a -ClearCache parameter that you can use.

Closing this issue now.
