### ISSUE TITLE
ConvertTo-PnPClientSidePage fails with FIPS

### ISSUE THREAD

**Issue by krainer** [SharePoint/sp-dev-modernization#146]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ X ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Classic page is converted to a modern page

#### Observed Behavior

If FIPS is enabled, the following error is thrown:

ConvertTo-PnPClientSidePage : This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

#### Steps to Reproduce

Verify that FIPS is enabled:

Get-Item HKLM:\System\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy

If FIPS is disabled, enable FIPS and afterwards reboot Windows:

Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy" -Name "Enabled" -Value 1

After reboot convert a classic page with ConvertTo-PnPClientSidePage

(Cleanup: set the value to 0 and reboot)

Version: 3.8.1904.0

Get-PnPException:
--------------------
Message          : This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
Stacktrace       :    at System.Security.Cryptography.SHA256Managed..ctor()
                      at SharePointPnP.Modernization.Framework.Cache.CacheManager.Sha256(String randomString)
                      at SharePointPnP.Modernization.Framework.Cache.CacheManager.GetClientSideComponents(ClientSidePage page)
                      at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts)
                      at SharePointPnP.Modernization.Framework.Transform.PageTransformator.Transform(PageTransformationInformation pageTransformationInformation)
                      at SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()

Module version:
------------------
ModuleType Version    Name
---------- -------    ----
Binary     3.8.1904.0 SharePointPnPPowerShellOnline

**Comment by jansenbe** [comment]
I'll look into changing the hashing algorithm by a FIPS compliant one.

**Comment by jansenbe** [comment]
Hi @krainer ,

I've changed the hash algorithm to one that should be FIPS compliant. I configure my machine for testing, so would be good if you could try this on your end?

**Comment by krainer** [comment]
Hi @jansenbe  -  that was fast :) - shall I just get the dev branch to test it, or?

**Comment by krainer** [comment]
Found it - updating and checking

**Comment by jansenbe** [comment]
hi @krainer ,

Wanted to cross check if things now work for you? If so I can close the issue.

**Comment by krainer** [comment]
Hi Bert - is there a pre-built version available I can download and try - as the signing key obviously isn't there it means that I need to configure multiple projects etc :)? 
/Brian

**Comment by jansenbe** [comment]
We don't have signed dev builds...let's then test with the May release once it's out. I'll close this issue for now, but don't hesitate to re-open if you've still issues with the May release
