### ISSUE TITLE
Publishing Page Transformation Model : Mapping File : How do you set a WebPart Title to a fixed string?

### ISSUE THREAD

**Issue by MartinHatch** [SharePoint/sp-dev-modernization#147]
I have a custom publishing page layout with a Summary Links Field embedded.

The mappings file was auto generated with a WebParts element entry, which automatically converts this to a Quick Links web part.  This is all very good, and does indeed create a web part, in the specified Row/Column with all of the otherwise correct values.

However ...  the title of the web part is always blank.
In my Page Layout I have a hard coded string embedded as a "heading" for the summary links.
Ideally I want to set that value as the Web Part title, but I can't seem to work out how.

```
<WebParts>
       <Field Name="SummaryLinks" Row="2" Column="2" TargetWebPart="Microsoft.SharePoint.Publishing.WebControls.SummaryLinkWebPart, Microsoft.SharePoint.Publishing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
          <Property Name="SummaryLinkStore" Type="string" />
          <Property Name="Title" Type="string" Functions="EmptyString()" />
        </Field>
</WebParts>
```
I have tried all sorts of methods to set a fixed string value for the "Title" attribute of the web part - but the closest I can get is the web part rendering {Title} instead of the value specified.

The schema doesn't seem to support text values or a "Value" element (like the fixed web parts do)

Example: Quick Links Web Part - converted using ConvertTo-PnPClientSidePage
![image](https://user-images.githubusercontent.com/12050704/57138377-72d5e880-6daa-11e9-9bc4-4489d1dcf8c0.png)

**Comment by jansenbe** [comment]
Hi @MartinHatch ,

You can use the StaticString function as shown in below sample. This should work based upon my quick testing

```xml
        <Field Name="SummaryLinks" TargetWebPart="Microsoft.SharePoint.Publishing.WebControls.SummaryLinkWebPart, Microsoft.SharePoint.Publishing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" Row="1" Column="3">
          <Property Name="SummaryLinkStore" Type="string" />
          <Property Name="Title" Type="string" Functions="StaticString('Hi there')" />
        </Field>
```

**Comment by MartinHatch** [comment]
Aha excellent!

Just so I know, was this in the official documentation? I couldn't find any reference to it.

**Comment by jansenbe** [comment]
Not yet as this feature requires the dev version, we'll release the May version by end of this week and then I'll also update the public docs.

**Comment by jansenbe** [comment]
Closing this issue now
