### ISSUE TITLE
Publishing Page Transformation Model : Mappings File : How can you control Field based Web Part order?

### ISSUE THREAD

**Issue by MartinHatch** [SharePoint/sp-dev-modernization#148]
Simple one this.

Using a Mappings File with the **ConvertTo-PnPClientSidePage** command.

**FixedWebParts > WebPart** elements can specify an "Order" attribute to control the order they appear on the page.

**WebParts > Field** elements however, do not support an "Order" attribute, and will ALWAYS appear at the top of their column (regardless of the value given to the Fixed web Part).

This makes it impossible to control the order of web parts on a converted page when both Field-based web parts and Fixed Web Parts are in use in the same row/column.

**Comment by jansenbe** [comment]
Hi @MartinHatch ,

Can you share your mapping file so I can better understand this scenario?

**Comment by jansenbe** [comment]
This is good change request @MartinHatch , will see to get it included before we ship the May release next week.

**Comment by jansenbe** [comment]
Hey @MartinHatch ,

I've added an Order property to both the WebParts Field element and to the WebPartZone element. This allows you to control the position of all elements. Let me know how this work for you.

**Comment by MartinHatch** [comment]
Outstanding that would definitely do the trick! :)

**Comment by jansenbe** [comment]
Hi @MartinHatch,

Wanted to cross check if things now work for you? If so I can close the issue.

**Comment by MartinHatch** [comment]
@jansenbe - In terms of theoretical / design ?? Then yes, this solves my problem - but assuming this feature will require the "May 2019" PnP PowerShell release then I cannot verify if this is actually doing the trick or not?

**Comment by jansenbe** [comment]
Correct, if you're not running of dev branch bits then you need the May release. I'll close this issue for now, feel free to re-open if the problem still appears with the May release.
