### ISSUE TITLE
PowerShell errors at numerous points

### ISSUE THREAD

**Issue by rshorto** [SharePoint/sp-dev-modernization#149]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[X ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

#### Observed Behavior

When I run the modernizesitecollection.ps1 I am getting numerous errors as shown below. Despite these errors  the script does create a new Migrated_Home.aspx and Migrated_How To Use This Library.aspx which you can navigate to and they visually look modern and from my testings function correctly.

Do I need to edit where the PNPfield it is pointing to as the current point doesn't exist and neither does the Theme. With the Site collection error on the basis the site isn't a Site collection makes sense however does that mean this can only be run against site collections and to run it against Sub Sites I need to adjust the script?

Additionally the O365 owner group isn't created the the scripts hangs on trying to add the existing users on the classic site to that group.

Here is the output of the script

`Input the url for the site to be modernized ?: https://blah.sharepoint.com/blah
Input the Office 365 group alias for this site ?: Blah
Will the created Office 365 group be a public group ? Enter True for public, False otherwise: True
Classification label to use? Enter label or leave empty if not configured: 
Please enter admin UPN: adminUPN@blah.onmicrosoft.com
Connect to tenant admin site https://TenantAdmin-admin.sharepoint.com
VERBOSE: PnP PowerShell Cmdlets (3.8.1904.0): Connected to https://TenantAdmin-admin.sharepoint.com
Connect to Azure AD
User running modernization: admin@blah.onmicrosoft.com
Connecting to site https://blah.sharepoint.com/blah
VERBOSE: PnP PowerShell Cmdlets (3.8.1904.0): Connected to https://blah.sharepoint.com/blah
Enabling modern page feature, disabling modern list UI blocking features
Set-PnPField : Column 'Color' does not exist. It may have been deleted by another user.
At line:154 char:9
+         Set-PnPField -Identity "Color" -Values @{ClientSideComponentI ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPField], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Fields.SetField
 
Cleanup old branding
Set-PnPWebTheme : Unknown Error
At line:170 char:9
+         Set-PnPWebTheme -Theme "Contoso Electronics"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPWebTheme], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.SetWebTheme
 
Modernize the site pages
Modernizing  Home.aspx ...
Done
Modernizing  How To Use This Library.aspx ...
Done
Call Office 365 Group connection API with following settings: Alias=Blah, IsPublic=True, Classification=
Add-PnPOffice365GroupToSite : You can only perform this operation on site collections.
At line:198 char:9
+         Add-PnPOffice365GroupToSite -Url $siteCollectionUrl -Alias $a ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPOffice365GroupToSite], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Admin.AddOffice365GroupToSite
 
Adding site administrators and site owners to the Office 365 group owners
Attempting to add user@blah.onmicrosoft.com to group 00000000-0000-0000-0000-000000000000
Retry attempt number: 1. Sleeping for 2 seconds...
Retry attempt number: 2. Sleeping for 4 seconds...
Retry attempt number: 3. Sleeping for 8 seconds...
Retry attempt number: 4. Sleeping for 16 seconds...`

#### Steps to Reproduce

I am running the script within Powershell ISE and have not really changed any part of the code other than the credentials. I am prompted to enter those manually. 

#### Submission Guidelines

_Delete this section after reading_

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi @rshorto ,

The script is meant to be a sample and does require tweaking to work in your environment. It shows how to, for example, deploy a new field customize to a given custom field, but obviously, you don't have that field in your site. Same with the the theme: code shows how to set a custom theme, but again this custom theme by default is not in your environment. So you have to see this script as a starting basis for building your end to end site modernization script, simply comment out the parts that you do not need.
