### ISSUE TITLE
Option to not add web parts where source data is empty

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#156]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

When transforming publishing pages, some content for web parts such as images, the source page does not contain data, would be nice to not add that web part, mainly because each web part contains padding that when unused can leave large blocks of white space. 

It is preferable to have an option to not add the part if the source data is empty or missing. This issue particular is focused around the image web parts.

**Comment by jansenbe** [comment]
If we do this we'll need to handle this per web part type, but it's a good call out as 'not having content' is typical in publishing page scenarios. Let's check for 'empty' web parts for image, summarylinks and text web parts.

**Comment by jansenbe** [comment]
Implemented a generic fix for this: see https://github.com/SharePoint/sp-dev-modernization/commit/40d969ea8e8d8b9cdcc9b403044e31e935cbe39c for more details.
