### ISSUE TITLE
When transforming WikiImage leaves {caption} placeholder when content is empty

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#157]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Empty web parts should be empty or removed (see ref #156), in transformations I have seen placeholders in the image web part 

#### Observed Behavior

When transforming publishing pages, when the source is empty, an empty web part contains {caption} text when using the SharePointPnP.Modernization.WikiImagePart mapping, currently working around with type: Microsoft.SharePoint.WebPartPages.ImageWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c

**Comment by jansenbe** [comment]
Let's solve this via the implementation of #156

**Comment by pkbullock** [comment]
Workaround - Specify the web part mapping file for WikiImagePart, Under Properties, add:

```xml
<Property Name="Caption" Type="string" />
```
then in page layout mapping file, under WebParts > Field PublishingPageImage, specify:
```xml
<Property Name="Caption" Type="string" Functions="EmptyString()" />
```
This moves the control to the page layout mapping file which for the moment I have specified as empty. This clears the issue when specifying the -WebPartMappingFile with the adjustments.

## Secondary Issue

One thought tho, I noticed in my user profile for the default xml files for page/web part mappings, are we handling updates to the file when we release a new version with modifications? Or how/where are the defaults specified?

**Comment by jansenbe** [comment]
Nice workaround but I'll plan to actually do a proper fix for this as I don't want to encourage creating a custom web part mapping file for this reason. Each release has the latest mapping files in the nuget package and in PnP PS, but it's up the user to merge changes for the web part mapping files.

**Comment by jansenbe** [comment]
Hey @pkbullock ,

Did check this and I don't think this is an issue. In the default page layout mapping file we use the following construct:

```XML
<Property Name="Caption" Type="string" Functions="ToImageCaption({PublishingImageCaption})" />
```
without the Caption field being set in the webpartmapping file. The caption field value is always set to "" for non-publishing page transformations. For publishing pages you would either use the default approach as shown above which will return in an empty value if the field provided into ToImageCaption is null or empty or alternatively use your approach with the EmptyString() function in case you do not want to take over image captions altogether. 

Can you verify that things work for you with the default web part mapping file?

**Comment by jansenbe** [comment]
Closing this one as we now anyhow skip empty web parts + the above mentioned approach works when there's actual content but no caption value. If this still is an issue then let's create a new issue for it.
