### ISSUE TITLE
Option to transfer assets to fixed location

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#158]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

For assets that are transferred, adding the capability to target a location for when the new organisational assets feature is enabled. This will allow pooling of image files into a single location. 

#### Observed Behavior

New feature in Office 365 for Organisational Assets

**Comment by jansenbe** [comment]
The organization assets feature is meant for assets that are company controlled and ready for broader usage. Some intranet assets would be good candidates, but definitely not all of them. I think this is more of a manual thing that customers use for future pages on their modern portals...what do you think @pkbullock ?

**Comment by pkbullock** [comment]
Yeah make sense, we may need to park this one, roadmap shows this as Q4 this year for release, was hoping to use this in current intranet project.

Perhaps if URL Rewrite supports this, on selected assets e.g. when a URL matching is done, the asset reference is updated to the org asset instead of the original - might need more thinking when the feature is released. Related to  #135

Closing based on rollout delay of feature.
