### ISSUE TITLE
Split off logging into seperate cmdlet + decide when to flush without transform

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#159]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

This is such a bad title for an issue lol

Two things, in PnP PowerShell:

- Split off logging setup into a seperate cmdlet
- Allow logging flush without needing to transform - in the scenario where after you loop through files it would be easlier to choose when to write the logs to file - ideally using a seperate cmdlet

**Comment by jansenbe** [comment]
Or create a separate "log flush" cmdlet than then can be used in combination with the -LogSkipFlush parameter

**Comment by jansenbe** [comment]
Added Save-PnPClientSidePageConversionLog to PnP PS: if you run the ConvertTo-PnPClientSidePage cmdlet with the -LogSkipFlush flag then logs are kept in memory. Calling Save-PnPClientSidePageConversionLog will trigger the log saving.
