### ISSUE TITLE
On-Prem Files reside in Pages Subfolder

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#160]
Related to #154 

#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[X] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Pages are transformed but in SPO they reside in a pages subfolder in the site pages library, no parameters are set to transform to this location:

![sub-folder-bug-2019-05-23_07-40-28](https://user-images.githubusercontent.com/8781041/58231166-36086c00-7d2e-11e9-8009-ec39ee42b09f.jpg)

#### Steps to Reproduce

Run the script example on SP2013 referenced in 
https://github.com/SharePoint/sp-dev-modernization/issues/154#issuecomment-494885176

**Comment by jansenbe** [comment]
This most likely is a side-effect of running this against on-prem...should be handled when we further work out this capability

**Comment by jansenbe** [comment]
Closing as the fix for this has been merged
