### ISSUE TITLE
On-Prem Multiple Reporting issues

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#162]
Related to #154 

#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Observed Behavior

- incorrectly links to wrong source in verbose report
- when exceptions occur, line breaks mess up markdown report (could be a bug regardless of on-prem - needs investigating)

#### Steps to Reproduce

Run script with logging options referenced in https://github.com/SharePoint/sp-dev-modernization/issues/154#issuecomment-494885176

**Comment by jansenbe** [comment]
Line breaks indeed are a bug, not related to on-premises. The links is related the on-premises use and should be handled this functionality is added

**Comment by pkbullock** [comment]
@jansenbe pls assign to me - working on this now

**Comment by jansenbe** [comment]
Closing as the fix for this has been merged.
