### ISSUE TITLE
Add more reporting observers - CSV/Log Analytics/AppInsights

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#163]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

- Add cloud based observers to Log Analytics or Application Insights, this can centralise a pool of logging reults, querable, and can be used for reporting in Page UI Transformation scenarios where the transformation runs in Azure Functions. 
- Add CSV output to provide a  list of transform results in a reportable format

Especially useful when doing lots of transformations, bulk or batching where a MD file isnt the best for multi-page, multi-site transforms. 

This is partly related to issue #159 where the parameters could be quite numerous to access cloud services or the number of variants to the logging feature.

**Comment by jansenbe** [comment]
Assigned to you @pkbullock , don't think there's an urgent need so this could move to summer time or even later

**Comment by pkbullock** [comment]
Agreed, if there is a stronger desire for this, pls comment.
