### ISSUE TITLE
Check support for transforming to root site in SPO

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#164]
#### Category

- [ ] Bug
- [X] Enhancement

#### Expected or Desired Behavior

Need to see if transforms work into Communication Sites in the Root Site Collection in SPO. I have a new Dev Tenant which is a communication site, so need to check if this will work.

#### Other Points

I have a hunch that issue #160 might cause issues with this as well.

**Comment by jansenbe** [comment]
Took the liberty to assign this one to you @pkbullock ... let me know if you want me to handle it.

**Comment by pkbullock** [comment]
Yeap - this transforms with a simple test successfully - no major blockers
