### ISSUE TITLE
Modernization UI

### ISSUE THREAD

**Issue by gregwilliams14** [SharePoint/sp-dev-modernization#166]
Installed the Modernization successfully - however, I have a few issues.
1)  Using Edge I get the following error (works in Chrome and IE) - Not all parameters are configured, can't execute. Please run the setup steps.
2) In IE the Keep/Discard options do not work.
3) is there a mapping for "Content Editor Web Part" to "Text" web part in modern? I can transform to "Embed" without issue - however, would like to map to "Text"

Greg

**Comment by gregwilliams14** [comment]
Just installed the dev Edge (Chromium open source) and the Modernization UI works.

**Comment by jansenbe** [comment]
Correct, IE11 does not work at this moment. With dev Edge becoming the standard MSFT browser we currently do not have plans to add support for IE11.

**Comment by jansenbe** [comment]
Hey @gregwilliams14 , wanted to cross check with you if using Edge chromium or Chrome is a valid workaround for you? If so then feel free to close this issue.

**Comment by gregwilliams14** [comment]
Not really.  We are in process for rolling out Win10 which has Edge (non-Chromium).  It would only work if we get user to install Edge chromium or Chrome.  At some point we will roll out Edge Chromium.  Will it not work in Edge?

**Comment by jansenbe** [comment]
Include IE support

**Comment by jansenbe** [comment]
There are no current plans to work on the page transformation UI. The preferred option for doing page transformation is using PnP PowerShell or .Net. Check out the guidance at https://aka.ms/sppnp-pagetransformation.

This issue will be closed but can be re-opened if we restart the work on the page transformation UI.
