### ISSUE TITLE
Page Layout mapping within Web Part Zones

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#167]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

Hopefully I can explain this one clearly. 

I am facing a scenario where I have a classic page, with a specific layout so I can set new row/column options on fixed elements. However, the new design requires that web parts within a Web Part Zone targets different rows/columns to the original.

At the moment, I cannot see capability under page layout or web part mapping to achieve this. 

Seen the docs site: https://docs.microsoft.com/en-gb/sharepoint/dev/transform/modernize-userinterface-site-pages-layout#overriding-the-default-layout-transformation but cannot see how to influence web parts (by PnP PowerShell) into the zones during transform.

So thinking of add page layout mapping to have under the Web Part Zones > Web Part Zone node to target web parts of a certain type to a row/column e.g.

```xml
<WebPartOccurance Type="Text" Row="1" Column="1" Occurs="First" />
<WebPartOccurance Type="Image" Row="1" Column="2" Occurs="First" />
<WebPartOccurance Type="Text" Row="2" Column="1" Occurs="Subsequent" />
<WebPartOccurance Type="SummaryLinks" Row="2" Column="2" Occurs="First" />
```
Above is representative Occurs needs some thinking. Types better accuracy, possibly enhance the page layout analyser to include the mappings of the instance of the web parts within the zones when a page is specified.

**Comment by jansenbe** [comment]
The thing with a web part zone in a page layout is that you're never sure which web parts are added (if any) and it what order, hence the current system allows you to "position" the zone and then the modern page will hold the modern equivalents of those web parts all in that defined "position" while retaining the order of the web parts in the web part zone.

Probably a more flexible approach might be using PnP PS to "shuffle" the web parts around after the page was created?

**Comment by jansenbe** [comment]
Thinking more about this idea and it makes a lot of sense for scenarios where folks heavily depended on adding content via web parts (eg content editor). Let's assign to July release for now.

**Comment by jansenbe** [comment]
Hey @pkbullock ,

I've implemented this one, docs will follow but below snippet should get you started. Important you use the web part types as received by the web part manager (check webpartmapping.xml to get these or the WebParts class. If a webpart found in the webpart zone is not defined in the webpart zone layout then the position information is taken from the actual zone. You can define as many web parts (WebPartOccurance element) as needed, if there's no actual webpart for the occurrence than it's simply ignored.

```Xml
      <WebPartZones>
        <WebPartZone Row="2" Column="1" ZoneId="g_0C7F16935FAC4709915E2D77092A90DE" ZoneIndex="0">
          <WebPartZoneLayout>
            <WebPartOccurance Type="Microsoft.SharePoint.WebPartPages.ContentEditorWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" Row="3" Column="2"/>
            <WebPartOccurance Type="Microsoft.SharePoint.WebPartPages.ContentEditorWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" Row="3" Column="1" Order="2"/>
            <WebPartOccurance Type="Microsoft.SharePoint.WebPartPages.XsltListViewWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" Row="3" Column="1" Order="1"/>
          </WebPartZoneLayout>
        </WebPartZone>
      </WebPartZones>
```

**Comment by pkbullock** [comment]
@jansenbe More awesomeness!!
