### ISSUE TITLE
Mapping migration issue

### ISSUE THREAD

**Issue by ManuMora9** [SharePoint/sp-dev-modernization#168]
#### Category

[x] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[x] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

I'm trying to migrate a classic page to modern experience. In the classic page, I have two zones, one occupies two-thirds, and the other, one-thirds. I'm trying to migrate it using a xml mapping file, in which I set the first zone "column" propertie to 1, and the second zone to 2 and 3, but when I migrate it, the layout it's two equal columns, instead of the two-thirds/one-thirds that I expected. I also tried to set the first zone "column" propertie to 2 and the second one to 3 but the result it's the same.

This is the XML code that I'm talking about:

`<WebParts> <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Order="1" Row="1" Column="1"> <Property Name="Text" Type="string" /> </Field> </WebParts>`
`<WebPartZones> <WebPartZone ZoneIndex="2" Order="2" ZoneId="g_3EABBA081F5C47FCBEE3A54DE44829EA" Row="1" Column="3" /> </WebPartZones>`

I'm using PowerShell, if you need to know it.

#### Observed Behavior

The layout is expected to be two-thirds/one-thirds but it results as one-half/one-half

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hey @ManuMora9 ,

The default layout manager for publishing pages sees three columns in your example as you've column 1 and 3 in your row 1. Hence it will create a three column section and put content in column 1 and 3. The default behaviour is to drop empty columns and sections, so column gets dropped giving you the result of 2 50% columns.

Can you try with turning off the "auto layout" feature by setting the PageLayoutTemplate property to the layout you need. You do need to ensure that the used rows and columns are present in the chosen PageLayoutTemplate.

```XML
<PageLayout Name="ArticleLeft" AssociatedContentType="" PageLayoutTemplate="TwoColumnsWithSidebarLeft" PageHeader="Custom">
```

**Comment by ManuMora9** [comment]
It worked perfectly, it did just what I needed! Thanks for your help.

**Comment by Saurabh7019** [comment]
The suggested solution does work when both the zones have content in the source page but not when right side zone in source page is empty. It adds a one column section in modern page and breaks ‘Add a new webpart’ feature. Please see the screen below - add a new web part option is replaced with the change section layout. 

![Capture](https://user-images.githubusercontent.com/18114579/67403000-9fc4c480-f5b1-11e9-8dcd-89a6125d72a3.PNG)
