### ISSUE TITLE
WebPart zone mapping to one third right column layout

### ISSUE THREAD

**Issue by robi26** [SharePoint/sp-dev-modernization#170]
#### Category

[ x ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ x ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Using the new publishing page layout mapping I try to convert a classic one third right column layout to a modern page using the following XML
```xml
<WebPartZones>
  <WebPartZone ZoneIndex="0" ZoneId="pageLayoutBRow1Left" Row="1" Column="1" />
  <WebPartZone ZoneIndex="0" ZoneId="pageLayoutBRow1Right" Row="1" Column="3" />
</WebPartZones>
```

I set the column value to 3 hoping that the one third right column layout is chosen for the modern page. But the chosen layout is 'two columns'.

#### Observed Behavior

Two column layout is chosen instead of One third right column layout

#### Steps to Reproduce

1. Create a classic page layout with at least two zones
2. Create a publishing page mapping file and configure the web part zones to use column 1 and 3 respectively. See xml above.
3. Perform transformation

**Comment by jansenbe** [comment]
Hey @robi26 ,
See #168 for an explanation on why this happens and a possible workaround

**Comment by robi26** [comment]
Thanks for the reference to the issue, didn't see that. 
Setting the PageLayoutTemplate property to a specific layout works as long as you have only one row.  The problem arises as soon as you have more than one row or mixed layouts.

If you have multiple rows with the same layout I get the following error:
ConvertTo-PnPClientSidePage : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Set the ``PageLayoutTemplate="TwoColumnsWithSidebarRight"``
The xml looks like:
```xml
<WebPartZones>
  <WebPartZone ZoneIndex="0" ZoneId="pageLayoutBRow1Left" Row="1" Column="1" />
  <WebPartZone ZoneIndex="0" ZoneId="pageLayoutBRow2Left" Row="2" Column="1" />
  <WebPartZone ZoneIndex="0" ZoneId="pageLayoutBRow1Right" Row="1" Column="2" />
  <WebPartZone ZoneIndex="0" ZoneId="pageLayoutBRow2Right" Row="2" Column="2" />
</WebPartZones>
```

When using mixed layouts the PageLayoutTemplate property on the page layout is too 'global' because the first row could be ``TwoColumnsWithSidebarRight`` and the second ``ThreeColumns``

**Comment by jansenbe** [comment]
Why don't you specify all in the same row like this...this should retain your 1/3 and 2/3 split and I think the web part order should follow the web part zone order if I'm not mistaken.

 ```XML
<WebPartZones>
  <WebPartZone ZoneIndex="0" ZoneId="pageLayoutBRow1Left" Row="1" Column="1" />
  <WebPartZone ZoneIndex="0" ZoneId="pageLayoutBRow2Left" Row="1" Column="1" />
  <WebPartZone ZoneIndex="0" ZoneId="pageLayoutBRow1Right" Row="1" Column="2" />
  <WebPartZone ZoneIndex="0" ZoneId="pageLayoutBRow2Right" Row="1" Column="2" />
</WebPartZones>
```

**Comment by robi26** [comment]
That works if all rows have the same layout.
But we also have some page layouts having a 'special' design, something like this:
![image](https://user-images.githubusercontent.com/9413361/58954878-ab4a5700-879a-11e9-9040-4b637f3043a4.png)

In this scenario the workaround does not work.

**Comment by jansenbe** [comment]
That design is anyhow currently not possible. We'll be shipping a continuous column as part of the home site release, once we have that capability we can re-evaluate this. There's nothing I can do short term here, hope you understand.

**Comment by jansenbe** [comment]
We now support a right side vertical column that spans the page. Will integrate using this for the October release

**Comment by jansenbe** [comment]
Moved to November release

**Comment by jansenbe** [comment]
@robi26 : with the November release you'll be able to transform publishing pages into modern pages that use a vertical column. See https://github.com/SharePoint/sp-dev-modernization/commit/ded7f1f6649ea8150a8f84d4ed89e4bea13b9990. Will close this issue now, if after testing with the November release you still have issues then please open a new issue with the needed details.

**Comment by robi26** [comment]
Thanks, that sounds great. I'll try it in November.
