### ISSUE TITLE
Papge properties web part for FixedWebParts

### ISSUE THREAD

**Issue by robi26** [SharePoint/sp-dev-modernization#171]
#### Category

[ ] Bug
[ x ] Enhancement

#### Expected or Desired Behavior

If possible, please add the 'Page Properties' web part (FieldsWebPart) to the [list of the supported fixed web parts](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/WebParts.cs).

**Comment by jansenbe** [comment]
Hey @robi26,

I do not really understand the question...are you talking about an existing classic FieldsWebPart? If so, can you specify the full name for me / a screenshot of the web part in action on a page. ...or are do want an option to get the modern page properties web part to be added to the created modern page?

**Comment by robi26** [comment]
Hi @jansenbe 
Sorry for the confusion. I'm talking about the page properties web part on the modern page.
Here is the example:
![image](https://user-images.githubusercontent.com/9413361/58934563-1d0aac80-876b-11e9-8e70-1851112a2795.png)
I would like to add this web part to the newly created page as a fixed web part.

**Comment by jansenbe** [comment]
Got it @robi26 , that's a good thing to include.

**Comment by jansenbe** [comment]
Was thinking of implementing this in below manner, so you'll have to tell which fields will be shown in the web part and where the web part will be hosted. Would that work for you @robi26 ?

 ```XML
<MetaData ShowPageProperties="true" PagePropertiesRow="1" PagePropertiesColumn="2">
        <Field Name="Title" TargetFieldName="Title" Functions="" ShowInPageProperties="true"/>
        <Field Name="SeoKeywords" TargetFieldName="" Functions=""/>
        <!-- Functions allow to 'add' new fields to the metadata collection -->
        <Field Name="MyCustomField" TargetFieldName="MyCustomField" Functions="ConsolidateCustomField({MyCustomField}); {ExtraField}=SplitCustomField({MyCustomField})" />
      </MetaData>
```

**Comment by robi26** [comment]
That would work. The question is, if we are limiting the configuration possibilities of the web part for the future. If there will be more configurations available (e.g. new layout possibilities, hiding the title...) the MetaData node will have more attributes. If we handle the configuration as a 'normal' fixed web part, we need no schema change.

**Comment by jansenbe** [comment]
Defining it like the other web parts is also not correct as you're not taking a specific field...for now, I've implemented this as mentioned above...if in the future things change we can update properties in the web part mapping file, in the code that generates the web part model and in the layout files if needed.

**Comment by jansenbe** [comment]
Implemented in the dev branch + updated dev branch of PnP PS for this. You'll need to ensure to use the latest webpartmapping.xml file to make this work.
