### ISSUE TITLE
On-premises support: prevent item level permission copy when source and target context are in different tenants

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#173]

**Comment by pkbullock** [comment]
I think this could be a simple change in the core, when the two contexts base address differ, disable the item level copying. 

Feel free to assign to me if you like :)

**Comment by jansenbe** [comment]
You got it :-)

Would create a method in the BasePageTransformator class for this check and then call it during input validation in the respective Transform methods of the PageTransformator and PublishingPageTransformator classes.

If you can't get this done before end of tomorrow then please let me know as I want to have this in for the June release

**Comment by jansenbe** [comment]
Thanks for the help @pkbullock , appreciated!
