### ISSUE TITLE
Mapping files - one file to rule them all

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#179]
#### Category

[ ] Bug
[x] Enhancement

#### Expected or Desired Behavior

With the growing requirements and mapping files, is it worth considering have one single file?

We have:

- Web Parts
- Page Layouts
- URL Rewrites (TBC)
- User Mapping (TBC)

Just thinking the complexity of built-in defaults/custom mappings files. Also, gives a single location to expand the schema later on.

**Comment by jansenbe** [comment]
These files have different dynamics and different usages: web part mapping file will be standard for the majority of customers whereas every publishing portal transformation will use a custom page layout mapping file. Combining them all will make the update story harder as than folks need to manually keep the web part mapping part in sync with the latest. Url rewrite and user mapping are also optional things, user mapping is only needed for cross tenant or from on-prem to online transformations. Was more of thinking about reusing existing file formats here (like the one used by the SharePoint Migration Tool (SPMT)

**Comment by pkbullock** [comment]
Yeah, just thinking of area for simplification but this isn’t one of them. Let’s close this I feel after a rethink this isn’t worth perusing at this time or has low value.
