### ISSUE TITLE
ConvertTo-PnPClientSidePage always create a new modern page with "Site Page" as default content type

### ISSUE THREAD

**Issue by ashwane** [SharePoint/sp-dev-modernization#185]
I run below command -

ConvertTo-PnPClientSidePage -Identity NewTest -PublishingPage -Overwrite -TargetWebUrl https://xxx.sharepoint.com/sites/Modernc -PageLayoutMapping c:\temp\custompagelayoutmapping.xml 

It always create a new page i,e NewTest.aspx with ContentType="Site Page" - and it doesn't copy all my metadata as my target list 'Site Pages' has multiple content types enabled ex:- PnPContentType which defines my custom columns that should be copied from source but this is  not happening.
If i update my new modern page NewTest.aspx -> ContentType ="PnPContentType" and re-run the "ConvertTo-PnPClientSidePage" it does copy all the metadata values. My xml(copylayoutmapping.xml) is attached.

Is there any way we can set modern page content type to custom content type i,e "PnPContentType" ?

Thanks In Advance.

[copylayoutmapping.txt](https://github.com/SharePoint/sp-dev-modernization/files/3281413/copylayoutmapping.txt)

**Comment by jansenbe** [comment]
Hi @ashwane ,

I just did a test on assigning the content type works for me. Some things to check: 
- You only have one custom content type named PnPContentType and it inherits from the "Site Page" content type?
- Can you enable logging and see if you actually get to the part where the metadata is handled, I think you're getting an error and therefore the page transformation does not fully complete. See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell#use-the-logging-features-as-of-june-2019-release-version-3101906 to learn more about setting up logging

**Comment by ashwane** [comment]
Hey @jansenbe you pointed me in right direction - Thank you so much (saves my life)
Yes, My custom content type "PnPContentType" was derived from parent "WebPartPage" - I changed back to 'Site Page' and it started assigning my custom content type with metadata values as well. All Good now.

Appreciate your efforts. Amazed how quickly you fix things.
