### ISSUE TITLE
Idea: Transformation of Classic Wiki into other modern types

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#186]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

I saw this link: [https://twitter.com/thatmattwade/statuses/1139200384474451968](https://twitter.com/thatmattwade/statuses/1139200384474451968) and got me thinking modernisation, there is more that one type of target to consider:

- Classic SP Wiki to Teams WIki
- Classic SP Wiki to OneNote

Just a thought if there is interest in that option, or if its possible.  Its quite a radical new mode and probably need a significant code change.

At this point, its just geeky coolness rather than actual demand - however this maybe a consideration since SharePoint/Teams as there is an overlap nowadays.

**Comment by jansenbe** [comment]
:-)

If we would have an infinite amount of time...

**Comment by jansenbe** [comment]
@pkbullock : will close this as there are too many differences to pull this off. Feel free to bring this up again in the future.
