### ISSUE TITLE
Mapping File Schema Version Change Notice

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#188]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

When we update the mapping files, have a version in the schema or default mappings, so that if the customer is using a custom one then they know the schema has changed to a newer version.

**Comment by jansenbe** [comment]
Good feedback @pkbullock

**Comment by jansenbe** [comment]
Hey @pkbullock ,

There are 2 levels of versioning here:
- The version of the schema
- The version of the default provided mapping files

We already had schema versioning from the beginning via the namespace (e.g. http://schemas.dev.office.com/PnP/2018/01/PageTransformationSchema). I plan to only bump that one when there's fundamental (breaking) changes, so I did not update this for the small optional elements we've added.

For the default file version, I've provided a version attribute in the top-level element: this now will make it easy to identify the version of a mapping file and allows one to understand if the default mapping files have been upgraded or not. This version attribute can also be used for versioning of custom mapping files. 

```XML
<PageTransformation xmlns="http://schemas.dev.office.com/PnP/2018/01/PageTransformationSchema" Version="1.0.1907.0">

<PublishingPageTransformation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.dev.office.com/PnP/2019/03/PublishingPageTransformationSchema" Version="1.0.1907.0">
```
