### ISSUE TITLE
Multi-Lingual StaticString functions

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#189]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

When working with transforming content, to produce a design to clients requirements there are some areas where I am using StaticStrings function for web part titles, properties etc. However, for Multi-Lingual Scenarios where the content is transforming into the respective language these titles will remain the same. 

Ideally, having a variant on the static string would be good e.g. LCID,"String"; combination - so when transforming to a site with a (primary) different language the appropriate string is used.

For the moment, I am having to use multiple mapping files for each language.

**Comment by jansenbe** [comment]
Multiple mapping files indeed is a workaround here...once we have multilingual modern pages we'll need to work to support these...would rather integrate that enhancement at that point, unless you feel the workaround is too troublesome for you?

**Comment by pkbullock** [comment]
Happy to wait and bundle, will comment back if it reaches that point. 😊

**Comment by pkbullock** [comment]
@jansenbe i'm thinking of closing this one, from what i have seen from the new capabilities this feature isn't relevant or i cannot see any meaningful use for this one.

**Comment by jansenbe** [comment]
@pkbullock :
Agreed, let's close. Supporting multi-lingual modern pages when transforming from a classic portal setup with variations might make sense, but variations usage is quite low so I'm waiting until I see real demand for such a capability.
