### ISSUE TITLE
Highlighted Content Web Part not filtering based on user profile custom property

### ISSUE THREAD

**Issue by ashwane** [SharePoint/sp-dev-modernization#190]
Hi Team,

I am wondering if someone can help me on this OR i need to post in another forum.

I am designing my company's modern intranet and requirement is to filter news/pages based on user location.

I am using HCWP for displaying news and managed property for filtering them.

Custom Profile Property -  AureconOfficeTest 
Managed Property - RefinableString00

RefinableString00 "equals" {User.AureconOfficeTest.Name} does not work.

RefinableString00 "equals" Australia does work without any issues.

I even tried by using OOTB user profile property by following ways.

RefinableString00 "equals" {User.SPS-Location} does not work.
RefinableString00 "equals" {User.ContactInformation.SPS-Location} does not work.

Am I using correct user profile property token OR missing anything ? Is ther any way I can troubleshoot - Please help.(Attached the screenshots)

![Custom_UserProfileProperty](https://user-images.githubusercontent.com/31452750/59740870-b5954680-92ac-11e9-84f8-7b35a459661c.png)
![SharepointModern_Page](https://user-images.githubusercontent.com/31452750/59740871-b5954680-92ac-11e9-8eb0-166b89ea429d.png)

**Comment by jansenbe** [comment]
I've asked the HCWP team to provide feedback. Stay tuned for an update

**Comment by ashwane** [comment]
That's great..Thanks @jansenbe - You are so quick..

**Comment by jansenbe** [comment]
Hey @ashwane , currently using KQL variables (like {User.SPS-Location}) does not work. It's, however, something that we plan to implement in the future as part of the feature to specify your own custom queries in HCWP.

**Comment by ashwane** [comment]
thanks @jansenbe as always.
