### ISSUE TITLE
Summary Links/Quick Links Transform Improvements

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#191]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

In the case where we transform Summary Links to Quick Links, the configuration of Quick Links e.g. Layout, Descriptions, alignments etc isn't configurable (from what I can see). 

I would like to be able to specify or configure the following blocks (example JSON for Quick Links Web Part):

```json

"properties": {
    "items": [
      {
        "sourceItem": {
          "itemType": 2,
          "fileExtension": "",
          "progId": ""
        },
        "thumbnailType": 3,
        "id": 2
      },
      {
        "sourceItem": {
          "itemType": 2,
          "fileExtension": "",
          "progId": ""
        },
        "thumbnailType": 3,
        "id": 1
      }
    ],
    **"isMigrated": true,
    "layoutId": "Button",
    "shouldShowThumbnail": true,
    "buttonLayoutOptions": {
      "showDescription": false,
      "buttonTreatment": 3,
      "iconPositionType": 2,
      "textAlignmentVertical": 1,
      "textAlignmentHorizontal": 2,
      "linesOfText": 2
    },
    "listLayoutOptions": {
      "showDescription": false,
      "showIcon": true
    },
    "waffleLayoutOptions": {
      "iconSize": 1,
      "onlyShowThumbnail": false
    },
    "hideWebPartWhenEmpty": true,**
    "dataProviderId": "QuickLinks",
    "webId": "7b178d79-89cf-4dbf-a67d-8de2e9920117",
    "siteId": "e9c7463c-7046-460d-82c7-2cd7fcf20810"
  }
```

between the RED bits (GitHub didn't like formatting example JSON). This would allow to control the presentation of the web part. Ideally, configured via the mapping file would be ideal.

**Comment by jansenbe** [comment]
@pkbullock : you could today update the webpartmapping file to change the defaults or use multiple web part mapping files. I could make it more configurable OOB but then I need to introduce additional mapping parameters...can maybe add 1 or 2 but adding all possible options will lead to too many parameters in my opinion.

**Comment by pkbullock** [comment]
@jansenbe I couldn't see how to map this, looking at this:

```xml
<Mapping Name="UseQuickLinks" Default="false" Functions="SummaryLinksToQuickLinksProperties({SummaryLinkStore})">
            <!-- Summary links html is tranformed to the quicklinks web part -->
            <ClientSideWebPart Type="QuickLinks" Order="10" JsonControlData="&#123;&quot;serverProcessedContent&quot;&#58;&#123;&quot;htmlStrings&quot;&#58;&#123;&#125;,&quot;searchablePlainTexts&quot;&#58;&#123;&quot;title&quot;&#58;&quot;{Title}&quot;{SearchablePlainTexts}&#125;,&quot;imageSources&quot;&#58;&#123;{ImageSources}&#125;,&quot;links&quot;&#58;&#123;&quot;baseUrl&quot;&#58;&quot;{EncodedWeb}&quot;{Links}&#125;,&quot;componentDependencies&quot;&#58;&#123;&quot;layoutComponentId&quot;&#58;&quot;706e33c8-af37-4e7b-9d22-6e5694d92a6f&quot;&#125;&#125;,&quot;dataVersion&quot;&#58;&quot;2.1&quot;,&quot;properties&quot;&#58;{JsonProperties}&#125;"/>
          </Mapping>       

```
in the section: properties&quot;&#58;{JsonProperties} (decoded: "properties":{JsonProperties}) 

The token replacement replaces the inserts properties block including the braces, which is set by the SummaryLinksToQuickLinksProperties function - which led me to believe this isn't mappable.

We could specify in one parameter the JSON block to include e.g. AdditonalJsonProperties - specifically in the Web Part Mapping file.

What you think?

**Comment by jansenbe** [comment]
Right...this web part uses another flow due to it's complexity. 

What are the key settings you're looking into?

**Comment by jansenbe** [comment]
Possible solution:
- add JSON properties web part property to webpartmapping for SummaryLinks wp
- provide that property into SummaryLinksToQuickLinksProperties function
- when provided to SummaryLinksToQuickLinksProperties, use the set properties else use the current defaults
- Add property to webpart mappings in the page layout mapping files, use the staticString function to provide a JSON (encoded) blob with the needed settings

**Comment by pkbullock** [comment]
> Right...this web part uses another flow due to it's complexity.
> What are the key settings you're looking into?

In this case the settings maybe dynamic depending on what layout option you choose, so this wouldn't be flexible.

> Possible solution

That makes sense, would be highly flexible. I have used (for reference for others) the ?MaintenanceMode=True during transform testing to grab the relevant section of the properties to include. We wouldn't need to change the code (in theory) if new layout options are added to the web part in the future.

**Comment by jansenbe** [comment]
@pkbullock : I've implemented this. See below snippet of how to provide custom QuickLinks properties. Currently only works for publishing page transformation, also note that you only need to specify the JSON elements that you want to override.

**Important:** You need to take the latest webpartmapping.xml file to make this work or update yours accordingly.

```XML
<WebParts>
        <Field Name="SummaryLinks" TargetWebPart="Microsoft.SharePoint.Publishing.WebControls.SummaryLinkWebPart, Microsoft.SharePoint.Publishing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" Row="1" Column="2">
          <!-- No function specified, means the content of the PublishingPageContent field will be assigned to the value of the first listed web part property -->
          <Property Name="SummaryLinkStore" Type="string" />
          <Property Name="Title" Type="string" Functions="EmptyString()"/>
          <Property Name="QuickLinksJsonProperties" Type="string" Functions="StaticString('{&quot;isMigrated&quot;: false, &quot;layoutId&quot;: &quot;Button&quot;, &quot;shouldShowThumbnail&quot;: true, &quot;buttonLayoutOptions&quot;: { &quot;showDescription&quot;: false, &quot;buttonTreatment&quot;: 1, &quot;iconPositionType&quot;: 2, &quot;textAlignmentVertical&quot;: 1, &quot;textAlignmentHorizontal&quot;: 2, &quot;linesOfText&quot;: 2}, &quot;listLayoutOptions&quot;: { &quot;showDescription&quot;: false, &quot;showIcon&quot;: true}, &quot;waffleLayoutOptions&quot;: { &quot;iconSize&quot;: 1, &quot;onlyShowThumbnail&quot;: false}, &quot;hideWebPartWhenEmpty&quot;: true}')" />
        </Field>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="1">
          <!-- No function specified, means the content of the PublishingPageContent field will be assigned to the value of the first listed web part property -->
          <Property Name="Text" Type="string" Functions="" />
        </Field>
      </WebParts>
```

**Comment by pkbullock** [comment]
@jansenbe Awesomeness!!
