### ISSUE TITLE
Strip Empty Paragraph Tags from Text Web Parts

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#192]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Transforming doesn't include blocks of empty text. 

#### Observed Behavior

This typically happens at the top of the text web part when transforming from a PublishingPageContents field.. The TextCleanUp doesn't appear to remove these. 

#### Steps to Reproduce

Create a classic publishing page with a block of text. Mapping for that field:

```xml
<Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="1">
<Property Name="Text" Type="String" />
</Field>
```
Am I missing a function in this page layout mapping fragment? Its specified in the web part mapping.

**Comment by jansenbe** [comment]
@pkbullock : A field looking empty often still has a set of P tags or a BR tag...there's some logic to eliminate these, but that does not seem to always work. I'll review and if needed improve.

**Comment by jansenbe** [comment]
Hi @pkbullock ,

There was a small issue in the function that checked for "empty" HTML, which I fixed. Now the TextSelector will return "Spacer" for empty text parts and by default will put a spacer web part in there. If you don't like that you can simply comment out the ClientSideWebPart node in the spacer mapping element.

```XML
      <WebPart Type="SharePointPnP.Modernization.WikiTextPart" CrossSiteTransformationSupported="true">
        <Properties>
          <!-- To turn off placeholders set the UsePlaceHolders property to false via the ReturnFalse() function. Set to true using the ReturnTrue() function -->          
          <Property Name="Text" Type="string" Functions="{UsePlaceHolders} = ReturnTrue(); {CleanedText} = TextCleanup({Text},{UsePlaceHolders})" />
        </Properties>        
        <!-- TextSelector does check the received html and if it's considered empty (e.g. <p></p>) it returns the value "Spacer", else "Text" is returned -->
        <Mappings Selector="TextSelector({CleanedText})">
          <Mapping Name="Text" Default="true">
            <ClientSideText Text="{CleanedText}" Order="10" />
          </Mapping>
          <Mapping Name="Spacer" Default="false">
            <!-- An "empty" piece of html is replaced by a spacer control to give the user flexibility to adjust the empty space.
                 You can fully drop empty parts by commenting the clientsidewebpart as an empty mapping results in the web part being dropped -->
            <ClientSideWebPart Type="Spacer" Order="10" JsonControlData="&#123;&quot;serverProcessedContent&quot;&#58;&#123;&quot;htmlStrings&quot;&#58;&#123;&#125;,&quot;searchablePlainTexts&quot;&#58;&#123;&#125;,&quot;imageSources&quot;&#58;&#123;&#125;,&quot;links&quot;&#58;&#123;&#125;&#125;,&quot;dataVersion&quot;&#58;&quot;1.0&quot;,&quot;properties&quot;&#58;&#123;&quot;autoHide&quot;&#58;true,&quot;height&quot;&#58;20&#125;&#125;"/>
          </Mapping>
        </Mappings>
      </WebPart>
```

**Comment by pkbullock** [comment]
Sweet!
