### ISSUE TITLE
The column "CanvasContent1" does not exist

### ISSUE THREAD

**Issue by colonelclaypoo** [SharePoint/sp-dev-modernization#193]
Hello,

first of all thanks for putting all the effort into the page transformation solution. 

SharePoint Online here.I was trying it out, attempting to convert a classic wiki page to a modern page. For this, I simply created a new one in our root site collections SitePages library. 

Unfortunately, the PowerShell cmdlet `ConvertTo-PnPClientSidePage -Identity 'convertMe' -Overwrite` throws an exception which would translate to: 

> The column "CanvasContent1" does not exist

I noticed that a new page is actually create in the SitePages library but it's inaccessible throwing 

> NoComponentId

in the browser.

I tried creating a new modern page in that library but using `Add-PnPClientSidePage -Name "convertMe" -LayoutType 'Article'` but I'm getting the same error message.

This error also occurs in /search of the tenant's root site. However, regular classic site collections under /sites work just fine.

Any idea what might be causing this?

Thanks a lot.

**Comment by pkbullock** [comment]
Sounds like the a feature for the modern pages isn't activated, have you tried activating as per this link:
[https://docs.microsoft.com/en-gb/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell#modern-site-pages-dont-work-on-the-site-i-want-to-transform-pages-in](https://docs.microsoft.com/en-gb/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell#modern-site-pages-dont-work-on-the-site-i-want-to-transform-pages-in)

Paul

**Comment by colonelclaypoo** [comment]
@pkbullock, thanks for pointing that out. I tried to enable the feature but can't:
`Enable-PnPFeature: The file "OfficeDevPnP.Core.resources" could not be found.`

Here's the results for our root site collection from the modernization scanner.
[results.xlsx](https://github.com/SharePoint/sp-dev-modernization/files/3306460/results.xlsx)

Are the publishing features interfering in any way with this?

Thanks.

**Comment by jansenbe** [comment]
Can you go to Site Settings --> Site Features (_layouts/15/ManageFeatures.aspx) and check that the below feature is enabled. If not enable it via the SharePoint UI:
![image](https://user-images.githubusercontent.com/7451219/59773858-a4e5d000-92ae-11e9-9cb3-dc1898e8102d.png)

**Comment by jansenbe** [comment]
Hey @colonelclaypoo , did the above get you unblocked?

**Comment by colonelclaypoo** [comment]
@jansenbe Yes, that did the trick. The Site Pages feature was indeed turned off although the library and items within it already existed. Thank you very much and keep up the good work. Case closed.
