### ISSUE TITLE
PublishingTargetPageName param to not included in result

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#194]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

When using the PublishingTargetPageName in PnP-PS parameter, once transform is complete, the return URL is based on the target file name.

#### Observed Behavior

The result includes the Source File name not taking into account the new target file name, thus the link is wrong.

#### Steps to Reproduce

Transform any publishing page with the PublishingTargetPageName specified.

**Comment by jansenbe** [comment]
Thanks for reporting this one @pkbullock , will fix this as part of the July release

**Comment by jansenbe** [comment]
Fixed.
