### ISSUE TITLE
Example Scripts

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#200]
#### Category

[ ] Bug
[X] Enhancement

#### Examples to add

Add more sample scripts for transformation
- Publishing Pages Examples
- Publishing Pages Examples with logging
- Processing library of pages 

All based on PnP PowerShell

**Comment by pkbullock** [comment]
@jansenbe we talked about adding example scripts - what is needed and I can contribute to those? Feel free to assign to me.

**Comment by jansenbe** [comment]
@pkbullock : as you're using PS scripts to perform transformation it would be good to share some of your more advanced scripts in https://github.com/SharePoint/sp-dev-modernization/tree/dev/Scripts/PageTransformation. Today there's a very basic example, but for example having a sample script that shows "real world" usage would be super useful for folks

**Comment by jansenbe** [comment]
Closing, thanks for your contribution @pkbullock
