### ISSUE TITLE
Url Rewrite - Issue with root addresses

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#205]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

URL Rewrite from root addresses -e.g. https://test.sharepoint.com or https://portal should be supported in URL rewrite transform.

#### Observed Behavior

HTML markup where there is a "/" all instances are replaced with the target web URL.

Discovered during on-prem testing but could apply to SharePoint online where the portal on root address is transformed.

**Comment by pkbullock** [comment]
@jansenbe please assign to me, already working on fix, issue raised as reference to others. Will include fix in SharePoint 2010 PR.

**Comment by jansenbe** [comment]
Merged @pkbullock 's fix for this one, closing now
