### ISSUE TITLE
Error creating modern page from Page library called Wiki

### ISSUE THREAD

**Issue by jathorpe** [SharePoint/sp-dev-modernization#206]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[X] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Clicked on "Create modern version" from a wiki page and a modern version would be created.

#### Observed Behavior

The "Create modern version" opened the Modernization Center and was processing the request but then received the message "Error: This function only supports the transformation of a single page. We found 0 pages for page skydrive3m.sharepoint.comundefined"

#### Steps to Reproduce

Go to the Page Library called "Wiki" and open a wiki page and click "Create modern version". The Modernization Center opens and starts processing the request and then the error appears on the Modernization Center page.

If I do these same steps but from the "Site Pages" Page library a modern version of the page is created.

sharepointpnp-pagetransformation-central-solution v1.0.0.4
sharepointpnp-pagetransformation-client-solution v1.0.0.2

**Comment by jansenbe** [comment]
Hi @jathorpe ,

The UI solution is currently lacking this feature, using PnP PowerShell (https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell#options-for-the-convertto-pnpclientsidepage-cmdlet) you can use the `-Library` parameter on the `ConvertTo-PnPClientSidePage` cmdlet to specify the list that contains the page to convert. 

Currently I cannot confirm if/when the UI solution will have this capability.

**Comment by jathorpe** [comment]
@jansenbe ,

Thanks for the response. Based on your feedback the UI solution is working as designed, so we can close this issue.
