### ISSUE TITLE
Error while Modernize the publishing pages of same subsite

### ISSUE THREAD

**Issue by sushanm** [SharePoint/sp-dev-modernization#207]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[Yes ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell

We are in the verge of modernize the  existing classic sites. We have sites and sub sites. We want to modernize this as is.(with sub site)
While we are modernizing the publishing pages getting error as: “Oops, seems source and target point to the same site collection...that's a no go for publishing portal page transformation!”  

#### Expected or Desired Behavior

We were expecting publishing page to modernize as is

#### Observed Behavior

NA

#### Steps to Reproduce

$subWeb = "https://<<Tenent>>.sharepoint.com/sites/<<Site>>/<<SubSite>>"
$siteContext = Connect-PnPOnline -Url $subWeb -UseWebLogin
$web = Get-PnPWeb -Connection $siteContext -Includes WebTemplate, Configuration, Description
$pages = Get-PnPListItem -List Pages -Query $query -Web $web
foreach ($page in $pages) {
ConvertTo-PnPClientSidePage -PublishingPage -Identity $page.FieldValues["FileLeafRef"] -TargetWebUrl $subWeb -LogFolder "c:temp\logs" -LogType File -DontPublish -SkipItemLevelPermissionCopyToClientSidePage
}

#### Submission Guidelines

_Delete this section after reading_

- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you checked the **"Page Transformation: Error during the setup/use of the Page Transformation UI solution"** checkbox then please provide:
  - The output of the following 2 PnP PowerShell statements: `Get-PnPStorageEntity` and `Get-PnPTenantServicePrincipalPermissionGrants`
  - The errors listed inside the browser's developer tools window (F12), if possible tested with Chrome as browser
  - The versions of the **sharepointpnp-pagetransformation-client-solution** and **sharepointpnp-pagetransformation-central-solution** solutions in your SharePoint tenant app catalog
- If you checked the **"Page Transformation: Error during the use of page transformation from PnP PowerShell"** checkbox then please provide:
  - The output you see in your PowerShell session
  - The output generated by calling `Get-PnPException`
  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
- If you checked the **"Page Transformation: Error during the use of page transformation from .Net"** checkbox then please provide:
  - The exact error message you get
  - The stack trace of the error
  - The version of the **SharePointPnP.Modernization.Framework.dll** assembly

Thanks for your contribution! Sharing is caring.

**Comment by pkbullock** [comment]
Hi @sushanm from looking at the script you need to specify a target URL other than the site $subWeb. For example typically for publishing pages you need to create a modern site and connect to the source site e.g. your publishing portal then specify a modern target URL. 

Hope that make sense.

**Comment by pkbullock** [comment]
I created a sample script that might help you out: https://github.com/SharePoint/sp-dev-modernization/blob/master/Scripts/PageTransformation/Convert-PublishingPages.ps1

**Comment by sushanm** [comment]
Thanks a lot for your reply, Can't we modernize the existing subsite as is with contents ?
Like our existing all site structure as below. Can't we retain that?

 https://tenentName.sharepoint.com/sites/SiteCollection/SubSite

**Comment by pkbullock** [comment]
You can convert a subsite into a communication site, just connect to the subsite address with Connect-PnP then target URL is the communication site. e.g.

Source: https://<tenant>.sharepoint.com/sites/ClassicPortal/SubSite
Target: https://<tenant>.sharepoint.com/sites/ModernPortal

A comm site is designed to be flat e.g. multiple comm sites with a hub site. I have done a similar project in a Bi-lingual Intranet with 1000 subsites and convert to hub site structure approx. 70 communication sites.

The transformation tool is only designed to convert pages + related assets, permissions etc, not whole lists, file migrations etc.

**Comment by sushanm** [comment]
Thanks for your kind reply, 
In our scenario we dont want to create new Modern site. Waht we want is to transform the existing site as is with same urls.

For example:
Before Modernize script run our site would be: https://.sharepoint.com/sites/ClassicPortal/SubSite
(this will have classic features)
After Modernize script run our site would be: https://.sharepoint.com/sites/ClassicPortal/SubSite
Our Modern site would be, with all modern transformed: https://.sharepoint.com/sites/ClassicPortal/SubSite
is this possible ?

**Comment by jansenbe** [comment]
Hi @sushanm ,

Looking at your earlier shared script you're transforming publishing pages and publishing pages are not meant to modernized in place. It's not supported to have classic publishing pages and modern pages in the same site collection, hence we force you to specify a modern target site collection when you're transforming publishing pages. The recommended modern site to replace a publishing portal is the modern communication site, this site however does not have sub sites, so it's recommended to create multiple of these modern communication sites and move pages from the "classic" sub sites in the respective modern communication sites. You can create a "structure" in by specifying a site collection as hub site and then join the other communication sites to that hub. @pkbullock has a good blog post explaining this model: https://capacreative.co.uk/2019/07/10/taking-the-leap-from-on-premises-portals-to-modern-sites/

**Comment by jansenbe** [comment]
Hi @sushanm ,

Are the above answers clear? If so please let us know so that we can close this issue. Thx.

**Comment by jansenbe** [comment]
Closing. @sushanm : feel free to create a new issue when you still have issues around this.
