### ISSUE TITLE
Page is an basic aspx page...can't currently transform that one, sorry!

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#21]
Hi,
Some pages in my Site Pages library give me the above error message others work fine.  Looking at the page metadata I cant figure out what the difference is. 

What causes this message?

**Comment by jansenbe** [comment]
Hi Russel,

Below is the [applied logic](https://github.com/SharePoint/sp-dev-modernization/blob/master/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Extensions/ListItemExtensions.cs#L24)...essentially if we can't identify the page as webpartpage, wikipage, clientsidepage or publishingpage we assume it's a basic aspx page. 

Can you check the list item fields for those pages? Can you edit these in SharePoint?

```C#
        public static string PageType(this ListItem item)
        {
            if (FieldExistsAndUsed(item, Constants.HtmlFileTypeField) && !String.IsNullOrEmpty(item[Constants.HtmlFileTypeField].ToString()))
            {
                if (item[Constants.HtmlFileTypeField].ToString().Equals("SharePoint.WebPartPage.Document", StringComparison.InvariantCultureIgnoreCase))
                {
                    return "WebPartPage";
                }
            }

            if (FieldExistsAndUsed(item, Constants.WikiField) && !String.IsNullOrEmpty(item[Constants.WikiField].ToString()))
            {
                return "WikiPage";
            }

            if (FieldExistsAndUsed(item, Constants.ClientSideApplicationIdField) && item[Constants.ClientSideApplicationIdField].ToString().Equals(Constants.FeatureId_Web_ModernPage.ToString(), StringComparison.InvariantCultureIgnoreCase))
            {
                return "ClientSidePage";
            }

            if (FieldExists(item, Constants.PublishingRollupImageField) && FieldExists(item, Constants.AudienceField))
            {
                return "PublishingPage";
            }

            if (FieldExistsAndUsed(item, Constants.WikiField))
            {
                return "WikiPage";
            }

            return "AspxPage";
        }
```

**Comment by russgove** [comment]
Hi Bert,
I have 2 sample pages. Home.aspx cannot be transformed , Home2.aspx  transforms just fine. 
I can edit both pages in  the browser, however when I edit Home.aspx none of the webparts show, it's just showing me an empty wiki page to edit.
they look the same when viewed in the libtrary:

![image](https://user-images.githubusercontent.com/2412956/50304057-f7a81180-045c-11e9-852f-35863e2d7550.png)

Home.aspx is item #1 is the Site pages list. Home2.aspx is item 17

when I hit Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(1) i get:
![image](https://user-images.githubusercontent.com/2412956/50304962-743bef80-045f-11e9-9308-fb3d4aa7f836.png)


when I hit Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17) i get:
![image](https://user-images.githubusercontent.com/2412956/50305042-b402d700-045f-11e9-8802-c7a21745cdbe.png)

So Home.aspx has no wiki content.

**Comment by russgove** [comment]
These pages are being migrated from on prem using sharegate. I redid the migration of just that page and the edit experience in the browser worked properly. (i.e. when i edit the page i can see all the webparts).

When I  run ConvertTo-PnPClientSidePage now i am getting:
![image](https://user-images.githubusercontent.com/2412956/50310914-76a74500-0471-11e9-8740-53f5a2420571.png)

**Comment by russgove** [comment]
Thanks bert,
here it is: the full file is attached
[image: image.png]

**Comment by jansenbe** [comment]
File is not shown when attached as to mail. Can you pasted the contents in here or alternatively send to me via email?

**Comment by russgove** [comment]
<?xml version="1.0" encoding="utf-8"?><entry xml:base="
https://tenantname.sharepoint.com/sites/sitename/_api/" xmlns="
http://www.w3.org/2005/Atom" xmlns:d="
http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="
http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"
xmlns:georss="http://www.georss.org/georss" xmlns:gml="
http://www.opengis.net/gml"
m:etag="&quot;42&quot;"><id>16bdbbc2-8b23-4b74-91a8-388ed8b671cb</id><category
term="SP.Data.SitePagesItem" scheme="
http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link
rel="edit"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/FirstUniqueAncestorSecurableObject"
type="application/atom+xml;type=entry"
title="FirstUniqueAncestorSecurableObject"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/FirstUniqueAncestorSecurableObject"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/RoleAssignments"
type="application/atom+xml;type=feed" title="RoleAssignments"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/RoleAssignments"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/AttachmentFiles"
type="application/atom+xml;type=feed" title="AttachmentFiles"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/AttachmentFiles"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/ContentType"
type="application/atom+xml;type=entry" title="ContentType"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/ContentType"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/GetDlpPolicyTip"
type="application/atom+xml;type=entry" title="GetDlpPolicyTip"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/GetDlpPolicyTip"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/FieldValuesAsHtml"
type="application/atom+xml;type=entry" title="FieldValuesAsHtml"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/FieldValuesAsHtml"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/FieldValuesAsText"
type="application/atom+xml;type=entry" title="FieldValuesAsText"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/FieldValuesAsText"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/FieldValuesForEdit"
type="application/atom+xml;type=entry" title="FieldValuesForEdit"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/FieldValuesForEdit"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/File"
type="application/atom+xml;type=entry" title="File"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/File"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/Folder"
type="application/atom+xml;type=entry" title="Folder"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/Folder"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/LikedByInformation"
type="application/atom+xml;type=entry" title="LikedByInformation"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/LikedByInformation"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/ParentList"
type="application/atom+xml;type=entry" title="ParentList"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/ParentList"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/Properties"
type="application/atom+xml;type=entry" title="Properties"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/Properties"
/><link rel="
http://schemas.microsoft.com/ado/2007/08/dataservices/related/Versions"
type="application/atom+xml;type=feed" title="Versions"
href="Web/Lists(guid'b4c8013a-d2d6-43b7-8658-7d04e71d993c')/Items(17)/Versions"
/><title /><updated>2018-12-21T18:35:19Z</updated><author><name
/></author><content
type="application/xml"><m:properties><d:FileSystemObjectType
m:type="Edm.Int32">0</d:FileSystemObjectType><d:Id
m:type="Edm.Int32">17</d:Id><d:ServerRedirectedEmbedUri m:null="true"
/><d:ServerRedirectedEmbedUrl></d:ServerRedirectedEmbedUrl><d:ContentTypeId>0x0101009D1CB255DA76424F860D91F20E6C4118009E883D84F9C04544A1DDBB9DB3D834C4</d:ContentTypeId><d:WikiField
m:null="true" /><d:ComplianceAssetId m:null="true"
/><d:Title>Home2</d:Title><d:CanvasContent1>&lt;div&gt;&lt;div
data-sp-canvascontrol="" data-sp-canvasdataversion="1.0"
data-sp-controldata="&amp;#123;&amp;quot;editorType&amp;quot;&amp;#58;&amp;quot;CKEditor&amp;quot;,&amp;quot;controlType&amp;quot;&amp;#58;4,&amp;quot;id&amp;quot;&amp;#58;&amp;quot;244efbd6-6cb5-4f4a-bfe7-12ae1d151b25&amp;quot;,&amp;quot;position&amp;quot;&amp;#58;&amp;#123;&amp;quot;controlIndex&amp;quot;&amp;#58;1.0,&amp;quot;zoneIndex&amp;quot;&amp;#58;1.0,&amp;quot;sectionIndex&amp;quot;&amp;#58;1,&amp;quot;sectionFactor&amp;quot;&amp;#58;8&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-rte=""&gt;&lt;p&gt;&lt;h2&gt;&lt;span&gt;
Welcome to your site!

&lt;/span&gt;&lt;/h2&gt;&lt;span&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;&lt;/span&gt;&lt;span&gt;&lt;p&gt;Add
a new image, change this welcome
text or add new lists to this page by
clicking the edit button above. You can
click on Shared Documents to add files
or on the calendar to create new team
events. Use the links in the getting
started section to share your site and
customize its look.

&lt;/p&gt;&lt;/span&gt;&lt;span&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;&lt;/span&gt;&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;div
data-sp-canvascontrol="" data-sp-canvasdataversion="1.0"
data-sp-controldata="&amp;#123;&amp;quot;editorType&amp;quot;&amp;#58;&amp;quot;CKEditor&amp;quot;,&amp;quot;controlType&amp;quot;&amp;#58;4,&amp;quot;id&amp;quot;&amp;#58;&amp;quot;b4ae81a2-1bea-4044-a482-b3b3259044b6&amp;quot;,&amp;quot;position&amp;quot;&amp;#58;&amp;#123;&amp;quot;controlIndex&amp;quot;&amp;#58;2.0,&amp;quot;zoneIndex&amp;quot;&amp;#58;1.0,&amp;quot;sectionIndex&amp;quot;&amp;#58;1,&amp;quot;sectionFactor&amp;quot;&amp;#58;8&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-rte=""&gt;&lt;p&gt;&lt;div&gt;&lt;strong&gt;Administration&lt;/strong&gt;&lt;ul&gt;&lt;li&gt;&lt;a
href="http&amp;#58;//google.com"&gt;Administration
Guide&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a
href="http&amp;#58;//google.com"&gt;Core
Brief&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a
href="http&amp;#58;//google.com"&gt;Directions
to Bentley Office&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="http&amp;#58;//
google.com"&gt;Helpdesk Quick Link&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a
href="http&amp;#58;//google.com"&gt;Values and Behaviours -
Bentley&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;div&gt;&lt;strong&gt;Corporate&lt;/strong&gt;&lt;ul&gt;&lt;li&gt;&lt;a
href="http&amp;#58;//google.com"&gt;sitename&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a
href="http&amp;#58;//google.com"&gt;Vision
Statement&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="http&amp;#58;//
google.com"&gt;Values and Behaviours&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a
href="http&amp;#58;//google.com"&gt;Safety &amp;amp; Environment Legal
Information&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="http&amp;#58;//
google.com"&gt;Safety, Health &amp;amp; Environment (SHE) Management
Standards&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="http&amp;#58;//
google.com"&gt;Environmental Performance
Standards&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href="http&amp;#58;//
google.com"&gt;Safety Performance
Standards&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;div&gt;&lt;strong&gt;Bentley
Business Plan&lt;/strong&gt;&lt;ul&gt;&lt;li&gt;&lt;a href="http&amp;#58;//
google.com"&gt;2011 Bentley Business
Plan&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a
href="http&amp;#58;//google.com"&gt;2012
Bentley Business
Plan&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;div&gt;&lt;strong&gt;Microsoft
Office Training Modules&lt;/strong&gt;&lt;ul&gt;&lt;li&gt;&lt;a
href="http&amp;#58;//google.com"&gt;Microsoft Office 2010 Training
Modules&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;div
data-sp-canvascontrol="" data-sp-canvasdataversion="1.0"
data-sp-controldata="&amp;#123;&amp;quot;editorType&amp;quot;&amp;#58;&amp;quot;CKEditor&amp;quot;,&amp;quot;controlType&amp;quot;&amp;#58;4,&amp;quot;id&amp;quot;&amp;#58;&amp;quot;a827b7de-9c9e-4c8e-b4fc-a4d3c8e1c6e9&amp;quot;,&amp;quot;position&amp;quot;&amp;#58;&amp;#123;&amp;quot;controlIndex&amp;quot;&amp;#58;3.0,&amp;quot;zoneIndex&amp;quot;&amp;#58;1.0,&amp;quot;sectionIndex&amp;quot;&amp;#58;1,&amp;quot;sectionFactor&amp;quot;&amp;#58;8&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-rte=""&gt;&lt;p&gt;&lt;span&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;&lt;/span&gt;&lt;span&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;&lt;/span&gt;&lt;span&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;&lt;/span&gt;&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;div
data-sp-canvascontrol="" data-sp-canvasdataversion="1.0"
data-sp-controldata="&amp;#123;&amp;quot;editorType&amp;quot;&amp;#58;&amp;quot;CKEditor&amp;quot;,&amp;quot;controlType&amp;quot;&amp;#58;4,&amp;quot;id&amp;quot;&amp;#58;&amp;quot;bd013094-aa98-45dc-b0c0-d7a149e41325&amp;quot;,&amp;quot;position&amp;quot;&amp;#58;&amp;#123;&amp;quot;controlIndex&amp;quot;&amp;#58;1.0,&amp;quot;zoneIndex&amp;quot;&amp;#58;1.0,&amp;quot;sectionIndex&amp;quot;&amp;#58;2,&amp;quot;sectionFactor&amp;quot;&amp;#58;4&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-rte=""&gt;&lt;p&gt;&lt;span class="fontColorThemeDarker"&gt;&lt;p
style="text-align&amp;#58;left;"&gt;

&lt;/p&gt;&lt;/span&gt;&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;div
data-sp-canvascontrol="" data-sp-canvasdataversion="1.0"
data-sp-controldata="&amp;#123;&amp;quot;webPartId&amp;quot;&amp;#58;&amp;quot;d1d91016-032f-456d-98a4-721247c305e8&amp;quot;,&amp;quot;controlType&amp;quot;&amp;#58;3,&amp;quot;id&amp;quot;&amp;#58;&amp;quot;d0130bfa-6969-4684-9f26-cf2940a9d0c2&amp;quot;,&amp;quot;position&amp;quot;&amp;#58;&amp;#123;&amp;quot;controlIndex&amp;quot;&amp;#58;2.0,&amp;quot;zoneIndex&amp;quot;&amp;#58;1.0,&amp;quot;sectionIndex&amp;quot;&amp;#58;2,&amp;quot;sectionFactor&amp;quot;&amp;#58;4&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-webpart="" data-sp-webpartdataversion="1.8"
data-sp-webpartdata="&amp;#123;&amp;quot;id&amp;quot;&amp;#58;&amp;quot;d1d91016-032f-456d-98a4-721247c305e8&amp;quot;,&amp;quot;instanceId&amp;quot;&amp;#58;&amp;quot;d0130bfa-6969-4684-9f26-cf2940a9d0c2&amp;quot;,&amp;quot;title&amp;quot;&amp;#58;&amp;quot;Image&amp;quot;,&amp;quot;description&amp;quot;&amp;#58;&amp;quot;Image&amp;quot;,&amp;quot;dataVersion&amp;quot;&amp;#58;&amp;quot;1.8&amp;quot;,&amp;quot;properties&amp;quot;&amp;#58;&amp;#123;&amp;quot;imageSourceType&amp;quot;&amp;#58;2,&amp;quot;altText&amp;quot;&amp;#58;&amp;quot;People
collaborating&amp;quot;,&amp;quot;fileName&amp;quot;&amp;#58;&amp;quot;copmanynameBentley.png&amp;quot;,&amp;quot;siteId&amp;quot;&amp;#58;&amp;quot;4f7ae9b5-ef91-4c7a-b319-6d03686f235b&amp;quot;,&amp;quot;webId&amp;quot;&amp;#58;&amp;quot;b7309131-2020-4ca2-9308-5c0515f0abc3&amp;quot;,&amp;quot;listId&amp;quot;&amp;#58;&amp;quot;b54b5a47-9c54-433f-b123-eb14a27962eb&amp;quot;,&amp;quot;uniqueId&amp;quot;&amp;#58;&amp;quot;f87df8ff-6ed0-4c58-a82d-50e31ffa9804&amp;quot;,&amp;quot;useParallax&amp;quot;&amp;#58;false&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-componentid=""&gt;d1d91016-032f-456d-98a4-721247c305e8&lt;/div&gt;&lt;div
data-sp-htmlproperties=""&gt;&lt;div data-sp-prop-name="captionText"
data-sp-searchableplaintext="true"&gt;&lt;/div&gt;&lt;img
data-sp-prop-name="imageSource"
src="/sites/sitename/PublishingImages/copmanynameBentley.png"
/&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;div data-sp-canvascontrol=""
data-sp-canvasdataversion="1.0"
data-sp-controldata="&amp;#123;&amp;quot;editorType&amp;quot;&amp;#58;&amp;quot;CKEditor&amp;quot;,&amp;quot;controlType&amp;quot;&amp;#58;4,&amp;quot;id&amp;quot;&amp;#58;&amp;quot;86f84d97-6443-4c4a-b6f6-339ffe9b2f02&amp;quot;,&amp;quot;position&amp;quot;&amp;#58;&amp;#123;&amp;quot;controlIndex&amp;quot;&amp;#58;3.0,&amp;quot;zoneIndex&amp;quot;&amp;#58;1.0,&amp;quot;sectionIndex&amp;quot;&amp;#58;2,&amp;quot;sectionFactor&amp;quot;&amp;#58;4&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-rte=""&gt;&lt;p&gt;&lt;span&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;&lt;/span&gt;&lt;span&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;&lt;/span&gt;&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;div
data-sp-canvascontrol="" data-sp-canvasdataversion="1.0"
data-sp-controldata="&amp;#123;&amp;quot;editorType&amp;quot;&amp;#58;&amp;quot;CKEditor&amp;quot;,&amp;quot;controlType&amp;quot;&amp;#58;4,&amp;quot;id&amp;quot;&amp;#58;&amp;quot;6612b317-3337-4043-bc9b-85d764b9e214&amp;quot;,&amp;quot;position&amp;quot;&amp;#58;&amp;#123;&amp;quot;controlIndex&amp;quot;&amp;#58;4.0,&amp;quot;zoneIndex&amp;quot;&amp;#58;1.0,&amp;quot;sectionIndex&amp;quot;&amp;#58;2,&amp;quot;sectionFactor&amp;quot;&amp;#58;4&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-rte=""&gt;&lt;p&gt;&lt;br&gt;&lt;br&gt;&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;div
data-sp-canvascontrol="" data-sp-canvasdataversion="1.0"
data-sp-controldata="&amp;#123;&amp;quot;webPartId&amp;quot;&amp;#58;&amp;quot;20745d7d-8581-4a6c-bf26-68279bc123fc&amp;quot;,&amp;quot;controlType&amp;quot;&amp;#58;3,&amp;quot;id&amp;quot;&amp;#58;&amp;quot;4472e4d2-dd60-4d71-913e-b40297ce3590&amp;quot;,&amp;quot;position&amp;quot;&amp;#58;&amp;#123;&amp;quot;controlIndex&amp;quot;&amp;#58;5.0,&amp;quot;zoneIndex&amp;quot;&amp;#58;1.0,&amp;quot;sectionIndex&amp;quot;&amp;#58;2,&amp;quot;sectionFactor&amp;quot;&amp;#58;4&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-webpart="" data-sp-webpartdataversion="1.0"
data-sp-webpartdata="&amp;#123;&amp;quot;id&amp;quot;&amp;#58;&amp;quot;20745d7d-8581-4a6c-bf26-68279bc123fc&amp;quot;,&amp;quot;instanceId&amp;quot;&amp;#58;&amp;quot;4472e4d2-dd60-4d71-913e-b40297ce3590&amp;quot;,&amp;quot;title&amp;quot;&amp;#58;&amp;quot;Events&amp;quot;,&amp;quot;description&amp;quot;&amp;#58;&amp;quot;Events&amp;quot;,&amp;quot;dataVersion&amp;quot;&amp;#58;&amp;quot;1.0&amp;quot;,&amp;quot;properties&amp;quot;&amp;#58;&amp;#123;&amp;quot;selectedListId&amp;quot;&amp;#58;&amp;quot;3741d188-4ef3-45ca-b73d-5bfcd56f27a9&amp;quot;,&amp;quot;selectedCategory&amp;quot;&amp;#58;&amp;quot;&amp;quot;,&amp;quot;dateRangeOption&amp;quot;&amp;#58;0,&amp;quot;startDate&amp;quot;&amp;#58;&amp;quot;&amp;quot;,&amp;quot;endDate&amp;quot;&amp;#58;&amp;quot;&amp;quot;,&amp;quot;isOnSeeAllPage&amp;quot;&amp;#58;false,&amp;quot;layoutId&amp;quot;&amp;#58;&amp;quot;FilmStrip&amp;quot;,&amp;quot;dataProviderId&amp;quot;&amp;#58;&amp;quot;Event&amp;quot;,&amp;quot;webId&amp;quot;&amp;#58;&amp;quot;b7309131-2020-4ca2-9308-5c0515f0abc3&amp;quot;,&amp;quot;siteId&amp;quot;&amp;#58;&amp;quot;4f7ae9b5-ef91-4c7a-b319-6d03686f235b&amp;quot;&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-componentid=""&gt;20745d7d-8581-4a6c-bf26-68279bc123fc&lt;/div&gt;&lt;div
data-sp-htmlproperties=""&gt;&lt;div data-sp-prop-name="title"
data-sp-searchableplaintext="true"&gt;&lt;/div&gt;&lt;a
data-sp-prop-name="baseUrl"
href="/sites/sitename"&gt;&lt;/a&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;div
data-sp-canvascontrol="" data-sp-canvasdataversion="1.0"
data-sp-controldata="&amp;#123;&amp;quot;editorType&amp;quot;&amp;#58;&amp;quot;CKEditor&amp;quot;,&amp;quot;controlType&amp;quot;&amp;#58;4,&amp;quot;id&amp;quot;&amp;#58;&amp;quot;63f5dde4-21a1-4028-85a4-3856603426ea&amp;quot;,&amp;quot;position&amp;quot;&amp;#58;&amp;#123;&amp;quot;controlIndex&amp;quot;&amp;#58;6.0,&amp;quot;zoneIndex&amp;quot;&amp;#58;1.0,&amp;quot;sectionIndex&amp;quot;&amp;#58;2,&amp;quot;sectionFactor&amp;quot;&amp;#58;4&amp;#125;&amp;#125;"&gt;&lt;div
data-sp-rte=""&gt;&lt;p&gt;&lt;span&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;&lt;/span&gt;&lt;span&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;&lt;/span&gt;&lt;span&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;&lt;/span&gt;&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;</d:CanvasContent1><d:BannerImageUrl
m:type="SP.FieldUrlValue"><d:Description>
https://tenantname.sharepoint.com/_layouts/15/getpreview.ashx?guidSite=4f7ae9b5-ef91-4c7a-b319-6d03686f235b&amp;guidWeb=b7309131-2020-4ca2-9308-5c0515f0abc3&amp;guidFile=f87df8ff-6ed0-4c58-a82d-50e31ffa9804
</d:Description><d:Url>
https://tenantname.sharepoint.com/_layouts/15/getpreview.ashx?guidSite=4f7ae9b5-ef91-4c7a-b319-6d03686f235b&amp;guidWeb=b7309131-2020-4ca2-9308-5c0515f0abc3&amp;guidFile=f87df8ff-6ed0-4c58-a82d-50e31ffa9804</d:Url></d:BannerImageUrl><d:Description
xml:space="preserve">
Welcome to your site!
                                         Add a new image, change this
welcome
text or add new lists to this page by
clicking the edit button above. You can
click on Shared Documents to add files
or on the calendar to create</d:Description><d:PromotedState
m:type="Edm.Double">0</d:PromotedState><d:FirstPublishedDate m:null="true"
/><d:LayoutWebpartsContent>&lt;div&gt;&lt;div data-sp-canvascontrol=""
data-sp-canvasdataversion="1.4"
data-sp-controldata="&amp;#123;&amp;quot;id&amp;quot;&amp;#58;&amp;quot;cbe7b0a9-3504-44dd-a3a3-0e5cacd07788&amp;quot;,&amp;quot;instanceId&amp;quot;&amp;#58;&amp;quot;cbe7b0a9-3504-44dd-a3a3-0e5cacd07788&amp;quot;,&amp;quot;title&amp;quot;&amp;#58;&amp;quot;Title
Region&amp;quot;,&amp;quot;description&amp;quot;&amp;#58;&amp;quot;Title
Region
Description&amp;quot;,&amp;quot;serverProcessedContent&amp;quot;&amp;#58;&amp;#123;&amp;quot;htmlStrings&amp;quot;&amp;#58;&amp;#123;&amp;#125;,&amp;quot;searchablePlainTexts&amp;quot;&amp;#58;&amp;#123;&amp;#125;,&amp;quot;imageSources&amp;quot;&amp;#58;&amp;#123;&amp;#125;,&amp;quot;links&amp;quot;&amp;#58;&amp;#123;&amp;#125;&amp;#125;,&amp;quot;dataVersion&amp;quot;&amp;#58;&amp;quot;1.4&amp;quot;,&amp;quot;properties&amp;quot;&amp;#58;&amp;#123;&amp;quot;title&amp;quot;&amp;#58;&amp;quot;Home2&amp;quot;,&amp;quot;imageSourceType&amp;quot;&amp;#58;4,&amp;quot;layoutType&amp;quot;&amp;#58;&amp;quot;NoImage&amp;quot;,&amp;quot;textAlignment&amp;quot;&amp;#58;&amp;quot;Left&amp;quot;,&amp;quot;showTopicHeader&amp;quot;&amp;#58;false,&amp;quot;showPublishDate&amp;quot;&amp;#58;false,&amp;quot;topicHeader&amp;quot;&amp;#58;&amp;quot;&amp;quot;&amp;#125;&amp;#125;"&gt;&lt;/div&gt;&lt;/div&gt;</d:LayoutWebpartsContent><d:OData__AuthorBylineId
m:null="true" /><d:_AuthorBylineStringId m:null="true"
/><d:OData__TopicHeader m:null="true" /><d:OData__OriginalSourceUrl
m:null="true" /><d:OData__OriginalSourceSiteId m:null="true"
/><d:OData__OriginalSourceWebId m:null="true"
/><d:OData__OriginalSourceListId m:null="true"
/><d:OData__OriginalSourceItemId m:null="true" /><d:ID
m:type="Edm.Int32">17</d:ID><d:Created
m:type="Edm.DateTime">2018-12-20T13:56:25Z</d:Created><d:AuthorId
m:type="Edm.Int32">9</d:AuthorId><d:Modified
m:type="Edm.DateTime">2018-12-21T13:39:32Z</d:Modified><d:EditorId
m:type="Edm.Int32">9</d:EditorId><d:OData__CopySource m:null="true"
/><d:CheckoutUserId m:null="true"
/><d:OData__UIVersionString>42.0</d:OData__UIVersionString><d:GUID
m:type="Edm.Guid">3112ba65-9b7f-438a-bd76-b9c4c3a273cc</d:GUID></m:properties></content></entry>

**Comment by jansenbe** [comment]
CanvasContent1 and LayoutWebpartsContent are filled, this already is a modern page. Was this created by ShareGate? Somehow the ClientSideApplicationId field is not present, which is what I use to detect a modern page...looks really weird

**Comment by russgove** [comment]
Hi, yes it was created by sharegate. It was migrated from an on prem 2010
farm.
It doesnt look modern to me (heres what i see when I edit the page:
[image: image.png]

**Comment by russgove** [comment]
Ah, sharegate has a setting when migrating to 'Convert lists to modern
experience'. I had that turned on. Let me turn it off and try again.....

**Comment by russgove** [comment]
OK , I tested with and without that setting. 
Sharegate seems to ALWAYs add  CanvasContent1 and LayoutWebpartsContent

![image](https://user-images.githubusercontent.com/2412956/50379189-c83a0600-0610-11e9-8464-1b95e553fbd5.png)

**Comment by russgove** [comment]
btw. Its sharegate v 9.0.2

**Comment by jansenbe** [comment]
Interesting...I checked the canvascontent1 field and clearly contains the html structure for a modern client side page...but somehow the ClientSideApplicationId field is not configured with the modern page feature id (=B6917CB1-93A0-4B97-A84D-7CF49975D4EC). Somehow someone experimented with this page resulting in an invalid setup...you could try with setting the ClientSideApplicationId field

**Comment by jansenbe** [comment]
Hi @russgove,

Any update on this one? It's interesting to understand how that page got created

**Comment by russgove** [comment]
Hi Bert,
The page was migrated to spo from a  2010 on prem page using sharegate. 
I'm going to close  this issue because we are not sure whether the site will be moved to SPO or another platform..

**Comment by berryst2** [comment]
Hi,
I'm getting this error when we tried doing the modern page conversion.
we copied the pages/files from on-premises SP 2013 to SPO using ShareGate. 
we'd like to investigate this further to understand what could be done so that we can modernise the classic publishing pages to modern pages....

**Comment by RalphBoccalini** [comment]
I am facing the same issue on multiple sites that we are trying to modernize, is there any solution about this topic?
