### ISSUE TITLE
/_layouts/15/settings.aspx does not got modernized

### ISSUE THREAD

**Issue by sushanm** [SharePoint/sp-dev-modernization#210]
[X] Bug
[ ] Enhancement

#### Problem Area
We wanted to modernize our classic SharePoint online site to modern site. 
Steps followed
1) Ran the site modernization script for a site collection. 
 All the pages, lists, libraries got transformed into modern, except 
1) /_layouts/15/settings.aspx -- Shows all old look and feel.
2) Faveicon in settings.aspx page still old, it did not transformed (In all other site pages, lists, libraries looks and feel is modern) 
3) We have a mega menu at the top of site, this did not applied to settings.aspx page (all other site pages this is showing)

#### Expected or Desired Behavior
Settings page also need to transformed as modern

#### Observed Behavior
Settings.aspx page retained old look and feel

#### Steps to Reproduce
I have run the site modernization script.

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by pkbullock** [comment]
Hi @sushanm 

The modernisation tooling is not designed to process system pages e.g. anything under _layouts/15/… only your page content in Wiki Page, Web Part Page and Publishing Page type content. 

Layout pages is done by Microsoft server side as part of the effort to update the user interfaces. Not all areas of SharePoint Online have been modernised the settings area represents one of those areas. 

The only thing I can suggest, is raise a user voice to get this modernised with enough support from others wanting the same requirement: https://sharepoint.uservoice.com/

**Comment by sushanm** [comment]
Thank you for the prompt reply.
How do we modernize 'default.apx'  residing at: https://tenent.sharepoint.com/sites/siteCollection/default.aspx

**Comment by pkbullock** [comment]
If you have not see this  excellent resource, I'd recommend reviewing the PnP Transformation playlist for the operations required to use the tooling:  [https://www.youtube.com/playlist?list=PLR9nK3mnD-OXBJr5tcAqxqSn2vwvRYgeZ](https://www.youtube.com/playlist?list=PLR9nK3mnD-OXBJr5tcAqxqSn2vwvRYgeZ) - this will help you to get started, the types of pages and what commands to run to get going.

**Comment by jansenbe** [comment]
Hi @sushanm ,

As already mentioned by @pkbullock the settings.aspx page is a system page which is shared across all sites. We (Microsoft) need to create a modern version of this page, I'll check if this work is already planned. 

When it comes to modernizing a page in the root of the site collection you can follow the guidance in https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell#transform-a-pages-that-lives-at-the-root-of-the-site-so-outside-of-a-library. This is a feature we recently added.

**Comment by jansenbe** [comment]
Closing. @sushanm : feel free to create a new issue when you still have issues around this.
