### ISSUE TITLE
Struggling to map Page thumbnail and include asset transfer

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#213]
#### Category

- [X] Bug
- [ ] Enhancement
- [X] User Error

#### Problem Area

-  [ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
- [ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
- [X] Page Transformation: Error during the use of page transformation from .Net
- [ ] Page Transformation: Page is not looking correct after transformation
- [ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Trying to transform a PublishingPageImage field to the BannerImageUrl field for the page thumbnail field.

#### Observed Behavior

Transform does not transfer the asset or update the URL and still references the source. 
Have I got the mapping wrong? My understanding in some parts of the mapping is still limited.

#### Steps to Reproduce

- Create a page with an image or two, an image that uses page controls and referenced in metadata such as PublishingPageImage.
- Add mapping

```
<MetaData>
<!-- default fields omitted for brevity -->
<Field Name="PublishingPageImage" TargetFieldName="BannerImageUrl" Functions="ReturnCrossSiteRelativePath(ToImageUrl({PublishingPageImage}))" />
</MetaData>
```
also tried
```
<MetaData>
<!-- default fields omitted for brevity -->
<Field Name="PublishingPageImage" TargetFieldName="BannerImageUrl" Functions="ToImageUrl({PublishingPageImage})" />
</MetaData>
```
still references source location. Any ideas?

**Comment by jansenbe** [comment]
Hey @pkbullock ,

The ways to configure the preview image of a page are documented here: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing#can-i-control-the-page-preview-image

So in your case I think you should be using this:

```XML
<MetaData>
<!-- default fields omitted for brevity -->
<Field Name="PublishingPageImage" TargetFieldName="BannerImageUrl" Functions="ToPreviewImageUrl({PublishingPageImage})" />
</MetaData>
```

If you have multiple fields containing images and you want a "fall back" mechanism in case your PublishingPageImage field is null then do something like this:

```XML
<MetaData>
<!-- default fields omitted for brevity -->
<Field Name="PublishingPageImage;Image2;Image3" TargetFieldName="BannerImageUrl" Functions="ToPreviewImageUrl({@Name})" />
</MetaData>
```

**Comment by pkbullock** [comment]
🤦‍♂️ Facepalm moment - read the docs. That worked, thanks for the pointer Bert.
