### ISSUE TITLE
URL Rewrite mapping not reflected on change

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#214]
#### Category

- [X] Bug
- [ ] Enhancement

#### Problem Area

- [ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
- [X] Page Transformation: Error during the use of page transformation from PnP PowerShell
- [ ] Page Transformation: Error during the use of page transformation from .Net
- [ ] Page Transformation: Page is not looking correct after transformation
- [ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Changes to the URL rewrite file should reflect in the next transform

#### Observed Behavior

Changes to the URL rewrite are not being reflected when the file changes.

See this in client transforms and can reproduce on my test rig, update tests to clear the cache with no effect.

#### Steps to Reproduce

- Create a source page with summary links
- Configure a URL mapping file, run transform
- Update the URL mapping file run transform again e.g. change the target URLs

Changes are not reflected using the updated mapping references

#### Example Mapping

```
"https://mytenant.sharepoint.com/sites/pnpSauce/en/Pages/News/Hot-Off-The-Press-New-Chilling-Truth-About-Sauce.aspx","https://mytenant.sharepoint.com/sites/PnPKatchup/SitePages/news/The-Cherry-on-the-Cake,-Transforming-to-Modern.aspx"
"https://mytenant.sharepoint.com/sites/PnPSauce/en/Pages/Article-SPO-New-London-Flagship-Store.aspx","https://bing.com"
```

**Comment by jansenbe** [comment]
Hey @pkbullock,

The Url mapping information is cached, in the current model you'll either have to start a new PS session if you change the mapping or alternatively do a call to `ConvertTo-PnPClientSidePage` with the `-ClearCache` parameter

**Comment by pkbullock** [comment]
Ok, I was slightly in error in my understanding of the original fault and I have done some debugging and figured out that i'm hitting this scenario:

Mapping files have full URL as source e.g. https://mytenant.sharepoint.com/sites/pnpSauce/en/Pages/News/Hot-Off-The-Press-New-Chilling-Truth-About-Sauce.aspx

However, this is not rewriting for Summary Links web part, because SP makes then relative in the source web part, thus its not matching in the RewriteUrl method.

By making the mapping relative this works. However, this would mean that I would need both relative and non-relative paths in the mapping file, so that i'm not excluding the text web parts.

**Comment by pkbullock** [comment]
I was also hitting the caching, when I was tweaking the CSV file and not seeing affect, so its good to know that when SMEs are fine tuning.

**Comment by jansenbe** [comment]
The *default* URL mapping will do relative and non relative paths automatically, but as you've noticed when you specify custom mappings you'll need to specify both in case you need both.
