### ISSUE TITLE
Page Layout Alias in mapping file

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#217]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

Page Layout Mapping

#### Expected or Desired Behavior

I would like the option to have a mapping, with an "alias" that if there are other page layouts that are almost identical, the mapping can apply to those as well, I didn't have to maintain two or more near exact mappings. 

The mapping attribute could be called "AlsoAppliesTo" - then the names, comma delimited of the page layouts to apply the mapping to.

#### Observed Behavior

Each mapping is separate. It did lead to some maintenance issues were I had to ensure all the mappings were updated when a change was made.

**Comment by jansenbe** [comment]
That makes sense. Will look into how we best can do this.

**Comment by jansenbe** [comment]
@pkbullock : implemented via the AlsoAppliesTo optional attribute. You can specify a ; delimited list. See https://github.com/SharePoint/sp-dev-modernization/blob/dev/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework.Tests/Transform/Publishing/custompagelayoutmapping.xml for an example. Docs will follow as part of the release process
