### ISSUE TITLE
Remove full web part type reference from mapping files

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#218]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

In the mapping files, references to web parts use the full class reference in the type. e.g.

```xml
<WebPart Type="Microsoft.SharePoint.WebPartPages.ContentEditorWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" Row="1" Column="1">
</WebPart>
```

In the latest on-premises code, I have put in filters to remove part of this in order to match older versions. e.g. Microsoft.SharePoint.WebPartPages.ContentEditorWebPart

Additionally and fairly minor, it would improve readability of the mapping files for SMEs. Especially since all the examples have the Row/Column at the end.

#### Observed Behavior

See above code example.

**Comment by jansenbe** [comment]
Hey @pkbullock ,

Given the full references is just a small annoyance and I don't want to end up with 2 models I'm closing this one. Let's stick with what we have today. Hope you understand.
