### ISSUE TITLE
Option to disable default url rewrite when custom specified

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#219]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

On a recent project, when using the URL rewrite CSV, the default one wasn't required and in some cases got in the way.

#### Observed Behavior

The custom URLs worked great, but for links outside the scope of the CSV file, the default one still rewrites the base address. So if you are transforming a classic publishing site, it would update the URLs which brakes as they point to the new site, but an in a classic format.

e.g. https://tenant.sharepoint.com/sites/newsite/english/somesubsite/subsite/page.aspx 

An option to disable the default rewrite would be nice, but allow the custom only. The URLs would still continue to link to the original content.

**Comment by jansenbe** [comment]
That makes sense, will add this for next release.

**Comment by jansenbe** [comment]
@pkbullock : Implemented via the SkipDefaultUrlRewrite PageTransformationInformation property and the SkipDefaultUrlRewriting flag in PS.
