### ISSUE TITLE
Improved Feedback for Transform Status

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#224]
#### Category

- [ ] Bug
- [X] Enhancement

#### Problem Area

- [ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
- [X] Page Transformation: Error during the use of page transformation from PnP PowerShell
- [ ] Page Transformation: Error during the use of page transformation from .Net
- [ ] Page Transformation: Page is not looking correct after transformation
- [ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

During a transform a number of operations are performed, some take a while to process e.g. Asset Transfer of large files such as large images and video content give the impression to the SME that the operation has stalled in someway not knowing what is taking the time to process.

Just wondering if we can implement in PnP PowerShell something like the PnP Provisioning style feedback to show the processing stage and status. 

Its an idea hopefully requires not too much re-engineering.

**Comment by pkbullock** [comment]
Perhaps a powershell feedback can be done by adding a new type of observer that includes this

**Comment by jansenbe** [comment]
Hi @pkbullock , now that we have console logging in PS (committed that yesterday) I think this feature request is less relevant and maybe can be closed?

**Comment by pkbullock** [comment]
Happy with that closing.
