### ISSUE TITLE
Unable to get the image Caption/Alt-Text to populate

### ISSUE THREAD

**Issue by arnostac** [SharePoint/sp-dev-modernization#228]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

Publishing Page Transformation

[X] Bug
[ ] Enhancement

Image Caption/ ALT-TXT

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

I have attached log files and also and xml page map as well. there are two references to the image caption/ALT-Text. I am unable to get the alt-text to populate even with the title if there is no caption/alt-text

**Comment by arnostac** [comment]
[New folder.zip](https://github.com/SharePoint/sp-dev-modernization/files/3468577/New.folder.zip)
these are the files

**Comment by jansenbe** [comment]
Hi @arnostac ,

For the image caption you need to add the below type of line to your mapping:

```xml
<Property Name="Caption" Type="string" Functions="ToImageCaption({PublishingImageCaption})" />
```

Also you need to be using a recent version of the PnP PS as to make this work you'll need to latest webpartmapping, which is embedded in PnP PS.

**Comment by arnostac** [comment]
[Updated files.zip](https://github.com/SharePoint/sp-dev-modernization/files/3478590/Updated.files.zip)

**Comment by jansenbe** [comment]
Hey @arnostac ,

Apologies for the delayed response (vacation time)...Did have a look at the details you've shared and noticed that your pagemap.xml is not correct. Currently I see the following snippet in pagemap.xml:

```XML
<Field Name="PublishingRollupImage" TargetWebPart="SharePointPnP.Modernization.WikiImagePart" Row="1" Column="2" Order="1">
          <Property Name="ImageUrl" Type="string" Functions="ToImageUrl({PublishingRollupImage})"></Property>
          <Property Name="Caption" Type="string" Functions="ToImageCaption({PublishingRollupImage})"></Property>
          <Property Name="AlternativeText" Type="string" Functions="ToImageAltText({PublishingRollupImage})"></Property>
</Field>
```

Can you change this to and then try again:

```XML
<Field Name="PublishingRollupImage" TargetWebPart="SharePointPnP.Modernization.WikiImagePart" Row="1" Column="2" Order="1">
          <Property Name="ImageUrl" Type="string" Functions="ToImageUrl({PublishingRollupImage})"></Property>
          <Property Name="Caption" Type="string" Functions="ToImageCaption({PublishingImageCaption})"></Property>
          <Property Name="AlternativeText" Type="string" Functions="ToImageAltText({PublishingRollupImage})"></Property>
</Field>
```

The change is that you need to provide the **PublishingImageCaption** field as input for the ToImageCaption function as in a publishing page the caption is stored in a different field than the actual image.

**Comment by jansenbe** [comment]
Hi @arnostac ,

Did the above help? Can this issue be closed?

**Comment by arnostac** [comment]
Yes I was able to get this working i found that a previous consultant had modified the page layout to use a different field. So I had to modify the the pagemap.xml to use the static string function. 

`
<Property Name="Caption" Type="string" Functions="StaticString({tdiRollupImageCaption})"></Property>
<Property Name="AlternativeText" Type="string" Functions="StaticString({tdiRollupImageCaption})"></Property>
`

Thank You for the direction sorry for the delayed response
