### ISSUE TITLE
Classic and Modern page is not renamed when -TakeSourcePageName is used

### ISSUE THREAD

**Issue by PriyankaDevi510** [SharePoint/sp-dev-modernization#230]
#### Category

[*] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[*] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Classic page is expected to be renamed as "Previous_Pagename.aspx" and the modern to be "Pagename.aspx"

#### Observed Behavior

Classic page is named as "Pagename.aspx" and modern page as "Migrated_PageName.aspx" after conversion

#### Steps to Reproduce

Getting this at random cases. Unaware of the exact reason

**Comment by pkbullock** [comment]
Same as #229 can you include the logs so we can further diagnose and reproduce please?

**Comment by PriyankaDevi510** [comment]
Though TakePageSourceName switch is used, The modern page is  set to Migrated_Pagename.aspx in the log at line. no 88
[Page-Transformation-Report-8-9-2019-4-31-48-PM.txt] (https://github.com/SharePoint/sp-dev-modernization/files/3486088/Page-Transformation-Report-8-9-2019-4-31-48-PM.txt)

**Comment by jansenbe** [comment]
Hi @PriyankaDevi510 ,

Looking at the logs I see that there was an error while reading the item level permissions set on the home page. Possible (short term) workaround is to convert this page without taking over the item level permissions via the tool (you can do them manually if really needed).

I however also want to understand why this goes wrong: can you check the item level permissions for the failed page and check if you see any thing that pops out? Can you share the accounts set (please change names of persons and company to random values)?

**Comment by PriyankaDevi510** [comment]
Hi @jansenbe 

I have observed that, no distinct item level permission has been set to that home page. And I didn't get any Popup message too after the page modernization. Can you please elaborate over the other workaround (without taking over the item level permissions via the tool ) you suggested in the last comment.

**Comment by jansenbe** [comment]
Can you try the conversion with the **SkipItemLevelPermissionCopyToClientSidePage** parameter (see https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell#options-for-the-convertto-pnpclientsidepage-cmdlet) and see if that fixes things for you?

**Comment by jansenbe** [comment]
Hi @PriyankaDevi510, 

Did you manage to test with this parameter?

**Comment by PriyankaDevi510** [comment]
We are trying to replicate this issue, as the root cause of the issue is not known. Will get back as soon as possible with the updates.

**Comment by jansenbe** [comment]
Hey @PriyankaDevi510 ,

Any update from your side on this issue?

**Comment by jansenbe** [comment]
Hey @PriyankaDevi510 ,

I'm closing this issue. If you still get issues, even when skipping item level permission copy via the SkipItemLevelPermissionCopyToClientSidePage parameter (see https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell#options-for-the-convertto-pnpclientsidepage-cmdlet) then please create a new issue with the relevant data to debug this.
