### ISSUE TITLE
ConvertTo-PnPClientSidePage : Page 'test2.aspx' does not exist

### ISSUE THREAD

**Issue by s60aun** [SharePoint/sp-dev-modernization#24]
Hi,
I am following the article from https://developer.microsoft.com/en-us/sharepoint/blogs/modernize-your-sharepoint-pages/   and trying to use the cmdlet -

`ConvertTo-PnPClientSidePage : Page 'test2.aspx' does not exist`

When using the cmdlet I get the following error?
`ConvertTo-PnPClientSidePage : Page 'test2.aspx' does not exist
At line:1 char:1
+ ConvertTo-PnPClientSidePage -Identity test2.aspx -AddPageAcceptBanner
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage`

This page is a wikipage that does exist on the site.

**Comment by jansenbe** [comment]
@s60aun,

Does this wiki page live in the sitepages library? Do you have other wiki page libraries in that site?

**Comment by s60aun** [comment]
Hi @jansenbe,
The site contains 2 page libraries.  1 x Site Pages, 1 x WikiLibrary.
SiteTemplate: STS#0

No other page libraries on the site collection.

**Comment by jansenbe** [comment]
Hi @s60aun,

This is a known issue and has been fixed (https://github.com/SharePoint/PnP-PowerShell/commit/a0c466396fc3a51bae24e7674ec0638f7d074de7). The upcoming January 2019 release will have this fix. What happens is that the logic to find the wiki page finds the wiki library and not the site pages library. You can only have modern pages in the site pages library, so this implies you can only modernize pages living in the site pages library.

If you try the modernization cmdlet in a site collection without additional wiki page libraries it should work fine.

**Comment by jansenbe** [comment]
Hi @s60aun,

The January 2019 release from PnP-PowerShell has been released and this one contains a fix for your initial issue. I'm closing this issue now, but feel free to re-open or create a new one in case you still see the error when using the January 2019 PnP PowerShell release.

**Comment by TroyHostetter** [comment]
Hi @jansenbe .. we were seeing this issue on the latest version of the cmdlet and did not know if you had any suggestions.  The source site has 3 wikis and a Site Pages.  We can manually recreate, but were wondering if you had any thoughts that might help us.  Regards.

![image](https://user-images.githubusercontent.com/48290477/91086356-d2e64300-e61c-11ea-81d9-63b21e79b832.png)
