### ISSUE TITLE
Page shows up as draft, even if -dontpublish isn't passed to ConvertTo-PnPClientSidePage

### ISSUE THREAD

**Issue by ToddKlindt** [SharePoint/sp-dev-modernization#242]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[X] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

If the -dontpublish parameter is _not_ passed to ConvertTo-PnPClientSidePage the converted page will be published and at a Major Version

#### Observed Behavior

If Fields are added to the MetaData section of a custom page layout file those changes are made after the page is initially published and it's not published again afterwards. That leaves the page in a draft with a minor version. 

#### Steps to Reproduce
Using version 3.12.1908.1
Ad a line like this:
<Field Name="Created" TargetFieldName="Created" Functions="" />
to the MetaData section of the custompagelayout.xml file. Run ConvertTo-PnPClientSidePage using that page layout file and do not use the -Dontpublish switch. The page will convert, several changes will be made, it will be published, then the change specified will be made to the page but it will not be published again.

**Comment by jansenbe** [comment]
Nice catch @ToddKlindt. Will look into this and include a fix for the September release

**Comment by jansenbe** [comment]
@ToddKlindt 
Fixed. I've moved the publishing part to the very end of the transformation flow for both publishing pages and wiki/webpart pages. Will be part of the upcoming September release.
