### ISSUE TITLE
List Webpart's view not retained in Modern Page!

### ISSUE THREAD

**Issue by PriyankaDevi510** [SharePoint/sp-dev-modernization#244]
#### Category

[*] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[*] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
Modern page's List webpart should retain the view as in classic

#### Observed Behavior

User has customized the list webpart's view. After the Page upgradation to Modern, the View is not retained. It has been  set to the default list view

#### Steps to Reproduce

Add a list view webpart in a classic page. Edit the view using webpart properties. Convert it to modern using  ConvertTo-PnPClientSidePage -Identity pagename.aspx

**Comment by jansenbe** [comment]
Hi @PriyankaDevi510 ,

Are you doing a transformation of a wiki page and create the new modern page in the same site or are you creating the modern page in another site collection?

**Comment by PriyankaDevi510** [comment]
It is a webpart page. And we are upgrading in the same site only

**Comment by jansenbe** [comment]
The view detection will not always work, let me explain. 

**What happens in the classic web part**

- You put the XSLTListView web part on a page
- You select an existing view

If the list view query/fields/rowlimit was not changed after using it in the web part then the modern list/library web part should be able to find that view...however if there was a change in the underlying view then the view definition stored in the web part will be different than the view definition in the list and therefore we can't match up the views anymore.

Background: the view id property is not stored in the classic XSLTListViewWebPart and therefore we need to "try" to match up a view by comparing the view query/fields/rowlimit definition. The code that does this logic can be found here: https://github.com/SharePoint/sp-dev-modernization/blob/dev/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Functions/BuiltIn.cs#L496

You could try by setting the view again in the web part and then see if it's retained during modernization. If that still does not work then we'll need to compare the view definition in the web part with the actual view definition in the list and try to understand where the matching goes wrong.

**Comment by jansenbe** [comment]
Hi @PriyankaDevi510 , did the above clarify things for you?

**Comment by jansenbe** [comment]
Closing this issue. If you still have issues with this then please provide me with the view xml of the source view and the view xml of the view on the target list. I can then verify if our "matching" logic requires updates or not.
