### ISSUE TITLE
The solution doesn't build

### ISSUE THREAD

**Issue by varma31** [SharePoint/sp-dev-modernization#25]
There seems to be some files missing fro the solution/projects.

**Comment by jansenbe** [comment]
Hi @varma31,

Can you specify what errors you see on build? Which solution are you building?

**Comment by varma31** [comment]
SharePointPnP.Modernization solution is not building. From the visual studio it appears that the app.config files are missing in SharePointPnP.Modernization.Scanner, Tests, Sample Add-On Projects.
![error](https://user-images.githubusercontent.com/7084970/50771811-589f5a00-1251-11e9-93ed-31370f993f6f.png)

**Comment by jansenbe** [comment]
You can give these all a default app.config file to make the compilation work. Add below content to your app.config files:

```Xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
</configuration>
```

**Comment by varma31** [comment]
Thanks Bret, The App.config files were missing as well, I added those and then the xml above to compile them. Looks like VS 2017 is adding App.Config files to ignored from source control.

**Comment by jansenbe** [comment]
So it now works for you?

**Comment by jansenbe** [comment]
Hi @varma31, I assume the compilation issues are resolved and therefore I'll close this issue. Feel free to re-open this issue or create a new one if you still have problems with the modernization tools.
