### ISSUE TITLE
Highlighted Content Web Part - It does not respect Query rules which we have defined at Tenant level for query transformation. We are appending user token ({User.<property>}) in query rule. How can I force HCWP to use our query rule?

### ISSUE THREAD

**Issue by jayminpatel81** [SharePoint/sp-dev-modernization#254]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

#### Observed Behavior

_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce

_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

#### Submission Guidelines

_Delete this section after reading_

- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you checked the **"Page Transformation: Error during the setup/use of the Page Transformation UI solution"** checkbox then please provide:
  - The output of the following 2 PnP PowerShell statements: `Get-PnPStorageEntity` and `Get-PnPTenantServicePrincipalPermissionGrants`
  - The errors listed inside the browser's developer tools window (F12), if possible tested with Chrome as browser
  - The versions of the **sharepointpnp-pagetransformation-client-solution** and **sharepointpnp-pagetransformation-central-solution** solutions in your SharePoint tenant app catalog
- If you checked the **"Page Transformation: Error during the use of page transformation from PnP PowerShell"** checkbox then please provide:
  - The output you see in your PowerShell session
  - The output generated by calling `Get-PnPException`
  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
- If you checked the **"Page Transformation: Error during the use of page transformation from .Net"** checkbox then please provide:
  - The exact error message you get
  - The stack trace of the error
  - The version of the **SharePointPnP.Modernization.Framework.dll** assembly

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hey @jayminpatel81 ,

In the September version of the page transformation we'll be using the custom query option of HCWP...so the search query in the CBS web part will be taken over in the HCWP. AFAIK this should then also support the user tokens (see https://github.com/SharePoint/sp-dev-modernization/issues/190) for a related question.

You can cross check this by pasting in your search query in the custom query field and see if you see the desired results.

**Comment by jansenbe** [comment]
Hey @jayminpatel81 ,

Did the above answer your questions? Did you try passing in a user token in the custom query field?

**Comment by jayminpatel81** [comment]
Thanks a lot @jansenbe ..I can use user token as well as other filters (like {Today}) in HCWP.

**Comment by popeadam** [comment]
Hey @jansenbe, this feature no longer appears to be working (on our tenant, at least). If I use the PnP search webpart, I'm getting the results through correctly with the identical KQL...
