### ISSUE TITLE
Can we replace custom webpart of an on-prem page with a custom modern webpart, while transforming that page ???

### ISSUE THREAD

**Issue by AAnkitaAswal** [SharePoint/sp-dev-modernization#255]
we need to add our custom webpart to a on-prem page when we are transforming it to a modern site.

**Comment by jansenbe** [comment]
Hey @AAnkitaAswal,

Just to understand things: you want to transform an on-premises page to a modern site in SPO or a modern site in SP2019 on-premises? We only support transforming into modern sites in SPO.

Also are you talking about publishing pages or wiki/webpart pages?

If you've built a modern equivalent for your custom classic web part you can add a mapping for that web part to the webpartmapping.xml file you're using. Below snippet shows a sample of a custom web part in the webpartmapping file:

```xml
<WebPart Type="SharePointPnP.Modernization.PageAcceptanceBanner" CrossSiteTransformationSupported="true">
        <Properties>
          <Property Name="SourcePage" Type="string"/>
          <Property Name="TargetPage" Type="string"/>
        </Properties>
        <Mappings>
          <Mapping Default="true" Name="default">
            <ClientSideWebPart Type="Custom" ControlId="d462a7c4-b2e1-4e80-867a-7b46d279c161" Order="10" JsonControlData="&#123;&quot;serverProcessedContent&quot;:&#123;&quot;htmlStrings&quot;:&#123;&#125;,&quot;searchablePlainTexts&quot;:&#123;&#125;,&quot;imageSources&quot;:&#123;&#125;,&quot;links&quot;:&#123;&#125;&#125;,&quot;dataVersion&quot;:&quot;1.0&quot;,&quot;properties&quot;:&#123;&quot;description&quot;:&quot;modernizationPageDemo&quot;,&quot;sourcePage&quot;:&quot;{SourcePage}&quot;,&quot;targetPage&quot;:&quot;{TargetPage}&quot;&#125;&#125;"/>
          </Mapping>
        </Mappings>
      </WebPart>
```

**Comment by AAnkitaAswal** [comment]
Hi Jasen,

we are trying to transform a publishing page to SPO site.

I will map my file according to the snippet you have provided.

Could you please share documentation with me if you have any handy with you.

Thanks a ton!!!!

**Comment by jansenbe** [comment]
Transforming on-premises publishing pages to SPO is supported. If your source is SP2013/2016 you might see an error in web part handling, but that will be fixed in the upcoming September release (will be released soon, latest on Monday September 9th).

When you transform publishing pages you typically create a page layout mapping file containing a mapping per page layout that you use in the source site. See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing to learn more about how to build and configure your page layout mapping files.

In your case you also want to transform a custom classic web part to an alternative modern custom web part, which implies that you need to update the default web part mapping file. See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model#webpart-definition-in-the-page-transformation-model to learn more about the webpartmapping.xml file. You can get the default mapping file via following PnP PS cmdlet:

```PowerShell
Connect-PnPOnline -Url https://yourtenant.sharepoint.com/sites/yoursite
Export-PnPClientSidePageMapping -BuiltInWebPartMapping -Folder c:\temp
```
Once you've updated the mapping file using the earlier specified guidance you need to pass it along in the ConvertTo-PnPClientSidePage cmdlet using the **-WebPartMappingFile** parameter.

**Comment by AAnkitaAswal** [comment]
Hi Bert,

Could you please share some sample files for pagelayout.xml and webpart.xml file, wherein you have added a client custom webpart in the page through transformation script.

Regards,
Ankita Aswal

**Comment by jansenbe** [comment]
There already was an example in the previous replies (see below XML snippet). You'll have to update the type to the fully qualified name of your custom classic web part and update the properties to indicate which properties of your classic web part you need to capture as input for the transformation process. Then you also need to specify the ID of your modern SPFX based web part that will replace this custom classic web part as ControlID property + plug in the JSON properties structure your custom web part needs. The best way to get the JSON is to configure your custom web part in the modern workbench and then copy the JSON and if needed tweak it with parameters (like {SourcePage} in my example, parameters must be defined as web part properties before they can be used).

```xml
<WebPart Type="SharePointPnP.Modernization.PageAcceptanceBanner" CrossSiteTransformationSupported="true">
        <Properties>
          <Property Name="SourcePage" Type="string"/>
          <Property Name="TargetPage" Type="string"/>
        </Properties>
        <Mappings>
          <Mapping Default="true" Name="default">
            <ClientSideWebPart Type="Custom" ControlId="d462a7c4-b2e1-4e80-867a-7b46d279c161" Order="10" JsonControlData="&#123;&quot;serverProcessedContent&quot;:&#123;&quot;htmlStrings&quot;:&#123;&#125;,&quot;searchablePlainTexts&quot;:&#123;&#125;,&quot;imageSources&quot;:&#123;&#125;,&quot;links&quot;:&#123;&#125;&#125;,&quot;dataVersion&quot;:&quot;1.0&quot;,&quot;properties&quot;:&#123;&quot;description&quot;:&quot;modernizationPageDemo&quot;,&quot;sourcePage&quot;:&quot;{SourcePage}&quot;,&quot;targetPage&quot;:&quot;{TargetPage}&quot;&#125;&#125;"/>
          </Mapping>
        </Mappings>
      </WebPart>
```

If you then have your custom web part on a page it will be detected and transformed. Would also recommend enabling logging, so you can see what's going during transformation.

**Comment by AAnkitaAswal** [comment]
Hi Bert,

In case we do not want to replace a classic webpart, instead want to add client side webpart to our page at the time of transformation. Is it also possible?


Regards,
Ankita Aswal

**Comment by jansenbe** [comment]
Yes you can do that.

Step1: You still need to define your modern web part as a mapping in the webpartmapping file like shown in the previously shared XML. Only for the type you can then pick an imaginary web part name (e.g. Contoso.CustomWebParts.WebPart1). It's still important you specify the properties of your new web part that you want to possibly update (e.g. SourcePage and TargetPage in my example).

Once you've that in the webpartmapping.xml you can add a web part in the mapping file like shown below:

```XML
...
<WebParts>
...
        <Field Name="PublishingPageImage" TargetWebPart="Contoso.CustomWebParts.WebPart1" Row="2" Column="2" Order="1">
          <Property Name="Property1" Type="string" Functions="StaticString('some hard coded input')"/>
          <Property Name="Property2" Type="string" Functions="StaticString({APageMetadataField})"/>
        </Field>
...
</WebParts>
...
```

During runtime this will trigger the placement of the modern version of "Contoso.CustomWebParts.WebPart1" to be placed in row 2, column 2. 

If you've no need for custom properties you can leave them out from the both the webpartmapping as the page layout file...but these properties allow you to use information from the source page to configure the modern web part on the target page.

I've not tried this myself yet, but at least in my mind this works ;-)

**Comment by AAnkitaAswal** [comment]
Hi Bert,

Thank you.

But still I am getting this issue:


PS C:\QianetMig> C:\QianetMig\ConvertPage.ps1
ConvertTo-PnPClientSidePage : The given key was not present in the dictionary.
At C:\QianetMig\ConvertPage.ps1:19 char:1
+ ConvertTo-PnPClientSidePage -Identity "Ankita13.aspx" -PublishingPage ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], KeyNotFoundException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage


Regards,
Ankita Aswal

**Comment by jansenbe** [comment]
can you share the web part mapping xml and page layout mapping xml files that you're using?

**Comment by AAnkitaAswal** [comment]
Hi Bert,

Please find attached.

Regards,
Ankita Aswal

**Comment by jansenbe** [comment]
Hi @AAnkitaAswal ,

Attaching files via GitHub email does not work. Please use the GitHub page (https://github.com/SharePoint/sp-dev-modernization/issues/255) to add these files

**Comment by AAnkitaAswal** [comment]
Pagelayout File
#################################################

<?xml version="1.0" encoding="utf-8"?>
<PublishingPageTransformation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.dev.office.com/PnP/2019/03/PublishingPageTransformationSchema" Version="1.0.1907.0">
  <PageLayouts>
   
    
    <PageLayout Name="BlankWebPartPage" AssociatedContentType="Pages" PageLayoutTemplate="AutoDetect" PageHeader="Custom">
      <Header Type="FullWidthImage" Alignment="Left" ShowPublishedDate="false">
        <Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="ToImageUrl({PublishingRollupImage})" />
        <Field Name="ArticleByLine" HeaderProperty="TopicHeader" Functions="" />
        <Field Name="PublishingContact" HeaderProperty="Authors" Functions="ToAuthors({PublishingContact})" />
      </Header>
      <MetaData>
        <Field Name="Title" TargetFieldName="" Functions="" />
        <Field Name="Comments" TargetFieldName="" Functions="" />
        <Field Name="PublishingStartDate" TargetFieldName="" Functions="" />
        <Field Name="PublishingExpirationDate" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactEmail" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactName" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactPicture" TargetFieldName="" Functions="" />
        <Field Name="PublishingIsFurlPage" TargetFieldName="" Functions="" />
      </MetaData>
      <WebParts>

<Field Name="HelloWebPart" TargetWebPart="customwebpart" Row="2" Column="2" Order="1">
 <Property Name="SourcePage" Type="string"/>
          <Property Name="TargetPage" Type="string"/>
		   </Field>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="1">
          <Property Name="Text" Type="string" />
        </Field>
      </WebParts>
      <WebPartZones>
        <WebPartZone ZoneIndex="0" ZoneId="Header" Row="2" Column="1" />        
      </WebPartZones>
	   <FixedWebParts>
	   <WebPart Type="Microsoft.SharePoint.WebPartPages.ContentEditorWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c"  Row="1" Column="1"> 
	   <Property Name="Title" Type="string" Value="exapmle"/>
	  
		 <Property Name="Content" Type="string" Value="exapmle"/>
	     <Property Name="ExportMode" Type="string" Value="All" />
	  </WebPart>
	    <WebPart Type="Microsoft.SharePoint.WebPartPages.ContentEditorWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c"  Row="1" Column="1"> 
	   <Property Name="Title" Type="string" Value="exapmle"/>
	  
		 <Property Name="Content" Type="string" Value="exapmle"/>
	     <Property Name="ExportMode" Type="string" Value="All" />
	  </WebPart>
	   </FixedWebParts>
    </PageLayout>
    
    
  </PageLayouts>
</PublishingPageTransformation>
##########################################################

Webpart.xml
################################################################


<PageTransformation xmlns="http://schemas.dev.office.com/PnP/2018/01/PageTransformationSchema" Version="1.0.1907.0">
    
    <BaseWebPart>
      <Properties>
        <Property Name="Title" Type="string" Functions=""/>
        <Property Name="Description" Type="string" Functions=""/>
        <Property Name="Width" Type="string" Functions=""/>
        <Property Name="Height" Type="string" />
      </Properties>
      <Mappings>
        
        <Mapping Name="default" Default="true">
          <ClientSideText Text="***Web part {Title} was not transformed***" Order="10" />
        </Mapping>
      </Mappings>
    </BaseWebPart>
    
    <AddOns>
      
      
    </AddOns>
     
    <WebParts>
    <WebPart Type="SharePointPnP.Modernization.PageAcceptanceBanner" CrossSiteTransformationSupported="true">
        <Properties>
      <Property Name="SourcePage" Type="string"/>
          <Property Name="TargetPage" Type="string"/>
        </Properties>
        <Mappings>
          <Mapping Default="true" Name="default">
            <ClientSideWebPart Type="Custom" ControlId="3193a2ff-de9c-4497-8c96-a3e4510fdf7a" Order="10" JsonControlData="&#123;&quot;serverProcessedContent&quot;:&#123;&quot;htmlStrings&quot;:&#123;&#125;,&quot;searchablePlainTexts&quot;:&#123;&#125;,&quot;imageSources&quot;:&#123;&#125;,&quot;links&quot;:&#123;&#125;&#125;,&quot;dataVersion&quot;:&quot;1.0&quot;,&quot;properties&quot;:&#123;&quot;description&quot;:&quot;modernizationPageDemo&quot;,&quot;sourcePage&quot;:&quot;{SourcePage}&quot;,&quot;targetPage&quot;:&quot;{TargetPage}&quot;&#125;&#125;"/>
          </Mapping>
        </Mappings>
      </WebPart>       
     
    </WebParts>
</PageTransformation> 

###############################################

**Comment by jansenbe** [comment]
hmm....above are incomplete snippets...send me the files at bjansen@microsoft.com

**Comment by AAnkitaAswal** [comment]
[pagelayoutmapping.txt](https://github.com/SharePoint/sp-dev-modernization/files/3599403/pagelayoutmapping.txt)
[webpartmapping.txt](https://github.com/SharePoint/sp-dev-modernization/files/3599405/webpartmapping.txt)

**Comment by jansenbe** [comment]
See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing#i-want-to-add-an-extra-web-part-on-the-created-page for the steps on how to realize this. Closing this issue now as we're also following up via email.

**Comment by SrihariKundargi** [comment]
Hi @jansenbe ,

Can you please update on this issue, if there is a solution for the question. Even I was trying to add a webpart during transformation. Have added all the required mappings in the webpartmapping.xml and pagelayoutmapping.xml files as suggested. The pages get transformed but without the custom clientsidewebpart. The logs say the "webpart was not found".

Thanks & Regards,
Srihari
