### ISSUE TITLE
Ability to specify a target folder on target site pages library

### ISSUE THREAD

**Issue by TuomasPakkanen** [SharePoint/sp-dev-modernization#260]
##Category

[ ] Bug
[X] Enhancement

**Comment by jansenbe** [comment]
That would indeed be a useful enhancement. Currently assigned to the October release

**Comment by pkbullock** [comment]
This one will be needed for the upcoming multilingual support in SPO (I think)

**Comment by jansenbe** [comment]
Hi @TuomasPakkanen, this will be available with the upcoming November release.
