### ISSUE TITLE
Page layout not mapped properly after page conversion to modern

### ISSUE THREAD

**Issue by PriyankaDevi510** [SharePoint/sp-dev-modernization#261]
#### Category

[*] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ *] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ *] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

After transformation to modern, Page is expected to have their webparts placed in the exact section as in the classic page

#### Observed Behavior

In classic page, webparts are aligned in both left and right column sections of the page. But after transformation to modern, All the webparts are lined down in a single section.  

But this issue is observed only in "default.aspx" page from the root folder

#### Steps to Reproduce
1.Choosing a site which has "default.aspx" in the root level
2. convert the page using  "ConvertTo-PnPClientSidePage -Identity "default.aspx" -Folder "<root>" -Overwrite -AddPageAcceptBanner "

**Comment by jansenbe** [comment]
This implies the logic we use to detect the layout of this wiki page (assume it is a wiki page?) does not find the right layout. This is possible if the wiki html has been manually "upgraded/updated"...if it's just one page I would manually fix the created target page.

If you can share the page wiki contents then I can try to repro this

**Comment by PriyankaDevi510** [comment]
Hi @jansenbe 

It is a webpart page and the page has webparts like  Content Editor WebPart, Xslt List View WebPart. As this default.aspx page is the landing page in almost all the site collections and sub sites, Manually fixing this seems to be much time consuming

**Comment by jansenbe** [comment]
ok, so it's a web part page. For web part pages we detect the layout based upon the value of the vti_setuppath property of the page (see https://github.com/SharePoint/sp-dev-modernization/blob/dev/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Pages/WebPartPage.cs#L470). **Can you check this property for your home page?** An easy way to do this without coding is using the SharePoint Client Browser (see https://github.com/bramdejager/spcb).

**Comment by PriyankaDevi510** [comment]
Hi @jansenbe ,
The  vti_setuppath property is found to be "SiteTemplates\STS\default.aspx"
Found using SP client browser

**Comment by jansenbe** [comment]
Can you share a screenshot? (or alternatively sent directly to me via bjansen@microsoft.com)

**Comment by jansenbe** [comment]
Were these sites at a certain point migrated from on-premises?

**Comment by PriyankaDevi510** [comment]
Yes, They were migrated from on-prem

**Comment by jansenbe** [comment]
Seems they originally came from SP2010. I've found the template in my lab, will make some changes to handle this scenario for the upcoming September release

**Comment by jansenbe** [comment]
Are the 2 columns each of the same size?

**Comment by PriyankaDevi510** [comment]
No. They seems to be on one-third right layout.

**Comment by jansenbe** [comment]
so, the biggest section is right?

**Comment by jansenbe** [comment]
Sorry, I see now...biggest is left (70%)

**Comment by PriyankaDevi510** [comment]
Yes. It is left:right :: 3:1

**Comment by jansenbe** [comment]
Fix has been committed and will be in the September version which will be released next week Monday. Please retest with the September release and let us know if that fixes things for you. 

Also thanks for reporting the issue, this helps making transformation better :-)

**Comment by jansenbe** [comment]
September release is available for testing

**Comment by jansenbe** [comment]
Hey @PriyankaDevi510 ,

Can you test if the web part pages are now converted using the correct layout?

**Comment by PriyankaDevi510** [comment]
Hey @jansenbe 

The webparts are not converting to the correct layout. Thanks much for the quick turn around

**Comment by jansenbe** [comment]
I assume **not** is **now** in above text?
