### ISSUE TITLE
Returned modern page url is containing /pages/ when transforming from on-premises SharePoint

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#262]
Page transformation gives back the URL of the created page, for on-premises publishing page transformation this is not handled correctly.

**Comment by jansenbe** [comment]
Also assigning you here @pkbullock , I've seen this during a quick screen share session with a customer....Maybe it was fixed in the latest release, but need to cross check. Maybe you've seen this as well?

**Comment by pkbullock** [comment]
@jansenbe i will cross check, after this weekend if that's ok working mega hours for client engagement. If i get a window ill check for you 😊

**Comment by jansenbe** [comment]
@pkbullock , that's fine. No rush as this is not a critical thing. If I happen to have before I'll test as well and update here.

**Comment by pkbullock** [comment]
@jansenbe just thinking about this,  i have seen an issue previously where if a closed web part is on the page, then no URL is returned. But this should be fixed in latest release. 

On a side note, whilst fixing the root cause might be the answer in the above, there maybe a  flaw in the feedback to PowerShell when a critical error occurs. In the above case, no URL is returned. If you don't proactively use the logs or have them on, you wouldn't know easily that a critical error occurred. 

Will report back shortly....

**Comment by pkbullock** [comment]
@jansenbe Yeap there is a bug, in a positive transform result, the URL is wrong:

```
/sites/pnpkatchup/sitepages/**pages**/article-sp2013-test.aspx
```
The files do not reside in a sub-folder called pages. I will email the transform file to you.

**Comment by pkbullock** [comment]
@jansenbe just realised not using the latest version of PnP, have a dev copy running, will confirm and get coffee.

**Comment by pkbullock** [comment]
@jansenbe confirmed this is still an issue, also the issue is shown in the MD report and the PS output. Ignore the error, my script doesn't filter transforming folders lol.

```powershell
Converting site...
 Processing TestSP2013Folder
 Modernizing TestSP2013Folder...
ConvertTo-PnPClientSidePage : Object reference not set to an instance of an object.
At C:\git\tfs\Intranet-Provision\transform\Publishing-Pages\Convert-OnPremPublishingPages.ps1:142 char:19
+ ...   $result = ConvertTo-PnPClientSidePage -Identity $page.FieldValues[" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage

Transformed URL:
Page not transformed, check the logs for issues
 Modernized TestSP2013Folder!
 Processing PageNotFoundError.aspx
 Modernizing PageNotFoundError.aspx...
Transformed URL: /sites/pnpkatchup/sitepages/pages/pagenotfounderror.aspx
 Modernized PageNotFoundError.aspx!
 Processing default.aspx
Skipping default.aspx
 Processing Article-SP2013-Test.aspx
 Modernizing Article-SP2013-Test.aspx...
Transformed URL: /sites/pnpkatchup/sitepages/pages/article-sp2013-test.aspx
 Modernized Article-SP2013-Test.aspx!
 Processing Article-with-richer-data.aspx
 Modernizing Article-with-richer-data.aspx...
Transformed URL: /sites/pnpkatchup/sitepages/pages/article-with-richer-data.aspx
 Modernized Article-with-richer-data.aspx!
 Processing Article-SP2013-Test2.aspx
 Modernizing Article-SP2013-Test2.aspx...
Transformed URL: /sites/pnpkatchup/sitepages/pages/article-sp2013-test2.aspx
 Modernized Article-SP2013-Test2.aspx!
 Processing Article-SP2013-Custom.aspx
 Modernizing Article-SP2013-Custom.aspx...
Transformed URL: /sites/pnpkatchup/sitepages/pages/article-sp2013-custom.aspx
 Modernized Article-SP2013-Custom.aspx!
 Processing Article-SP2013-InFolderTest.aspx
 Modernizing Article-SP2013-InFolderTest.aspx...
Transformed URL: /sites/pnpkatchup/sitepages/pages/testsp2013folder/article-sp2013-infoldertest.aspx
 Modernized Article-SP2013-InFolderTest.aspx!
 Processing Common-PubPageWithWebPart.aspx
 Modernizing Common-PubPageWithWebPart.aspx...
Transformed URL: /sites/pnpkatchup/sitepages/pages/common-pubpagewithwebpart.aspx
 Modernized Common-PubPageWithWebPart.aspx!
Report saved as: c:\temp\Page-Transformation-Report-11-09-2019-07-32-06.md
```
[Page-Transformation-Report-11-09-2019-07-32-06 - Copy.txt](https://github.com/SharePoint/sp-dev-modernization/files/3599332/Page-Transformation-Report-11-09-2019-07-32-06.-.Copy.txt)
![Annotation 2019-09-11 073708](https://user-images.githubusercontent.com/8781041/64673865-3b1d3280-d467-11e9-87a8-5a6e51cd0d84.png)

**Comment by jansenbe** [comment]
Thanks for testing and confirming the issue @pkbullock .

**Comment by jansenbe** [comment]
I'm not able to simulate this issue with pages living in a regular site collection, might be related to transforming from the root site collection. Will do some more testing

**Comment by jansenbe** [comment]
Yep, related to handling publishing pages in a root site collection. Fixed now.
