### ISSUE TITLE
Export-PnPClientSidePageMapping returning a blank pagelayout mapping file

### ISSUE THREAD

**Issue by KVSolutions** [SharePoint/sp-dev-modernization#268]
### Reporting an Issue 
Export-PnPClientSidepageMapping is returning a blank mapping file for the custom page layout

### Expected behavior 
Create a mapping file which has header,webpartzones and any fixed webparts

### Actual behavior 
Currently its generating a xml file as below
<?xml version="1.0" encoding="utf-8"?>
<PublishingPageTransformation xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.dev.office.com/PnP/2019/03/PublishingPageTransformationSchema" />

### Steps to reproduce behavior
Run the cmdlet on a SP2013 site (migrated from SP2010)

### Which version of the PnP-PowerShell Cmdlets are you using?
- [ ] PnP PowerShell for SharePoint 2013
- [ ] PnP PowerShell for SharePoint 2016
- [ X] PnP PowerShell for SharePoint Online - 3.13.1909.0

### What is the version of the Cmdlet module you are running?
3.13.1909.0

### How did you install the PnP-PowerShell Cmdlets? 
- [ ] MSI Installed downloaded from GitHub
- [X ] Installed through the PowerShell Gallery with Install-Module
- [ ] Other means

**Comment by jansenbe** [comment]
Hi @KVSolutions ,

Did manage to repro this, will fix this bug for the next release (October drop)

**Comment by jansenbe** [comment]
Actually, doing some more testing this just seems to work. Did you specify the -CustomPageLayoutMapping parameter?

This works on my SP2103 test lab and generates a mapping file for my custom page layout:

```PowerShell
Export-PnPClientSidePageMapping -CustomPageLayoutMapping  -Overwrite -Folder c:\temp
```

Can you cross check this in your environment? If you're not seeing your custom page layout then please check if that one was properly published and that it has a title set

**Comment by KVSolutions** [comment]
HI @jansenbe ,
I did specify the parameter(CustomPageLayoutMapping) ,However its generating the xml file with just xml root element.
I have tried this with multiple pages in order to generate the page layout and seeing the same file and the pages is published,there is no checkouts pending on these pages.
Thats a great news ,as you managed to reproduce this.

**Comment by jansenbe** [comment]
Hi @KVSolutions ,

I thought I was reproducing...but then I realized I was not using a custom page layout in my site collection. Once I've setup a custom pagelayout things worked for me. The one thing I can think off is that somehow your page layout is not returned when we do the CAML query to the master page gallery. Can you take a screenshot of the properties screen of one your custom page layouts and share that?

**Comment by KVSolutions** [comment]
Hi @jansenbe 

Here is the screenshot of properties

![image](https://user-images.githubusercontent.com/40911501/65212438-78c43000-dae5-11e9-98a7-b7a93f6acb34.png)

This content type has inheritance of 4 more levels from root content type "Page" of SharePoint

**Comment by jansenbe** [comment]
Hi @KVSolutions ,

Would it be possible to evaluate the page layout properties against below query (which is the one we're using to find all page layouts to be analyzed):

```csharp
            var query = new CamlQuery
            {
                // Use query Scope='RecursiveAll' to iterate through sub folders of Master page library because we might have file in folder hierarchy
                // Ensure that we are getting layouts with at least one published version, not hidden layouts
                ViewXml =
                $"<View Scope='RecursiveAll'>" +
                    $"<Query>" +
                        $"<Where>" +
                            $"<And>" +
                                $"<Contains>" +
                                    $"<FieldRef Name='File_x0020_Type'/><Value Type='Text'>aspx</Value>" +
                                $"</Contains>" +
                                $"<And>" +
                                    $"<And>" +
                                        $"<Geq>" +
                                            $"<FieldRef Name='_UIVersionString'/><Value Type='Text'>1.0</Value>" +
                                        $"</Geq>" +
                                        $"<BeginsWith>" +
                                            $"<FieldRef Name='ContentTypeId'/><Value Type='ContentTypeId'>{Constants.PageLayoutBaseContentTypeId}</Value>" +
                                        $"</BeginsWith>" +
                                    $"</And>" +
                                    $"<Or>" +
                                        $"<Eq>" +
                                            $"<FieldRef Name='PublishingHidden'/><Value Type='Boolean'>0</Value>" +
                                        $"</Eq>" +
                                        $"<IsNull>" +
                                            $"<FieldRef Name='PublishingHidden'/>" +
                                        $"</IsNull>" +
                                    $"</Or>" +
                                $"</And>" +
                            $"</And>" +
                         $"</Where>" +
                    $"</Query>" +
                    $"<ViewFields>" +
                        $"<FieldRef Name='{Constants.PublishingAssociatedContentTypeField}' />" +
                        $"<FieldRef Name='PublishingHidden' />" +
                        $"<FieldRef Name='Title' />" +
                    $"</ViewFields>" +
                  $"</View>"
            };
```

Also if your page layout is named like a "out of the box one" it's skipped by default. Below snippet shows the out of the box page layout names:

```csharp
public static string[] OobPublishingPageLayouts = new string[] { "ArticleLeft", "ArticleLinks", "ArticleRight", "BlankWebPartPage", "ProjectPage", "WelcomeLinks",
                                                                         "PageFromDocLayout", "WelcomeSplash", "ErrorLayout", "EnterpriseWiki", "CatalogArticle", "CatalogWelcome",
                                                                         "PageLayoutTemplate", "RedirectPageLayout", "VariationRootPageLayout" };
```

If that's the case then please try with the following PowerShell:

```Powershell
Export-PnPClientSidePageMapping -CustomPageLayoutMapping  -Overwrite -Folder c:\temp - AnalyzeOOBPageLayouts
```

Also adding @pkbullock  for awareness.

**Comment by pkbullock** [comment]
Hi @jansenbe 

Looking at the CAML, it might be flawed at this point :
```
"<Geq>"
    $"<FieldRef Name='_UIVersionString'/><Value Type='Text'>1.0</Value>" 
"</Geq>"
```
I am doing a text greater than, i should have used numbers. 
I ran came command on 2010/2013, UI still looks like 2010 works fine in both cases. However, that cmdlet doesn't produce any error if there was one.  There maybe a problem with page itself, a scenario the analyser doesn't handle well.

@KVSolutions is it possible to download the page and post here or email?

**Comment by pkbullock** [comment]
All in case we don't catch this in time for the next release - I have added #286 and written extra logging points to help move this one forward.

**Comment by KVSolutions** [comment]
Hi @jansenbe 
This worked as expected now post october release.
