### ISSUE TITLE
Error: Tenant xxx.com is not whitelisted for this transformation service endpoint

### ISSUE THREAD

**Issue by redepandence** [SharePoint/sp-dev-modernization#27]
I am trying to convert a classic page to modern page by using the ribbon button on the page library, after clicking the button, it redirected to the modernization center page and after awhile there are error message in the page as below :

Busy generating a modern version of Home.aspx...
Error: Tenant xxx.com is not whitelisted for this transformation service endpoint.
![1-17-2019 2-09-24 pm](https://user-images.githubusercontent.com/12904318/51299178-67141f80-1a62-11e9-8e90-0266a91910dc.jpg)

where I can setup the whitelist ? how to resolve this ? thanks !

**Comment by redepandence** [comment]
Hi guys, 

the issue resolved , it is because  'AllowedTenants' in the Provision-ModernizationFramework.ps1 used the wrong parameter.

another question:

When I setting the appsetting according to the script , the below two properties will return "Bad Request" 
WEBSITE_CONTENTSHARE
WEBSITE_CONTENTAZUREFILECONNECTIONSTRING

I try to set these properties at AAD application, the error is same

**Comment by redepandence** [comment]
Hi @jansenbe 

Thanks for you quick response, your answer is very helpful.

"setting WEBSITE_CONTENTSHARE and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING, did you get a failure while running the Provision-ModernizationFramework.ps1 script?"  
The answer is yes, the script is trying to set these two properties, however the API Set-AzureRmWebApp will return "Bad Request" if the appsettings contain these two properties, I also trying to set these two properties at Azure function host app in Azure instead of by script but get the same result, I am not sure what will effect on if I cannot set it and if it effect nothing then I will ignore these two properties. 

BR, 
Thanks!

**Comment by jansenbe** [comment]
I'll test the script again and see if these 2 settings can be dropped. Beta will be available by end of next week.

**Comment by jansenbe** [comment]
but you got it to work eventually?

**Comment by jansenbe** [comment]
Perfect. I've created #28 and will test this before the beta release. Since the tool works for you I'll now close this issue. Thanks for the testing and feedback, really appreciated!

**Comment by jansenbe** [comment]
About the webpartmapping.xml file: the ones that don't have a mapping today don't have an equivalent 1st party modern webpart. Our telemetry has shown that 90%+ of the pages can be modernized using the current mapping. If you need content or script editor you can adjust your mapping as explained in issue #26.

**Comment by jansenbe** [comment]
Hi @redepandence,

I do have one question: do you have your Azure Function app on a consumption plan or a standard plan? The 2 settings that gave an error can only be used on a consumption plan.

**Comment by jansenbe** [comment]
Hi @redepandence ,

There was one more reason for this issue: if you've used a character that's forbidden in a storage account name inside the function app name (e.g. uppercase character) then the WEBSITE_CONTENTSHARE property got populated with an invalid value. This will be fixed in the provisioning script but thought it would be interesting for you to know as well.
