### ISSUE TITLE
Implement native "keep source page author/editor/created/modified properties" solution that works for all cross page transformations

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#270]

**Comment by pkbullock** [comment]
Interest in the answer for this, i heavily tried to achieve this but could get past when you publish a page in code, the modified properties reflected who published but I'm sure migration tools get round this.

**Comment by jansenbe** [comment]
Almost done with this one :-) Also will include a "postasnews" option + have done some work to lower the amount of intermediate page versions we create

**Comment by pkbullock** [comment]
Cool, I do btw read your commits its a great way to learn... 😊😁

**Comment by jansenbe** [comment]
@pkbullock : just checked in. Will still have to add to PnP PS, but you can play around with the KeepPageCreationModificationInformation and PostAsNews options
