### ISSUE TITLE
Logging shows class name instead of data

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#273]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Report should show timing information

#### Observed Behavior

In ticket #267 the markdown report contains a class name not timing information:

e,g, 

**Transform duration: SharePointPnP.Modernization.Framework.Entities.TransformationLogAnalysis**

#### Steps to Reproduce

Transform something with logging enabled for Markdown

**Comment by jansenbe** [comment]
Nice catch @pkbullock , will fix this

**Comment by jansenbe** [comment]
And fixed
