### ISSUE TITLE
Does not work with Modern Authentication

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-modernization#282]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[X] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Connection to AzureAD needs to use modern auth

#### Observed Behavior

Connection is using legacy methods which fail when you have Azure AD CA applied - which everyone should have:

# Connect to Azure AD
$credential = Get-Credential
Connect-AzureAd -Credential $credential

#### Steps to Reproduce

Run the Provision-ModernizationFramework.ps1

Connect-AzureAd : One or more errors occurred.: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access

**Comment by jansenbe** [comment]
Just merged your PR for this, so we can close this. 

Do note that we've not been very active in pushing out new page transformation UI releases...the PowerShell or .Net code based approaches have however received a ton of updates. Unless there's a real demand for end-user driven transformation I would recommend using an IT team driven approach using PowerShell.
