### ISSUE TITLE
Update to use new Az module

### ISSUE THREAD

**Issue by danmyhre** [SharePoint/sp-dev-modernization#283]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[X] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
Use current PowerShell modules

#### Observed Behavior
Using AzureRM module

#### Steps to Reproduce
Provision-ModernizationFramework.ps1

**Comment by jansenbe** [comment]
Hi @danmyhre ,

As mentioned in your previous issue (which was fixed by your PR) the UI component is currently not receiving much focus as we'll first want the provisioning engine component to be covering all scenarios. I'll leave this issue in, but will tag it as a future idea.

**Comment by jansenbe** [comment]
Given the UI component anyhow does not work in your scenario and that we're not actively planning any work on it I'm gonna close this one. Hope you don't mind @danmyhre .

**Comment by danmyhre** [comment]
Yep, no worries!
