### ISSUE TITLE
Markdown Reporting Enhancements

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#285]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[X] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Improvements to Markdown reports to include:

- Fixes to transformation settings - expand on all settings (support beyond basic settings)
- SharePoint Version
- List of web parts that are detected by source scan
- Indications of Web Services Usage
- Program Transformation Mode - Wiki, Web Part Page or Publishing Page

**Comment by pkbullock** [comment]
@jansenbe if there is anything you want to add on a diagnostics side, perhaps to the verbose modes, please add here.

**Comment by jansenbe** [comment]
Good ideas @pkbullock, having more log details will help customers (and us) with debugging. Your list is a good start, one small thing to add is "Blog Page" in transformation mode.

**Comment by jansenbe** [comment]
Thanks for your PR @pkbullock , I've just tested and merged it. Closing this issue.
