### ISSUE TITLE
Export-ClientSidePageMapping Logging

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#286]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Logging option for ExportClientSidePageMapping cmdlet, we sometimes get errors and there are already some basic error handling involved.

Related to #285 where extra information capture should be included in this as well.

Recommend the Console Observer for this.

**Comment by jansenbe** [comment]
Something we indeed need @pkbullock. I'll merge your PR for this and I'll add some PS support as well (similar to what we have for the `ConvertTo-PnPClientSidePage` cmdlet.

**Comment by jansenbe** [comment]
Both are merged, closing this issue
