### ISSUE TITLE
Asset transfer from images living in a sub site of a publishing portal in the root are not copied over

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#298]
Issue most likely is within EnsureAssetContextIfRequired

**Comment by jansenbe** [comment]
@pkbullock : is this something you can have a look at? I'm aiming to get this fixed before the October drop as it's prevents image transfer from sub sites of a root site collection

**Comment by pkbullock** [comment]
I shall investigate and report back.

**Comment by pkbullock** [comment]
@jansenbe struggling to repro this, tried with SharePoint 2016, with the following:

- Subsite in Publishing Portal - Page and Image in subsite
- Main site with page, Sub-Site with Image

Both transformed OK. Do you have more info on the scenario? My tests might be wrong.

**Comment by jansenbe** [comment]
I can repro this in my 2013 lab, key here is that it's for a page in a sub site of the **root** site collection pointing to an image that lives in the root site collection. Sub sites in other site collections work fine. Things fail because when we create the context to load the asset it's returning the context for the sub site and not for the root site hosting the asset.

**Comment by jansenbe** [comment]
Thx for the fix @pkbullock , just merged so closing the issue
