### ISSUE TITLE
Build richer examples for docs site

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#302]
Like the other PnP programs, build a MKDocs style site. I use this myself in my work, after looking at how Elio did it for the web part controls.

I'm thinking Keep the higher level strategy, overview stuff on the MS docs site and the deep technical references move over the MK Docs.
e.g.

- Mapping file examples
- Example before and afters screenshots
- Ability to combine PRs in this repo to include documentation elements with enhancements (those areas where auto generated docs aren't a factor)
- Excuse for general improvements
- Move any MD files in the repos solutions to the site

**Comment by pkbullock** [comment]
I've seen a logo for PnP Core Modernizer in the pnp library that might be suitable for this 😊 - https://github.com/pnp/media/blob/master/pnp-logos/github-social/pnp-core-modernisation.png

**Comment by pkbullock** [comment]
Updated based on call.

**Comment by jansenbe** [comment]
Guess we can close this one: docs will all be on docs.microsoft.com and samples will be in the scripts folder of this repo.
