### ISSUE TITLE
Failed to modernize page, Index out of range error

### ISSUE THREAD

**Issue by GamalMohamed** [SharePoint/sp-dev-modernization#304]
#### Category

[ ] Bug

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell

#### Expected or Desired Behavior
The page should be transformed to modern normally.

#### Observed Behavior
Transformation failed and Index out of range exception is thrown

#### Steps to Reproduce

**I'm using PnP version 3.13.19 and running the sample powershell script of pages transformation and just changing the site URL and it throws the below error on the attached homepage:**

```
ConvertTo-PnPClientSidePage : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
At C:\Users\gmohamed\source\repos\SharePointOnline-Migration-Tool\PowerShell
Scripts\ModernizationScripts\ModernizingPages.ps1:27 char:27
+ ... odernPage = ConvertTo-PnPClientSidePage -Identity $page.FieldValues[" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage
```

**Get-PnPException output:**

```
Message          : Index was out of range. Must be non-negative and less than the size of the collection.
                   Parameter name: index
Stacktrace       :    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument,
                   ExceptionResource resource)
                      at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.LastColumnOrder(Int32
                   row, Int32 col)
                      at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1
                   webParts)
                      at SharePointPnP.Modernization.Framework.Transform.PageTransformator.Transform(PageTransformation
                   Information pageTransformationInformation)
                      at SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 27
```

![Page](https://user-images.githubusercontent.com/14844937/65873671-045e7c00-e384-11e9-8111-d28b89844246.PNG)

**Comment by jansenbe** [comment]
Hi @GamalMohamed ,

I assume that you're transforming from SP2013 on-premises to online?
Does this happen to all your home pages or just this one?
Can you run with logging enabled and share the log (add `-LogType File -LogVerbose -LogFolder "c:\temp"`)?

**Comment by GamalMohamed** [comment]
@jansenbe 
Yes, I'm migrating classic pages from SP2013 to SPOnline, then running the modernization scripts to transform them to modern on SPOnline.

> Does this happen to all your home pages or just this one?
No, this page only.

> Can you run with logging enabled and share the log (add -LogType File -LogVerbose -LogFolder "c:\temp")?
Yes, u can find attached below the log file.

[Page-Transformation-Report-9-30-2019-1-54-50-PM.txt](https://github.com/SharePoint/sp-dev-modernization/files/3670932/Page-Transformation-Report-9-30-2019-1-54-50-PM.txt)

**Comment by jansenbe** [comment]
Thanks for the log and details @GamalMohamed .

I do have some more questions:

- How do you migrate the pages from SP2013 to SPOnline? Using SPMT?
- Can you share the wiki content of the failing page with me:

```PowerShell
# Check the id of your home.aspx page
$p = Get-PnPListItem -List sitepages -Id 1
# copy contents into clipboard
$p.FieldValues["WikiField"] | clip
```

- Can you try to directly modernize the page from your SP2013 on-premises environment?

```PowerShell
# Target Tenant Connection - must be SPO and modern site
$target = Connect-PnPOnline https://tenant.sharepoint.com/sites/ModernizationTarget -Credentials bertonline -ReturnConnection

# Source Connection
Connect-PnPOnline https://portal2013.pnp.com/sites/devportal -CurrentCredentials

# Must have SkipItemLevelPermissionCopyToClientSidePage as two environments may not have knowledge of each others users.
ConvertTo-PnPClientSidePage -Identity "home.aspx" -TargetConnection $target -SkipItemLevelPermissionCopyToClientSidePage -LogVerbose -LogType File -LogFolder c:\temp
```

**Comment by jansenbe** [comment]
Hi @GamalMohamed ,

Can you provide answers to the questions? Did you test with the latest release 3.14.1910?

**Comment by GamalMohamed** [comment]
Hi @jansenbe 
Sorry for the late reply, I got busy throughout the last couple of days in work.

> How do you migrate the pages from SP2013 to SPOnline? Using SPMT?
Yes, I'm using MS SPMT

> Can you share the wiki content of the failing page with me
Yes sure, u can find it attached below
[WikiContent.txt](https://github.com/SharePoint/sp-dev-modernization/files/3712663/WikiContent.txt)

> Can you try to directly modernize the page from your SP2013 on-premises environment?
Unfortunately, I don't have access to SP2013 on-premises environment now, I will try this later.

> Did you test with the latest release 3.14.1910?
Yes, I just tested it on the same page and it gave me the same error

**Comment by GamalMohamed** [comment]
Hey @jansenbe 

> Can you try to directly modernize the page from your SP2013 on-premises environment?
I got access now to the On-premises environment, and ran the script. Attached below the log.

[Page-Transformation-Report-10-10-2019-4-02-40-PM.txt](https://github.com/SharePoint/sp-dev-modernization/files/3713011/Page-Transformation-Report-10-10-2019-4-02-40-PM.txt)

**Comment by jansenbe** [comment]
Hi @GamalMohamed ,

I've pasted the wiki page you shared in a new page and transformation works...although the outcome is not looking great. That page is an old 2010 page which heavily relies on nested tables for layouting. Since nested tables are not supported in modern SharePoint pages the resulting page is not looking pretty...but the content is there and it could be manually updated.

**Comment by jansenbe** [comment]
@GamalMohamed ,

The fixes we did apply to web part pages and publishing pages...but not to wiki pages when transforming from on-premises (2010/2013/2016) to online. I'll do the needed changes to enable that scenario.

**Comment by GamalMohamed** [comment]
@jansenbe 

When I run the following script:
`Get-Module SharePointPnPPowerShellOnline -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending`

It gives me the below result:
`Name                          Version
----                          -------
SharePointPnPPowerShellOnline 3.14.1910.0
SharePointPnPPowerShellOnline 3.13.1909.0
SharePointPnPPowerShellOnline 3.12.1908.1`

So, I think I'm using the latest version.


I ran the script again and here's it report:
[Page-Transformation-Report-10-10-2019-7-20-25-PM.txt](https://github.com/SharePoint/sp-dev-modernization/files/3713805/Page-Transformation-Report-10-10-2019-7-20-25-PM.txt)

**Comment by jansenbe** [comment]
@GamalMohamed 

You're right, there was a bug in wiki to SPO handling which I just fixed. But the fact that you got to the web part handling makes me think something did go wrong when using SPMT. I manually created a page based on the wiki html you shared, but could not repro the issue with that. I'll test with migrating an SP2013 team site to SPO via SPMT and then run page transformation on the migrated site in SPO.

Question: you only have the issue on the home page or also on other pages?

**Comment by GamalMohamed** [comment]
@jansenbe 

> you only have the issue on the home page or also on other pages?
No, it's on the homepage only.

> I'll test with migrating an SP2013 team site to SPO via SPMT and then run page transformation on the migrated site in SPO.
However, I previously tried to migrate SP2013 teamsite pages and it worked well. So, I don't think this will give u an error.

**Comment by GamalMohamed** [comment]
@jansenbe 

I do have another site homepage giving the same error:

`ConvertTo-PnPClientSidePage : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
At C:\Users\gmohamed\source\repos\SharePointOnline-Migration-Tool\PowerShell
Scripts\ModernizationScripts\SinglePage.ps1:8 char:1
+ ConvertTo-PnPClientSidePage -Identity "Previous_Home.aspx" -Overwrite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage`

and here's the PnPException:

`Message          : Index was out of range. Must be non-negative and less than the size of the collection.
                   Parameter name: index
Stacktrace       :    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument,
                   ExceptionResource resource)
                      at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.LastColumnOrder(Int32
                   row, Int32 col)
                      at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1
                   webParts)
                      at SharePointPnP.Modernization.Framework.Transform.PageTransformator.Transform(PageTransformation
                   Information pageTransformationInformation)
                      at SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()`

![h2](https://user-images.githubusercontent.com/14844937/66594852-2e8d1680-eb9a-11e9-9ac7-2dac5b5e6550.PNG)

**Comment by jansenbe** [comment]
Hey @GamalMohamed ,

I've tried to repro this, but so far without success. I've used SPMT to copy over a 2013 team site from on-premises 2013 to SPO and then modernized the pages in the created SPO site and that went fine. I'll do some more analysis with the wiki content you shared earlier, but would be good if you could also share the wiki content from the other page that's failing.

**Comment by jansenbe** [comment]
Found something in your wiki html: you're using `<td style="width&#58;66.6%;padding&#58;0px;">` to identify a column whereas the code we have expects `<td style="width&#58;66.6%;">` to correctly identify things. Will change our logic to handle your case as well.

**Comment by jansenbe** [comment]
Issue should be fixed with the above commit. The fix will be part of the November release (released between 2-4 November). I'll close this issue for now. Would recommend creating a new issue if the problem still is there with the November release.

**Comment by jansenbe** [comment]
FYI: Today we'll be releasing an intermediate October release which will contain this fix.
