### ISSUE TITLE
unable to create sub site using custom site template after modernizing the sites

### ISSUE THREAD

**Issue by RajiVenkat242** [SharePoint/sp-dev-modernization#310]
We modernized a classic site where it has few custom sub site templates available. But after upgrade, we are not able to create the sub sites using the classic sub site templates. Please advise the behavior of custom classic sub site templates in modern sites

**Comment by jansenbe** [comment]
Guess the issue is there because your tenant is configured to not show the subsite creation UI for modern site templates. Please verify this in tenant admin and adjust if needed.

![image](https://user-images.githubusercontent.com/7451219/66074312-3d037e80-e559-11e9-9e55-ba6501776428.png)

**Comment by RajiVenkat242** [comment]
Thank you. The settings are fine and able to create the sub site now.
