### ISSUE TITLE
Calendar List view web part Title column is incorrect

### ISSUE THREAD

**Issue by RajiVenkat242** [SharePoint/sp-dev-modernization#312]
After upgrading the classic page with Calendar xsltlistviewwebpart, the modern page web part doesn't show the Title value correctly. Please check the screenshots below. 
![ModernCalendatlistViewWebpart](https://user-images.githubusercontent.com/54291136/66239764-5dc60280-e718-11e9-8a1c-e219753e7b0b.png)

**Comment by jansenbe** [comment]
Hi @RajiVenkat242 ,

It's strange your calendar list gets transformed to a list web part...in our default mapping the calendar is transformed to the events web part. Are you using a custom webpartmapping.xml file?

**Comment by RajiVenkat242** [comment]
i am not using any custom web part mapping file. Please find below the command used for converting the page.  

ConvertTo-PnPClientSidePage -Identity "default.aspx" -Folder "<root>" -LogType File -LogFolder "D:\Scripts\log" -LogVerbose

**Comment by jansenbe** [comment]
The logic we today have to "identify" a calendar only works when a calendar view is selected. When the calendar for example is using the "All Events" view it's handled as a regular list. Let me see if I can still fix this for the October release

**Comment by jansenbe** [comment]
Issue is fixed. Please upgrade your PnP PowerShell version to the October version. This version will be released today.
