### ISSUE TITLE
Add Console Output option to LogType PowerShell

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#316]
#### Category

- [ ] Bug
- [X] Enhancement

#### Problem Area

- [ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
- [X] Page Transformation: Error during the use of page transformation from PnP PowerShell
- [ ] Page Transformation: Error during the use of page transformation from .Net
- [ ] Page Transformation: Page is not looking correct after transformation
- [ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

A Console Observer already exists for transformation, this observer is designed to write immediately to the console and not cache entries, so if there is an issue that prevents markup generation (which is cached until the end) this could be used to support diagnostics in support queries.

Add to LogType parameter in PnP PowerShell

**Comment by jansenbe** [comment]
Yep, that's a good idea @pkbullock . I'll make it happen.

**Comment by jansenbe** [comment]
Implemented :-)
