### ISSUE TITLE
Unable to Update Multiple Managed Metadata Values during Migration using Set-PnPListItem

### ISSUE THREAD

**Issue by arnostac** [SharePoint/sp-dev-modernization#322]
#### Managed Metadata - Term Store
PnP PowerShell after page conversion to set MMD fields
#### Expected or Desired Behavior
Be able Set MMD Field with Multiple Values

#### Observed Behavior
 **Running this works** 
Set-PnPListItem -List "Site Pages" -Identity $PageID -Connection $target -Values @{“Classifications” = "People|Classification|Office", "People|Classification|Field"; "Locations" = "People|Location|All Locations"}      

But we cannot update each page manually so when we try and do this Problematically we are hitting issues.
**Running This Fails
[MMD.zip](https://github.com/SharePoint/sp-dev-modernization/files/3731272/MMD.zip)

**
$csvlist = Import-CSV -Path C:\Temp\MMD.csv
foreach ($item in $csvlist  )
{          $Loc = $item.Loc

ConvertTo-PnPClientSidePage -Identity $Name -PublishingPage -overwrite -TargetConnection $target -PageLayoutMapping c:\temp\pagemap.xml -CopyPageMetadata -LogVerbose -LogType File -LogFolder c:\temp\Log 
$PageID = (Get-PnPFile -Url $modernpage -AsListItem -connection $target).Id

#_____________________START Locations UPDATE __________________
if ($Loc -eq "1847;#All Locations")
    {
    Set-PnPListItem -List "Site Pages" -Identity $PageID -Connection $target -Values @{"Locations" = "People|Location|All Locations";} -SystemUpdate     
    }
else
    {
     $LocList = $Loc -split ";#"
     $LocListClean=@()
    for ($i = 1; $i -le ($LocList.length - 1); $i += 2)
       {
           $LocListClean += '"People|Location|'+$LocList[$i] +'",'
       }

    } 
    $Value = @{
              Locations = "("+$LocListClean+")"
              }
             
   Set-PNPListItem -List "Site Pages" -Identity $PageID -Connection $target -Values $Value -SystemUpdate
    #_____________________END Locations UPDATE __________________

}
Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi @arnostac ,

The page transformation engine can set multi-value taxonomy fields during transformation if you specify them in your page layout mapping file and this should work fine if the **same** term groups, termset's and term's are available for the target site. In the case of SPO to SPO transformation this often is the case, but when transforming pages from on-premises to SPO this is not. 

So in your case using PnP PowerShell to set the metadata afterwards makes sense. Let me see if I can get the Set-PnPListItem cmdlet to work.

**Comment by arnostac** [comment]
Thanks Bert,
I have tried Several things But have not been successful. 

Stacey

**Comment by arnostac** [comment]
I still have not been able to get this to work. i have tried using GUIDS but still unable to set multiple

**Comment by jansenbe** [comment]
Sorry @arnostac , have not yet have time to look into this. Since this is PnP PS question you could also ask this question in the PnP-PowerShell repo issue list...there are more folks following that list.

**Comment by arnostac** [comment]
Thanks Bert,
I have come up with a work around using the term GUID to update.
