### ISSUE TITLE
JS/HTML/CSS code added in 'Edit Source'- Not transformed to the Modern page

### ISSUE THREAD

**Issue by PriyankaDevi510** [SharePoint/sp-dev-modernization#323]
[*] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[* ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

HTML/JS/CSS code to be available in modern page using script editor web part

#### Observed Behavior

Code is added using Edit source in a wiki Page. After transformation to modern, the content is missing. 

#### Steps to Reproduce

1.Create a wiki Page
2. Add HTML, JS code using the edit source button, available in Page's Edit ribbon
3. Convert the page to modern using "ConvertTo-PnPClientSidePage -Identity Pagename.aspx -AddPageAcceptBanner -UseCommunityScriptEditor -TakeSourcePageName"

**Comment by pkbullock** [comment]
Hi @PriyankaDevi510, this scenario isn't supported as the modern web parts do not allow CSS and JavaScript, we have coded the transformation tool to work in this way.

See: https://docs.microsoft.com/en-gb/sharepoint/dev/transform/modernize-userinterface-site-pages-webparts#contenteditorwebpart-web-part

**Comment by jansenbe** [comment]
Thanks @pkbullock .

The only way to "keep" JavaScript when transforming from classic pages is if:
- the script is inside either a content editor or script editor web part
- you've deployed the community modern script editor web part to your SPO tenant
- you tell the transformation engine to use the this modern script editor web part via the `-UseCommunityScriptEditor` parameter of the `ConvertTo-PnPClientSidePage` cmdlet

**Comment by jansenbe** [comment]
Hi @PriyankaDevi510 ,

Closing this one after the feedback given in today's call.
