### ISSUE TITLE
Tentative date for the Updated Modernization Scanner release

### ISSUE THREAD

**Issue by PriyankaDevi510** [SharePoint/sp-dev-modernization#330]
Hey Bert,

Kindly inform us with the tentative date for the upcoming Modernization Scanner update, to plan things accordingly

**Comment by jansenbe** [comment]
Just replied to the previous issue...but 3.14.1910.1 will come out any moment now :-)

**Comment by jansenbe** [comment]
And it's available: https://www.powershellgallery.com/packages/SharePointPnPPowerShellOnline/3.14.1910.1

**Comment by jansenbe** [comment]
nevermind...it's about the scanner....that one will be later this week

**Comment by jansenbe** [comment]
Scanner was released today: https://aka.ms/sppnp-modernizationscanner
