### ISSUE TITLE
Error while Transforming Classic SharePoint Pages To Modern - Index out of range

### ISSUE THREAD

**Issue by aswathee** [SharePoint/sp-dev-modernization#331]
#### Category

[x] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

All classic sharepoint home pages are transformed to modern pages( or create a modern version of it)

#### Observed Behavior

I am getting the following error while transforming home pages of _**some sites.**_
`Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.LastColumnOrder(Int32 row, Int32 col) at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List1 webParts) at SharePointPnP.Modernization.Framework.Transform.PageTransformator.Transform(PageTransformationInformation pageTransformationInformation)`

#### Steps to Reproduce

I am following the same code mentioned in the below Microsoft page:
https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell
I am using latest Pnp powershell version which is 3.14.1910.1

**Comment by jansenbe** [comment]
Hi @aswathee ,

Can you please do the following:
- Run the transformation with logging enabled and provide the output md file
- For the page that fails, I would need to inspect the wiki html which you can get into the clipboard using below PnP PowerShell script

```PowerShell
# Check the id of your home.aspx page
$p = Get-PnPListItem -List sitepages -Id 1
# copy contents into clipboard
$p.FieldValues["WikiField"] | clip
```

**Comment by Saurabh7019** [comment]
Same issue occurs when ShowInPageProperties is set to true for Enterprise keywords field. Here’s what I have in custompagelayoutmapping.xml

<MetaData ShowPageProperties="true" PagePropertiesRow="1" PagePropertiesColumn="3" PagePropertiesOrder="1">
	<Field Name="TaxKeyword" TargetFieldName="TaxKeyword" Functions="" ShowInPageProperties="true" />
	..
</MetaData>

**Comment by jansenbe** [comment]
@Saurabh7019 : can you create a new issue and provide the needed input (log file, cmd line used). Let's keep issues separated since I'm not sure this is the same problem.

**Comment by jansenbe** [comment]
@aswathee  / @Saurabh7019 : if you still have these issues with the latest release (3.14.1910.1) then please provide the requested details so I can look into this for the November release. If you're good then feel free to close this issue

**Comment by jansenbe** [comment]
Closing this issue as there's no reply. If the problem occurs again please create a new issue and specify the log file of the transformation and your wiki page content which can be fetched via:

```PowerShell
# Check the id of your home.aspx page
$p = Get-PnPListItem -List sitepages -Id 1
# copy contents into clipboard
$p.FieldValues["WikiField"] | clip
```

**Comment by Saurabh7019** [comment]
I am sorry for not being able to respond to this in time –

Issue in my case was not related to the bug raised by Aswathee. I was getting Index out of range error because I had specified PagePropertiesColumn="**3**" whereas my page had only 2 columns.
