### ISSUE TITLE
Document user mapping capability

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#337]

**Comment by pkbullock** [comment]
@jansenbe with the SkipUserMapping property, i am updating the PnP PowerShell to reflect the latest commit, this, or shall i ignore this as an option?

**Comment by jansenbe** [comment]
SkipUserMapping should be in PS as well...I did rename this to be more generic and align with the SkipUrlMapping one. This way we do have an option to revert back to the previous behavior for on-prem customers when we ship the November release. Thanks for looking into the PS side, let me know once done and I'll merge it

**Comment by pkbullock** [comment]
Cool, I should be updating the PR shortly, will update here. 

With the revert back to previous behavior, we blocked on-prem mapping as it wasn't an option, but with this option, this passes through which may cause an exception, do you think we need to update accordingly?

**Comment by jansenbe** [comment]
I did do testing with "no mapping available" which is the same as this "passthrough"...obviously more testing is welcome (I tested on SP2010 and SP2013). If there's really a blocking issue then we'll release an intermediate November release, but hoping that is not necessary.

**Comment by pkbullock** [comment]
btw - updated PS PR - https://github.com/SharePoint/PnP-PowerShell/pull/2340 for these options

**Comment by jansenbe** [comment]
PR merged and docs updated
