### ISSUE TITLE
Transformed pages are placed in root of Site Pages library, not in the folder the original page was in.

### ISSUE THREAD

**Issue by GCamilleri** [SharePoint/sp-dev-modernization#34]
Title says it all. Overwrite is enabled, TargetPageTakesSourcePageName is enabled. The modern version ends up in the root of the library, even when the original page was in a folder.

**Comment by jansenbe** [comment]
You're right, this is a bug. Will fix this in an upcoming release

**Comment by jansenbe** [comment]
Fixed in the dev branch. Closing this issue now. The fix will be included in the Feb drop of the modernization framework and pnp powershell. Can't release it earlier as it depends on folder support for the client side pages API which I added to the PnP-Sites-Core library.

**Comment by GCamilleri** [comment]
Excellent. Thanks!
