### ISSUE TITLE
Events web part not displaying all events from the calendar list

### ISSUE THREAD

**Issue by RajiVenkat242** [SharePoint/sp-dev-modernization#341]
The current Events web part does not show up all the events, instead we get only the upcoming events from the list. Please let us know if there are any options available in modern SP to show all the events (like the replacement of allevents view in calendar list view web part)

**Comment by jansenbe** [comment]
Hey @RajiVenkat242 ,

You can configure the events web part to use a date range which does make it show events from the past:
![image](https://user-images.githubusercontent.com/7451219/67853356-ab167380-fb0e-11e9-85cd-a5413c22b744.png)

This could be a manual change after transformation on the site where it makes sense.

**Comment by jansenbe** [comment]
Hey @RajiVenkat242,

Does the above answer your question? If so, then feel free to close the issue

**Comment by RajiVenkat242** [comment]
Yes, Thank you for the prompt response.
