### ISSUE TITLE
Web Part page layout not correctly mapped

### ISSUE THREAD

**Issue by a1mery** [SharePoint/sp-dev-modernization#342]
#### Category

[*] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[*] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

After transforming a classic page to modern, the layout of the webpart page is correctly mapped with webparts placed in exact section as in the classic page.

#### Observed Behavior

The page layout in not correctly mapped -> target layout is One Column whatever is the source layout.

#### Steps to Reproduce

1. On a modern team site (no Office 365 group), create a WebPart page inside the Site Pages library (choose "Header, Footer, 3 Columns" as example).
2. Run the page transformation engine (page transformation from .Net using SharePointPnP.Modernization.Framework.dll version 1.0.1910.1).

#### Additional informations

Before posting this issue I read the issue #261 and I checked the vti_setuppath of page. The vti_setuppath for my source (classic) page is : **1036**\STS\doctemp\smartpgs\spstd2.aspx

Thanks for your help

**Comment by jansenbe** [comment]
And fixed. Will close this issue, thanks for using page transformation and reporting this.
