### ISSUE TITLE
ConvesrtTo-PnPClientSidePage does not retain capitalized letters in folder name

### ISSUE THREAD

**Issue by kambridge** [SharePoint/sp-dev-modernization#343]
#### Category

**[ x ] Bug**
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
**[ x ] Page Transformation: Error during the use of page transformation from PnP PowerShell**
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

When running ConvertTo-PnPClientSidePage to read publishing pages in on-premises SharePoint and create the modern page in SharePoint Online, the text format (i.e. capitalized letters) should carry over to SharePoint Online

#### Observed Behavior

When running ConvertTo-PnPClientSidePage the cmdlet does not carry over the capitalized letters in the folder name.

#### Steps to Reproduce

# Setup connection the target site - must be SPO and must be a modern site
$target = Connect-PnPOnline https://contoso.sharepoint.com/sites/moderncommunicationsite -ReturnConnection

# Connect to your on-premises portal
Connect-PnPOnline https://portal2013.pnp.com/sites/classicportal -CurrentCredentials

# Convert a classic page living in the on-premises portal to a modern page in SharePoint Online. Dependent images and videos are copied as well from on-premises to online during this process.
ConvertTo-PnPClientSidePage -Identity "page1.aspx" -PublishingPage -Folder "Folder Name" -TargetConnection $target -LogVerbose -LogType File -LogFolder c:\temp

**Comment by jansenbe** [comment]
Thanks for reporting this @kambridge, good to see folks paying an eye on the details here. I've just committed a fix for this, which will be included in the upcoming November release. I'll close this issue now, but if you still have this issue after testing with the November release then please open a new issue.

**Comment by kambridge** [comment]
Hey @jansenbe, 
I see the November release is out. Do we need to wait for the PnP Module November release to see the updates?

**Comment by jansenbe** [comment]
@kambridge : November is not yet out...I've already updated docs, but the actual release will be there from Friday evening. Sorry for the confusion
