### ISSUE TITLE
Document URL rewrite updates + regenerate functions documentation page

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#344]

**Comment by pkbullock** [comment]
Morning @jansenbe with the functions docs, i have noticed a duplication of functions, possibly because the functions classes use inheritance so when both BuiltIn, PublishingBuiltIn is processed, the generator includes the BuiltIn twice.

**Comment by jansenbe** [comment]
@pkbullock , good feedback...let me check this (was just working on the docs)

**Comment by jansenbe** [comment]
There's indeed one duplicate (staticstring) as that one was needed for both publishing page layout mapping files and web part mapping files. For now I'm leaving this as is

**Comment by pkbullock** [comment]
lol thought there were more, your right 😊

**Comment by jansenbe** [comment]
docs updated
