### ISSUE TITLE
Add logging for start and finish asset transfer

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#345]
#### Category

- [ ] Bug
- [X] Enhancement

#### Expected or Desired Behavior

When assets are transferring, esp those of reasonable size, there is a perceivable pause in the logging output especially when in console logging mode - thus giving the impression the app is stuck, when its just uploading the data.

Add more logging points in asset transfer.

**Comment by jansenbe** [comment]
Makes sense. Do you want to include this in the November release or more thinking of the December release? For November the cut off date would be this week Thursday.

**Comment by pkbullock** [comment]
Yeap, ill add something before then - thanks for the deadline note.

**Comment by jansenbe** [comment]
Your change has been merged @pkbullock , thanks!
