### ISSUE TITLE
Page transformation doesn't carry over custom column values from original page.

### ISSUE THREAD

**Issue by GCamilleri** [SharePoint/sp-dev-modernization#35]
Our site has a custom column we use to sort pages. The column is validated against a list of known values. Transformed pages don't carry over their parent page's value from this column.

**Comment by jansenbe** [comment]
Good catch @GCamilleri. Will include this in an upcoming release

**Comment by jansenbe** [comment]
Support for metadata copy was added in dev branch. You'll have to set the CopyPageMetadata property of the PageTransformationInformation to true to trigger the copy. Updated nuget will come with the Feb release of PnP. Will close this issue for now, feel free to create a new one with specific details whenever you still have issues after testing the Feb drop. Thanks for reporting this.

**Comment by GCamilleri** [comment]
Thanks for the fix! I might clone the dev branch and have a go. Otherwise I look forward to it in Feb.

Cheers!
