### ISSUE TITLE
Modern Sharepoint sites observed to be working too slow in IE browsers

### ISSUE THREAD

**Issue by InfosysAdmin** [SharePoint/sp-dev-modernization#352]
Issues been reported heavily in IE browsers than in Chrome/Firefox. As IE is used by the widely, Issue fix of the same would be much helpful.

**Comment by jansenbe** [comment]
Hey @InfosysAdmin, this is not a problem related to page transformation but rather related to modern SharePoint. IE is indeed noticeably slower compared with modern browsers (the new Edge browser from Microsoft of Chrome). I would recommend switching to the new Edge browser, this browser does have a built-in IE11 tab in case a site needs IE11 while running all the other sites at optimal performance. 

If you feel that Microsoft should fix the IE11 performance then I would recommend to open a support case.

**Comment by jansenbe** [comment]
Closing this issue as it's not related to page transformation.
