### ISSUE TITLE
User Transform - Misleading remapping result in logging

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#354]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Observed Behavior

When user resides in a AD group, transformation remapping indicates user has been remapped to another but does not show, giving the false impression this hasn't worked - as users in groups are not processed.

#### Steps to Reproduce

```powershell

# Specified User Mapping
ConvertTo-PnPClientSidePage -Identity "Secret-Sauce-Recipe.aspx" -PublishingPage -TargetConnection $spOnlineConn -Connection $sp13Conn -Overwrite -ClearCache -LogType Console -PageLayoutMapping c:\temp\onprem-mapping-all-test.xml -UserMappingFile C:\temp\usermapping.csv -LogVerbose

```

**Comment by pkbullock** [comment]
Might be related to same issue in #355

**Comment by jansenbe** [comment]
I don't understand what goes wrong based up on your explanation...let me know if you still see issues when you test with the updated dev version

**Comment by pkbullock** [comment]
Closing put root cause in ticket #355 as similar fault.
