### ISSUE TITLE
User Mapping not working when specified mapping file

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#355]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Observed Behavior

Mapping not working - PS PowerShell no errors raised

Raising because cant fix until late tonight.

#### Steps to Reproduce

```powershell
ConvertTo-PnPClientSidePage -Identity "Secret-Sauce-Recipe.aspx" -PublishingPage -TargetConnection $spOnlineConn -Connection $sp13Conn -Overwrite -ClearCache -LogType Console -PageLayoutMapping c:\temp\onprem-mapping-all-test.xml -UserMappingFile C:\temp\usermapping.csv -LogVerbose
```

CSV Snippet
```
ALPHADELTA\SPInstall,Emily.Braun@capadevtest.co.uk
S-1-5-21-2364077317-3999105188-691961326-1103,AdeleV@capadevtest.onmicrosoft.com
c:0+.w|s-1-5-21-2364077317-3999105188-691961326-1129,c:0t.c|tenant|c293ebb4-5999-414f-b0c5-16e7a618db21
s-1-5-21-2364077317-3999105188-691961326-1128,Transform-Group
alphadelta\testuser1,Enrico.Cattaneo@capadevtest.co.uk
```

**Comment by pkbullock** [comment]
Some notes for repo:

- testuser1 with contribute permissions to page. 
- Page resides in a folder
- Page is custom layout
- Using Dev version of PS PowerShell. 
- Console logging shows successful replacement of users
- SP2013 to SPO. 
- Permissions on page not folder
- Author/Editor also not updating

**Comment by jansenbe** [comment]
@pkbullock : Permission management will not work with contribute permissions...can you retry with being administrator on both target site as source site?

**Comment by pkbullock** [comment]
Sorry, might not have been clear in the reproduction info, the transform accounts are admin.

**Comment by pkbullock** [comment]
I’ll be able to check around 5pm later on. On client site at the moment.

**Comment by jansenbe** [comment]
I'll try this from SP2013 with PS and update here

**Comment by jansenbe** [comment]
Found something not working with querying the user list...let me dive into it

**Comment by jansenbe** [comment]
@pkbullock : I did fix several things: https://github.com/SharePoint/sp-dev-modernization/commit/b93267385c4f295b62cb51538ac7d7051e59009a. Please test again and let me know. If needed I can still do some changes this evening, tomorrow morning...but the release will have to go out tomorrow

**Comment by pkbullock** [comment]
I have managed to get this working with the latest dev code. I found the root cause, is that i had blocked some of the test users in my tenant - which meant that they do not resolve in SPO and not getting the expected results. Thanks for looking into this!

**Comment by pkbullock** [comment]
This might be an enhancement opportunity to show this had occurred in reporting.

**Comment by jansenbe** [comment]
OK, closing this issue then. Thanks for the extra testing :-)
