### ISSUE TITLE
ConvertTo-PnPClientSidePage does not name sections in migrated page

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-modernization#356]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Each Section in the Migrated Page should be named (eg Column1 or Section1)

#### Observed Behaviour

The Sections in the migrated page are not named.  so when click on "+"  you get "add a new webpart in" rather than "add new webpart in column 1".  So you do not know where you are adding the webpart.

#### Steps to Reproduce

Take webpart page and run ConvertTo-PnPClientSidePage against it then  edit page and then click on the "+" sign.

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hey @NPrice99 ,

Sections in modern pages don't have names and columns are always "column one", "column two", ...when you click on the plus in the desired column you can add the web part or text in that column.

Can you clarify what actually goes wrong compared to editing a completely manually created page?

**Comment by NPrice99** [comment]
Hi Bert
The Sections in the migrated page are not named. so when click on "+" you get "**add a new webpart in**" rather than "**add new webpart in column 1"** when a page is created manually.. So you do not know where you are adding the webpart.
Regards
Nigel

**Comment by pkbullock** [comment]
Hi Both, this this might be a SPO bug rather transform, just converted pages in my dev tenant and see the full message.

**Comment by jansenbe** [comment]
I also see the full message...and these names are not even persisted in the page...seems indeed to be a temp SharePoint glitch.

**Comment by jansenbe** [comment]
@NPrice99 : will be closing this issue as it's not related to page transformation
