### ISSUE TITLE
Update logging when using user mapping SPO environment

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#357]
See 
![image](https://user-images.githubusercontent.com/7451219/68464905-bdc93080-0211-11ea-9a22-f05306a31dd5.png)

Can't use | signs in an MD table + "membership" is wrong

**Comment by pkbullock** [comment]
There is a method in the user transformator class that cleans this, but not thought to apply to reporting

**Comment by jansenbe** [comment]
Implemented
