### ISSUE TITLE
Vertical Section add empty columns

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#359]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[X] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Unused columns are removed or not added to get web parts into vertical section, there maybe cases where not all columns are needed to populate vertical section.

#### Observed Behavior

If you transform a page with 2 web parts, one with text, one image, set the image to Column 4, enable vertical section, on transform, the text resides in column 1, image in column 4, but 2 empty columns are added.

#### Steps to Reproduce

Source page with image and text

```xml
<PageLayout Name="NewsPageLayout" AssociatedContentType="" PageLayoutTemplate="AutoDetect" PageHeader="Custom" IncludeVerticalColumn="true">
...

<Field Name="PublishingPageImage" TargetWebPart="SharePointPnP.Modernization.WikiImagePart" Row="1" Column="4">
          <Property Name="ImageUrl" Type="string" Functions="ToImageUrl({PublishingPageImage})" />
          <Property Name="AlternativeText" Type="string" Functions="ToImageAltText({PublishingPageImage})" />
          <Property Name="Anchor" Type="string" Functions="ToImageAnchor({PublishingPageImage})" />
          <Property Name="Caption" Type="string" Functions="ToImageCaption({PublishingImageCaption})" />
        </Field>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="1">
          <Property Name="Text" Type="string" />
        </Field>
```

**Comment by jansenbe** [comment]
You're right. BasePageTransformator.RemoveEmptySectionsAndColumns does not take in account vertical column section types. Will fix this for the December release, this is not a blocking issue as the use of vertical columns anyhow is optional.

**Comment by jansenbe** [comment]
@pkbullock : just fixed this one
