### ISSUE TITLE
Create modern Version Gray Out

### ISSUE THREAD

**Issue by mgmjtech** [SharePoint/sp-dev-modernization#36]
I have followed the deployment guide using (pnp powershell). After I enabled the "the page transformation UI on the site collections", the "create modern version" is gray out.

Please advise

**Comment by jansenbe** [comment]
I've seen this as well, there's some caching ongoing for the ribbon XML. If you wait a while the cache seems to get cleared and it will show as enabled, otherwise clearing the browser cache and re-opening the browser should help as well.
