### ISSUE TITLE
Skip Asset transfer if asset exists

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#360]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

Performance

#### Expected or Desired Behavior

If the target site already contains an asset, e.g. you are overwriting transformed page, it isnt necessary to recopy up assets, for those environments with slow connections (like my test rig 😒)

**Comment by jansenbe** [comment]
well...you could use smaller files :-) 

But, yes this would be optimized.

**Comment by pkbullock** [comment]
Yeah, not the highest priority one.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pkbullock** [comment]
Closing this, i am using the ClearCache parameter, noticed in other transforms this is skipped.
