### ISSUE TITLE
StaticString for images option to use target site

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#361]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

In reference to docs: https://docs.microsoft.com/en-gb/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing#page-header-image-options

The URL has to be from source site, would be nice to have option for target or perhaps have dedicated functions for this type of usage. This way if pages contain images that are "replaced" by a specified image. 

Another observation, 
If you put full URL into path (to source file), transform appears to stop. Not sure why and might need some investigating, ideally this should have nice, don't do that message or handle this.

**Comment by jansenbe** [comment]
Hey @pkbullock , in my test the below works and grabs the file from the target site collection.

```Xml
<Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="StaticString('/sites/ModernizationTarget/SiteAssets/sitepages/Michael-Freedman/ms-stories-station-q-freedman-michael-12-1024x683.jpg')" />
```

About the fully qualified url's: 
- Specifying a full qualified url pointing to an image in the target site works for me
- Specifying a full qualified url pointing to an image in the source site results in the image not being copied over, hence the created page is not having a header image

So overall I don't see a reason to change anything at this moment.

**Comment by pkbullock** [comment]
Ok, thanks for looking into this, I’ll double check over weekend, what I was seeing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
