### ISSUE TITLE
Minor logging message misleading during user transform

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#363]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[X] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Logging improvement.

#### Observed Behavior

Highlighted below created by, modified by, user does not map to a user in SPO from On-Premises, generated message below.  As this message shows when EnsureUser fails, the message in this scenario doesn't describe what actually happened.

This is operating under default mode, to auto resolve the user SPInstall.

Marked as enhancement as, its not a blocker.

#### Partial Output from Console

[User Transform] Default remapping mechanism for user i:0#.w|alphadelta\spinstall
[User Transform] Not remapping user i:0#.w|alphadelta\spinstall
[User Transform] Default remapping mechanism for user i:0#.w|alphadelta\spinstall
[User Transform] Not remapping user i:0#.w|alphadelta\spinstall
**Warning: [Article page handling] Page could not be published as versioning is not enabled on the SitePages library.**
[Page Creation] Transformation Complete

**Comment by jansenbe** [comment]
@pkbullock : not sure what you mean here, but we can discuss later today

**Comment by jansenbe** [comment]
Done
