### ISSUE TITLE
ClearCache doesnt clear page layout mappings

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#364]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[X] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Observed Behavior

Clearing the cache doesnt emtpy the page mappings collection. For PowerShell, this requires the close the window/reopen in the scenario where you are tweaking page layout mapping files for their resulting changes.

Logging to fix soon, not working on this tonight. Its super minor but can help with testing of mapping configuration files.

**Comment by jansenbe** [comment]
Yes, let's fix this.

**Comment by jansenbe** [comment]
Done
