### ISSUE TITLE
Specific layout throws "out of range" error

### ISSUE THREAD

**Issue by a1mery** [SharePoint/sp-dev-modernization#371]
#### Category

[*] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[*] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

A classic WebPart page with the following layout : **Header, Footer, 4 Columns, Top Row** is correctly transformed into a modern client-side page. All the WebPart zones of the source page contain at least one WebPart.

#### Observed Behavior

The page transformation engine throws the following error : 

> Page ClassicPage.aspx could not be transformed: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Detailed error message : 

> Exception thrown: 'System.ArgumentOutOfRangeException' in SharePointPnP.Modernization.Framework.dll

#### Steps to Reproduce

1. On a modern team site (no Office 365 group), create a WebPart page inside the Site Pages library with the following page layout : **Header, Footer, 4 Columns, Top Row**.
2. Insert a WebPart in each WebPart zone.
3. Run the page transformation engine (page transformation from .Net using SharePointPnP.Modernization.Framework.dll version 1.0.1911).

#### Additional informations

When using custom layout mapping (using a custom modern layout with more sections than the default one), the transformation works fine.

Thanks for your help

**Comment by jansenbe** [comment]
Hi @a1mery ,

Is your source site in a non-english language?

**Comment by a1mery** [comment]
Hi @jansenbe ,

Yes, originally  my source source site was in a non-english language (french). But I've just tried with an english language site and the issue seems to be the same.

Thanks

**Comment by jansenbe** [comment]
@a1mery : I could repro this and will commit a fix shortly. The fix will be included in December release.

**Comment by jansenbe** [comment]
Fix has been committed. Will close this issue, but feel free to raise it again if things still fail with the December release. Tentative timeline for the December release is end of next week.

**Comment by a1mery** [comment]
Thanks again for your help !
