### ISSUE TITLE
Converting on-prem publishing pages

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#373]
[ ] Bug
[ ] Enhancement
[X] Question

To transform on prem publishing pages, does the script have to be run from the server where the source pages exist?

**Comment by pkbullock** [comment]
Nope you can run  outside farm. Uses CSOM or Web services to talk to both environments, these don’t need to be on farms servers. I know some orgs block internet access from servers.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by russgove** [comment]
Thanks Paul

**Comment by jansenbe** [comment]
Think this one can be closed
