### ISSUE TITLE
Delve Blog Conversion

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#377]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

There is some demand from a twitter conversion, to have the recently announced retirement of Delve Blogs conversion to Modern communication sites.

https://twitter.com/Beau__Cameron/status/1198993577117802496?s=20 

#### Observed Behavior

There is a REST API to retrieve contents that can be used.

**Comment by jansenbe** [comment]
Done!
