### ISSUE TITLE
.Net Transformation engine is unable to copy the page metadata other than the contents on the page

### ISSUE THREAD

**Issue by SrihariKundargi** [SharePoint/sp-dev-modernization#379]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from .Net

#### Expected or Desired Behavior

The page metadata should get updated on the transformed pages.

#### Observed Behavior

The page metadata such as Created, Modified, Created By, Modified By, or any other custom metadata field values are not getting added on transformed page other than the actual content embed on the source page.

#### Steps to Reproduce

Try to add the mappings of custom fields in the pagelayoutmapping.xml that are actually not embed on the page. The values don't get transformed other than the actual content on the source page.
For example, I add the below mappings in the pagelayoutmapping.xml
<Field Name="Created" TargetFieldName="Created" Functions="" />
<Field Name="Modified" TargetFieldName="Modified" Functions="" />
<Field Name="Author" TargetFieldName="Author" Functions="" />
<Field Name="Editor" TargetFieldName="Editor" Functions="" />
<Field Name="AverageRating" TargetFieldName="AverageRating" Functions="" />
<Field Name="LikesCount" TargetFieldName="LikesCount" Functions="" />
<Field Name="RatingCount" TargetFieldName="RatingCount" Functions="" />
<Field Name="Tags" TargetFieldName="Tags" Functions="" />
None of the above field values get updated on the transformed page.
Please help on this issue.

Thanks & Regards,
Srihari

**Comment by jansenbe** [comment]
Hey @SrihariKundargi ,

Can you add the screenshot you mentioned above...it's not visible for me. Also please enable logging (add `-LogType File -LogVerbose -LogFolder c:\temp`) and share the log. It will tell which fields are copied and which ones are skipped. The target site must have the fields defined, page transformation will not update the target SitePages library.

To keep Created, Modified, Created By, Modified By you need to specify the `-KeepPageCreationModificationInformation` parameter.

**Comment by SrihariKundargi** [comment]
![image](https://user-images.githubusercontent.com/56874792/69728036-b37fbf80-1149-11ea-9a19-776b1b8279a1.png)

Hi @jansenbe ,

Thank you for the quick reply. 
Attaching the log file:
I set pti.KeepPageCreationModificationInformation = true; and the log file for this Page-Transformation-Report-With-KeepPageCreationModificationInformation.txt
[Page-Transformation-Report-With-KeepPageCreationModificationInformation.txt](https://github.com/SharePoint/sp-dev-modernization/files/3897093/Page-Transformation-Report-With-KeepPageCreationModificationInformation.txt)
None of the fields get updated on the destination. Only the page content get added on the page.
<img width="422" alt="FieldMapping" src="https://user-images.githubusercontent.com/56874792/69728653-d2328600-114a-11ea-87db-7f01b7edcbf6.PNG">

Thanks & Regards,
Srihari

**Comment by jansenbe** [comment]
You never reached the code that handles the metadata copy as there's somewhere an error (as seen in the log file). Can you share command line you're using? Can you try without specifying a custom page layout mapping and see if that works?

```
_The given key was not present in the dictionary.   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingMetadataTransformator.Transform()
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)_ 

### 11/27/2019 7:05:56 PM - [/qwiki/pages/bldinstall_adev_pdd.aspx](https://qwikmind.mindtree.com/qwiki/pages/bldinstall_adev_pdd.aspx)

_The given key was not present in the dictionary.   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingMetadataTransformator.Transform()
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)_ 
```

**Comment by SrihariKundargi** [comment]
Hi @jansenbe ,

I'm using "**pti.KeepPageCreationModificationInformation = true**" to keep the source created and modified information. If I don't use the above line, the page gets transformed with the contents but the metadata doesn't get copied.
[Page-Transformation-Report-WithPageMetadataCopied.txt](https://github.com/SharePoint/sp-dev-modernization/files/3900000/Page-Transformation-Report-WithPageMetadataCopied.txt)

If I don't using a custom pagelayoutmapping the transformed page is blank.

Thanks,
Srihari

**Comment by jansenbe** [comment]
Based upon the log output you're not running the latest version. Please use the November version of PnP PowerShell (3.15.1911.0) and also please share the your page layout mapping file that you created.

**Comment by jansenbe** [comment]
Hi @SrihariKundargi ,

Is this still a problem for you? If so can you please test with the latest release (December version - 3.16.1912.0) and provide the page layout mapping file you're using

**Comment by jansenbe** [comment]
Hey @SrihariKundargi ,

Given there was no feedback for over 2 weeks I'm gonna close this issue. If you still have this issue then please retest with the latest release and provide the requested input in a new issue.
