### ISSUE TITLE
Source Connector Framework

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#383]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

Design and build a framework for connecting to custom sources beyond SharePoint. 

The idea is to build a common source format e.g. a XML file or another suitable common input that the transformation tool can convert to modern pages. We can then have a separate library/tools/scripts for connecting to an alternative source generate this file that the transformation framework can process. This would support non-SharePoint source intranets (based on a large new incoming requirement).

In theory, the same method can in future be used to support a on-premises transformation using the hosted service by having an agent, tool running on source system.

Customers, if they wish can define their own connector.
 
Idea diagram:
![Modernisation Diagrams - Non-MS Source](https://user-images.githubusercontent.com/8781041/69852390-0a85b180-127c-11ea-87f8-01e192d441b9.png)

**Comment by jansenbe** [comment]
@pkbullock : interesting idea, what type of source environments are you looking at? Think the key aspect in this solution is that the extractor will produce content that aligns with the current model, meaning it should work a little bit like the current Delve implementation: creating a list of "fake" web parts with properties (e.g. WikiTextPart with valid html in it's text property) which then are send into the transformation pipeline. Let's discuss more next week

**Comment by jansenbe** [comment]
@pkbullock : do you still want to keep this one open? It's a massive effort and  I personally have not seen any demand for it so far.

**Comment by pkbullock** [comment]
@jansenbe this one is frustrating there is a possibility that it might be useful to the client but the programme is work is moving very slowly, could be a long time before this surfaces as a requirement if at all. I'll close, we can either raise new or re-open. 

I am quite surprise that MS customers have very little demand to move from legacy portals (non-MS) to SharePoint Modern, given so many orgs now have O365.
