### ISSUE TITLE
highlighted content webpart - user profile custom property as an filter to choose properties

### ISSUE THREAD

**Issue by paxvas** [SharePoint/sp-dev-modernization#385]
highlighted content webpart now offers filtering on user properties via KQL. As normal enterprise users are not really able to use KQL for their queries, is there a plan to offer filtering based on user properties to make the ease of use better. Are there any thoughts toward that?

**Comment by jansenbe** [comment]
Let me check

**Comment by jansenbe** [comment]
Hi @paxvas , currently this is not possible. Can you provide more details on the scenario you would like to have? The Highlighted content web part owners would like to better understand your ask.

**Comment by paxvas** [comment]
Dear Bert,

As we nowadays move away from a prebuilt intranet or collaboration site and
we give the site owners more control on how they can offer content to their
team/department/company, we should consider that these people are not
really developers, more configurators.

As an site owner I would like to offer rich personalized content to my
team/department/company. I insert  multiple highlighted webparts and I
would like for example show following information.

1. News

   - Content Type= News AND MMD Field Department = Global OR MMD Field
   Department= user. department (information from the user profile)

2 Events

   -   Content Type= Event AND MMD Field Location = user. locations
   (information from the user profile, If I work in different locations I can
   choose them in user profile)

3 Daily Menu

   - Content Type= Daily Menu AND MMD Field Location = user. locations
   (information from the user profile, If I work in different locations I can
   choose them in user profile)

4 Videos

   - Content Type= Video AND MMD Field Topic = user.interest (information
   from the user profile, I can choose them in user profile)

These are just a few examples and I already build a lot of them in former
SP versions with search webparts.

As I understand highlited webpart is a hybrid between CQWP and Search. If
the filtering is not possible with CAML, why not use search with an similar
interface as content by search webpart was. So the site owner can choose
their content type, metadata and personalization metadata (current user,
user.department, user.mycustomfield - showing all user profile fields under
user).

I f it is not clear what I like to say I can also make some wireframes, so
that it is more visible.

Thx for your help.

kind regards janko



Am Mo., 9. Dez. 2019 um 09:02 Uhr schrieb Bert Jansen <
notifications@github.com>:

**Comment by jansenbe** [comment]
Thx @paxvas, I've provided this input.

**Comment by jansenbe** [comment]
What you need in on our HCWP backlog, although not with an already defined target date. Thanks for the suggestion!

**Comment by paxvas** [comment]
Thx for your help

Am Di., 10. Dez. 2019 um 17:39 Uhr schrieb Bert Jansen <
notifications@github.com>:
