### ISSUE TITLE
Update docs to ensure aadtenant is seen as xxx.onmicrosoft.com and not xxx.sharepoint.com

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#389]

**Comment by Forket** [comment]
Keep in mind that if default tenant is set as custom tenant, than this custom tenant should be used. E.g.:
i have tenant **mycompany.com**, in this case mycompany.com should be used instead of ~~mycompany.onmicrosoft.com~~

**Comment by jansenbe** [comment]
Done
