### ISSUE TITLE
ConvertTo-PnPClientSIdePage reports overwrite previous reports

### ISSUE THREAD

**Issue by rudfoss** [SharePoint/sp-dev-modernization#394]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Provide a way to make transformation report file names more distinct. For instance it could include the name of the file being converted. Since files cannot have the same name within a library this should ensure one report does not overwrite another. Maybe also include the seconds in the date as it usually takes a few seconds to process the page.

E.g.:
```
Transformation-Reports/Page-Transformation-Report-[page-name]-[date]
```

#### Observed Behavior

Setting -LogType File or SharePoint produces report files in their respective locations, with file names following a standard pattern: `Page-Transformation-Report-[date]`. When running multiple migrations as part of a script these report names are not distinct enough causing subsequent reports to override older ones.

#### Steps to Reproduce

See Observed behaviour

PowerShell PnP Version: `3.16.1912`

**Comment by rudfoss** [comment]
Including the page name would also make it much easier to connect the correct report to the migrated page.

**Comment by jansenbe** [comment]
Hi @rudfoss ,

Thanks for your feedback. The generated reports have a timestamp in them with allows to have a report per second and given that transforming a page will in all cases take more than a second I don't see how you can have reports that overwrite each other. Can you cross check that you actually see reports being overwritten?

About the name: as you can configure the the transformation to "accumulate" the report data of multiple pages in a single report we do not put the page name in the report. Use the `-LogSkipFlush` parameter on the  `ConvertTo-ClientSidePage` cmdlet and then when you've transformed your pages call the `Save-PnPClientSidePageConversionLog`  cmdlet to trigger the logs to persist.

![image](https://user-images.githubusercontent.com/7451219/70789816-0c7b6480-1d94-11ea-827c-054864e15dfd.png)

**Comment by rudfoss** [comment]
Hi, thanks for the quick reply. I did not know about the accumulation feature. Will definitely check that out. Regarding the name, my reports do not contain the time down to the second, maybe it has something to do with the locale on my machine or site (Norwegian, 1044)?

Regardless, if i can accumulate the reports that is enough for me to resolve the issue. Thanks for the tip! I'll implement it immediately.

**Comment by jansenbe** [comment]
Thanks for the reply. I'll close the issue then
