### ISSUE TITLE
Unable to add js/jquery/html code to list view page (Eg Allitems.aspx, ByAuthor.aspx) in Modern

### ISSUE THREAD

**Issue by InfosysAdmin** [SharePoint/sp-dev-modernization#395]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug
[*] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[*] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

After transforming the list to New experience, The list views' pages(Eg Allitems.aspx, ByAuthor.aspx) which has got custom code added using webpart is missing.

#### Steps to Reproduce

Add a webpart and add js code to Allitems.aspx page of any list. Change the list experience to Modern.

**Comment by jansenbe** [comment]
Page transformation will not update lists...so your lists have to be in place in the target site. If the list used some JS based customization (e.g. JSLink) then that customization indeed does not work anymore on the modern lists. This is not an issue with page transformation, it's simply how modern lists work. If the JS based customization is important you should consider rewriting it using SharePoint Framework. https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions is a good example that shows how to rebuild a JSLink based customization as an SPFX extension.

**Comment by jansenbe** [comment]
Closing as this is not something to fix in page transformation
