### ISSUE TITLE
Accessibility in Partner slide desk

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#396]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...
[X] Partner Content

#### Expected or Desired Behavior

To be inclusive as possible.

#### Observed Behavior

They contain accessibility errors or issues

**Comment by pkbullock** [comment]
@jansenbe is it best to make the corrections in the dev branch and are you doing any updates?

**Comment by jansenbe** [comment]
Hi @pkbullock, Jjust fix the issues in the dev branch. Interesting to understand what you're about to fix?

**Comment by pkbullock** [comment]
So just looking though the accessibility checker and addressing the issues (150+ for Delivery Guide) with the aim of not changing the look to the presentation e.g  Adding alt text, marking slide titles as titles, etc.

**Comment by jansenbe** [comment]
Thx @pkbullock , I've just merged this.
