### ISSUE TITLE
ConvertTo-PnPClientSidePage with WebPartMapping file - No web parts are added

### ISSUE THREAD

**Issue by MartinHatch** [SharePoint/sp-dev-modernization#407]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

Using January 2020 version of PnP-PowerShell

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[X] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
After running the cmdlet - I would expect the web parts on the converted page to be correct.

#### Observed Behavior

I am using ConvertTo-PnPClientSidePage with both a custom Page Layout mapping file, and a Web Part mapping file. 

Initially I had my page being converted correctly. 
I then tried to add my own custom web part to each page.

**1. Created a "WebPartMappings.xml" file**
(downloaded this):
https://github.com/SharePoint/PnP/blob/master/Samples/Modernization.PageTransformation/Modernization.PageTransformation/webpartmapping.xml

**2. Added my own Web Part to the file**
I then added my own Web Part entry to the file:
(note - the Control Id GUID is the same as the "id" value from my Web Part Manifest JSON)

`
 <WebPart Type="PFP.PageProperties" CrossSiteTransformationSupported="true">
            <Properties>
                <Property Name="Title" Type="string" />
            </Properties>
            <Mappings>
                <Mapping Default="true" Name="default">
                    <ClientSideWebPart Type="Custom" ControlId="71703ef5-5f64-483d-8cd5-2f733f81a42a" Order="10" JsonControlData="&#123;&quot;serverProcessedContent&quot;: &#123;&quot;htmlStrings&quot;: &#123;&#125;,&quot;searchablePlainTexts&quot;: &#123;&#125;,&quot;imageSources&quot;: &#123;&#125;,&quot;links&quot;: &#123;&#125;&#125;,&quot;dataVersion&quot;: &quot;1.0&quot;,&quot;properties&quot;: &#123;&quot;Title&quot;: &quot;Page Properties&quot;&#125;&#125;"/>
                </Mapping>
            </Mappings>
        </WebPart>
`

**3. Added an entry in the Page Layout mapping...**
`
   <WebParts>
       <Field Name="ID" TargetWebPart="PFP.PageProperties" Row="2" Column="2" Order="1">
          <Property Name="Title" Type="string" Functions="StaticString('PFP Properties')"/>
        </Field>
      </WebParts>
`

**What actually happens**
After the script runs there are NO web parts on the page at all.

If I DO NOT use my own WebPartMapping file .. then all of the "OOTB" web parts (e.g. text / images) come through fine .. but my custom web part is instead replaced with:

`
*** Web Part PFP Properties was not transformed ***
`

**Comment by jansenbe** [comment]
@MartinHatch : Can you do a run with verbose logging enabled and share the log file? 

What you did seems to be correct at first sight (based upon our docs: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing#i-want-to-add-an-extra-web-part-on-the-created-page).

**Comment by MartinHatch** [comment]
Yep, those were pretty much the steps I followed. 

Log file is attached (just rename extension back to ".md")
[Page-Transformation-Report-22-01-2020-13-48-48.md.txt](https://github.com/SharePoint/sp-dev-modernization/files/4097602/Page-Transformation-Report-22-01-2020-13-48-48.md.txt)
[Page-Transformation-Report-22-01-2020-13-48-52.md.txt](https://github.com/SharePoint/sp-dev-modernization/files/4097603/Page-Transformation-Report-22-01-2020-13-48-52.md.txt)

**Comment by jansenbe** [comment]
It seems to see all webparts as "non usable in cross site"...can you also share the commandline you've used?

**Comment by MartinHatch** [comment]
Sure.

Note - if I do NOT use my own WebPartMapping file .. then it works FINE .. but obvious doesn't include my custom web part.

**This doesn't work - zero web parts on the page**
`
ConvertTo-PnPClientSidePage -PublishingPage -Identity "$fileName" 
				-Overwrite 
				-TargetWebUrl $TargetUrl 
				-PageLayoutMapping "$currentDir\Mappings\PFP_Mappings.xml" 
				-WebPartMapping "$currentDir\Mappings\WebPartMappings.xml" 
`

**This works fine for OOTB web parts - but no custom webparts**
`
ConvertTo-PnPClientSidePage -PublishingPage -Identity "$fileName" 
				-Overwrite 
				-TargetWebUrl $TargetUrl 
				-PageLayoutMapping "$currentDir\Mappings\PFP_Mappings.xml" 
`

**Comment by jansenbe** [comment]
Also saw this: ´Web Part:'EmptyString()' of type 'Microsoft.SharePoint.WebPartPages.ContentEditorWebPart' is being transformed´

Can you provide full webpartmapping and pagelayoutmapping files. You can also mail them to bjansen@microsoft.com if you prefer that

**Comment by MartinHatch** [comment]
Email on the way

**Comment by jansenbe** [comment]
in calls for the coming hours, but will look into this after that

**Comment by MartinHatch** [comment]
Ok forget it ... I've worked it out

I should have used the "Export-PnPClientSidePageMapping -BuiltInWebPartMapping" command to generate the WebPartMapping file .. instead of using the one on GitHub! 

Using this and the issue appears to be resolved! SORRY!

**Comment by jansenbe** [comment]
NP, glad it now works!
