### ISSUE TITLE
List view Page-Unable to switch to New Experience- When webparts added

### ISSUE THREAD

**Issue by InfosysAdmin** [SharePoint/sp-dev-modernization#409]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[#] Bug
[ ] Enhancement

#### Problem Area

[#] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
List view Page with webparts(content editor) should be able to switch to New experience

#### Observed Behavior

After adding web parts to List view page, unable to switch the page to new experience

#### Steps to Reproduce

Add a content editor webpart to list view page. Add a link/html code. switch the List experience to new experience.

**Comment by jansenbe** [comment]
Hi @InfosysAdmin , 

When a list view page contains more than one web part it cannot be shown as a modern page. This is a know limitation of modern list view pages. The solution is to remove all but the needed XSLTListView web part from the page. If you've many list view pages that need this change then you can automate this as shown here: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-lists-and-libraries#customized-list-view-pages-that-contain-more-than-the-list-xsltlistviewwebpart

**Comment by InfosysAdmin** [comment]
We have a scenario in which a library has 5 views, in which 1 view has a multiple list view webpart and the other views don't have any webparts. While upgrading to Modern, only the view which don't have any webparts render in modern and the view with list view webpart is rendering in classic. Is this the normal behavior for a library?

**Comment by jansenbe** [comment]
SharePoint will automatically flip back to classic if it detects a situation where modern can't be used. Typical cases are:
- the list view/edit pages have multiple web parts: a view/edit page should only have one XSLTListView web part
- The view is showing columns which are not compatible with modern or the view is using JSLink/Xsl to customize it's rendering

See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-lists-and-libraries for the details on this. You can also run the modernization scanner (https://aka.ms/sppnp-modernizationscanner) on your site to better understand the found incompatibilities.

**Comment by jansenbe** [comment]
Hey @InfosysAdmin , I'm closing this issue as it's not something related to page transformation. Hope the above answers provided you the feedback you needed.
