### ISSUE TITLE
Question : How can you set a fixed Taxonomy value for newly converted pages?

### ISSUE THREAD

**Issue by MartinHatch** [SharePoint/sp-dev-modernization#411]
This is just a fairly simple question.

If you are using ConvertTo-PnPClientSidePage and have a custom Page Layout Mapping file, how can you specify a custom Taxonomy value to assign to the newly created pages?

I've tried assigning a "StaticString" function using the term label, but that doesn't work.

**Comment by jansenbe** [comment]
Hi @MartinHatch ,

Currently we do not support function calls on metadata fields, hence your StaticString function is never invoked. I'll see if I can come up with some default functions here in anticipation of a more broader taxonomy mapping support.

**Comment by MartinHatch** [comment]
It's particularly bad because the default values in the Site Pages library don't seem to stick either..

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jansenbe** [comment]
I'll try to have a something done for the Feb release. You're ok with a function in which you can specify a default term value?

**Comment by jansenbe** [comment]
@MartinHatch: as of the Feb release you'll be able to do set default values as shown below. For single value taxonomy fields specify a single term id, for multi value you specify multiple values delimited by |. The bool parameter at the end allows you to configure overwrite: if 'false' then the default values are not set when the field already contains term(s).

```Xml
<MetaData ShowPageProperties="true" PagePropertiesRow="1" PagePropertiesColumn="4" PagePropertiesOrder="1">
...
        <Field Name="TaxField2" TargetFieldName="Metadata2" Functions="DefaultTaxonomyFieldValue({TaxField2},'a65537e8-aa27-4b3a-bad6-f0f61f84b9f7|69524923-a5a0-44d1-b5ec-7f7c6d0ec160','true')" ShowInPageProperties="true"/>
...
</MetaData>
```

**Comment by jansenbe** [comment]
Closing this one as the feature will ship in the February release. Docs have just been updated

**Comment by MartinHatch** [comment]
@jansenbe just a note on this (and I know this was closed)

Any chance we could use the path instead of the ID?
The reason being, I'm testing this in Dev / Test .. they have different GUID values in different environments. 

So instead of specifying: 

`DefaultTaxonomyFieldValue({TaxField2},'a65537e8-aa27-4b3a-bad6-f0f61f84b9f7|69524923-a5a0-44d1-b5ec-7f7c6d0ec160'`

How about instead doing:

`DefaultTaxonomyFieldValue({TaxField2},'GroupName\TermSetName\Term\SubTerm'`

So for example, if this was countries it might look something like:

`DefaultTaxonomyFieldValue({TaxCountry},'Taxonomy_4NiNeoiKGkSe2IfG6uWAvw==\MyTermGroup\Countries\Europe\UK'`
