### ISSUE TITLE
Question : Page Layout Mapping > How can I add a fixed "title" above a field mapping?

### ISSUE THREAD

**Issue by MartinHatch** [SharePoint/sp-dev-modernization#413]
Another quick question.

I have a Page Layout which contains a Publishing HTML field. In the page layout this has a fixed title of "Goals".

I have achieved this initially by doing the following in my Page Layout Mapping:

 - Add a fixed Content Editor web part with content set to 'Goals' (as an H2)
 - Add the HTML field mapping below it.

However .. there are TWO things wrong with this approach:

 1. I end up with Two Text web parts on the modern page (one for the title, and one for the HTML content)

 2. If the HTML field is empty .. I don't want the title to render... 

I have tried using the following, but it didn't work:

`
   <Field Name="My_Goals" Row="1" Column="1" Order="2" 
             TargetWebPart="SharePointPnP.Modernization.WikiTextPart"
             <Property Name="Text" Type="string" Functions="Concatenate(StaticString('Goals'),{Text})" />
    </Field>
`

Is there a way of doing this? either merging multiple HTML fields into one .. or adding / concatenating fixed HTML when converting?

**Comment by jansenbe** [comment]
@MartinHatch , using the extra web part approach indeed is not perfect. For the upcoming February release I've foreseen 3 extra functions that allow you to prefix and/or suffix your html field value. Usage would be like shown below:

```Xml
<WebParts>

...
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
          <Property Name="Text" Type="string" Functions="PrefixAndSuffix('&lt;H1&gt;Prefix some extra text&lt;/H1&gt;','&lt;H1&gt;Suffix some extra text&lt;/H1&gt;',{PublishingPageContent},'false')" />
        </Field>
...
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
          <Property Name="Text" Type="string" Functions="Prefix('&lt;H1&gt;Prefix some extra text&lt;/H1&gt;',{PublishingPageContent},'true')" />
        </Field>
...
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
          <Property Name="Text" Type="string" Functions="Suffix('&lt;H1&gt;Suffix some extra text&lt;/H1&gt;',{PublishingPageContent},'false')" />
        </Field>
...
</WebParts>
```

**Comment by MartinHatch** [comment]
Otherwise could we not just make use of the Title attribute?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jansenbe** [comment]
Which title attribute are you referring to? This approach replaces the need for adding an extra content editor web part in the mapping file, you just need to use the correct function on the field that you want to have a prefix or suffix on.

**Comment by MartinHatch** [comment]
Isn't the web part title element currently ignored for Text fields/text web parts

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jansenbe** [comment]
there's no title as in publishing scenarios you have a html field

**Comment by MartinHatch** [comment]
Just a final thought on this (and thank you for putting so much effort in)

Given we already have the Concatenate function, wouldn't that make "Prefix" / "Suffix" functions obsolete? 
(Concat is also more flexible)

**Comment by jansenbe** [comment]
Concat does not have a flag to set the "apply if content is empty or not" + you're limited to a single function when using function in page layout templates (in the webpartmapping file you can use multiple) so with a concat you would not be able to realize what you need.

**Comment by jansenbe** [comment]
Closing this one as the feature will ship in the February release. Docs have just been updated

**Comment by MartinHatch** [comment]
@jansenbe Using the code sample you provided above I get the error:

ConvertTo-PnPClientSidePage : An item with the same key has already been added.

```
<WebParts>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
          <Property Name="Text" Type="string" Functions="PrefixAndSuffix('&lt;H1&gt;Prefix some extra text&lt;/H1&gt;','&lt;H1&gt;Suffix some extra text&lt;/H1&gt;',{PublishingPageContent},'false')" />
        </Field>
</WebParts>
```

**Comment by MartinHatch** [comment]
Just to be 100% clear - if I remove this line (and revert to a "standard" web part) then the error goes away and the page transformation works fine!
