### ISSUE TITLE
Warnings not showing in Output logs

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#420]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[X] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Warnings should be reported and listed in Log Verbose mode.

#### Observed Behavior

They are not working, sometimes the resulting transform is showing successful when it in fact should have warnings, which is slightly misleading.

Affected observer is the Markdown report.

#### Steps to Reproduce

Transform something that would generate warnings. e.g. page with unsupported web parts.

@jansenbe was warning output removed from Markdown reports for any reason? Happy to investigate and fix if not.

**Comment by jansenbe** [comment]
Hi @pkbullock , I've just tested and I do see warnings popping up in the log file. Below is a sample log file of a transformation with a malformed table. Did you see this in on-premises bits?

# Modernisation Summary Report

Date  |  Duration  |  Source Page  |  Target Page Url  |  Status
-------------  |  -------------  |  -------------  |  -------------  |  -------------
29/01/2020 9:17:40  |  00:00:19  |  [/SitePages/table_12_bug_404.aspx](https://bertonline.sharepoint.com/sites/modernizationtestpages/SitePages/table_12_bug_404.aspx)  |  [/SitePages/Migrated_table_12_bug_404.aspx](https://bertonline.sharepoint.com/sites/modernizationtestpages/SitePages/Migrated_table_12_bug_404.aspx)  |  Successful with 1 warnings and 0 non-critical errors
## Warnings during transformation

Date  |  Source Page  |  Operation  |  Message
-------------  |  -------------  |  -------------  |  -------------
29/01/2020 9:17:58  |  /SitePages/table_12_bug_404.aspx  |   Built-in Function  |  Table could not be normalized and will be taken over as is. Error = Index was outside the bounds of the array.
# Individual Page details
## Transformation Details: /SitePages/table_12_bug_404.aspx

- Report date: 29/01/2020 9:17:37
- Transform duration: 00:00:19
- Mode:  Wiki Page Transformation
- Transforming from site: https://bertonline.sharepoint.com/sites/modernizationtestpages
- Transforming page: /sites/modernizationtestpages/SitePages/table_12_bug_404.aspx
- Source SharePoint version:  Online (16.0.0.12068)
- Transformed Page: /sites/modernizationtestpages/SitePages/Migrated_table_12_bug_404.aspx

### Page Transformation Settings

Property  |  Setting
-------------  |  -------------
Engine version   |   1.0.2001.0
Target Page Takes Source Page Name   |   False
Target Page Prefix   |   Migrated_
Source Page Prefix   |   Previous_
Copy Page Metadata   |   False
Set Author In Page Header   |   False
Replace Home Page With Default Home Page   |   False
Overwrite   |   True
Target Page Name   |   Not Specified
Target Page Folder   |   Not Specified
Target Page Folder Overrides Default Folder   |   False
Keep Page Specific Permissions   |   True
Remove Empty Sections And Columns   |   True
Handle Wiki Images And Videos   |   True
Add Table List Image As Image Web Part   |   True
Keep Page Creation Modification Information   |   False
Publish Created Page   |   True
Post As News   |   False
Disable Page Comments   |   False
Skip Url Rewrite   |   False
Skip Default Url Rewrite   |   False
Url Mapping File   |   Not Specified
Skip User Mapping   |   False
User Mapping File   |   Not Specified
L D A P Connection String   |   Not Specified
Skip Telemetry   |   True
### Transformation Operation Details

Date  |  Operation  |  Actions Performed
-------------  |  -------------  |  ------------- 
29/01/2020 9:17:40  |  Page Creation  |  Using the supplied prefix
29/01/2020 9:17:41  |  Page Creation  |  The page already exists in target location
29/01/2020 9:17:41  |  Page Creation  |  Modern page created 
29/01/2020 9:17:41  |  Home page handling  |  Welcome page setting does exist, checking if the transform page is a home page
29/01/2020 9:17:41  |  Home page handling  |  The current page is not used as the site home page
29/01/2020 9:17:41  |  Article page handling  |  Transforming source page as Article page
29/01/2020 9:17:41  |  Article page handling  |  Page Header Set to None. Removing the page header
29/01/2020 9:17:41  |  Article page handling  |  Recognized source page as a Wiki Page. - Analyzing web parts and page layouts
29/01/2020 9:17:41  |  Article page handling  |  Splitting images and videos from wiki text - as modern text web part does not support embedded images and videos
29/01/2020 9:17:42  |  Set Page Title  |  Setting the modern page title: Table_12_bug_404
29/01/2020 9:17:42  |  Article page handling  |  Transforming content
29/01/2020 9:17:42  |  Content Transform  |  Transforming web parts
29/01/2020 9:17:44  |  Web Part Mapping  |  Web Part:'WikiText' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
29/01/2020 9:17:58  |  **Built-in Function**  |  **Table could not be normalized and will be taken over as is. Error = Index was outside the bounds of the array.**
29/01/2020 9:17:58  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
29/01/2020 9:17:58  |  Content Transform  |  Transforming web parts complete
29/01/2020 9:17:58  |  Article page handling  |  Transforming content complete
29/01/2020 9:17:58  |  Article page handling  |  Saved page: Migrated_table_12_bug_404.aspx
29/01/2020 9:17:58  |  Item level permissions  |  Item level permissions read
29/01/2020 9:17:59  |  Page Creation  |  Transformation Complete

**Comment by pkbullock** [comment]
Thanks @jansenbe i'll do some more testing, its possible just a class isn't covered by the logging.

**Comment by pkbullock** [comment]
Ah yeap, def a bug, most of the classes under pages folder e.g. BasePage.cs etc don't have observers passed to. Working on PR shortly.

**Comment by jansenbe** [comment]
Thanks for the fix @pkbullock
