### ISSUE TITLE
Left navigation links with tree view enabled- Missing when page converted to Modern

### ISSUE THREAD

**Issue by InfosysAdmin** [SharePoint/sp-dev-modernization#424]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug
[ *] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[*] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Tree view left navigation links to be available in modern pages after transformation

#### Observed Behavior

Left navigation tree view missing
#### Steps to Reproduce

Enable tree view navigation in site settings. Page will get new set of left navigation links with a tree format. Convert the page to modern.

**Comment by jansenbe** [comment]
Hi @InfosysAdmin,

Left treeview navigation (the "Enable Tree View" option in the "Navigation Elements" site setting) does not exist anymore on modern pages, this is not related to page transformation. You however should be able to configure up to three levels in the regular left navigation.

**Comment by jansenbe** [comment]
Closing this one as it's not about page transformation and the asked question has been answered
