### ISSUE TITLE
PnP PowerShell support for Term Store Mapping

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#436]
#### Category

[ ] Bug
[X] Enhancement

-------------------
Placeholder here to notify that I submit the PnP PowerShell element of the term mapping feature.

**Comment by pkbullock** [comment]
@jansenbe struggling slightly with this, unit tests in the core pass for a scenario, but output in PS records fields skipped. I feel there might be some binary caching happening but dunno, might be just lateness of the evening. Just wondering if you can get it to work in PS?

Scenario:

- Publishing Pages in SPO
- Taxonomy on both pages
- Term Mapping contains from one term to another
- Page Mapping contains metadata references source and target, no functions used
- Tenant level term set, both term sets are the same

Result: "Copying taxonomy field PnPCategory skipped because it's empty"

```
$spoConn = Connect-PnPOnline https://tenant.sharepoint.com/sites/PnPSauce/en -Credentials CaPaDevTest -ReturnConnection
$targetConn = Connect-PnPOnline https://tenant.sharepoint.com/sites/PnPKatchup -Credentials Online -ReturnConnection

ConvertTo-PnPClientSidePage -Identity "Article-PnP-Example" -TargetPageName "Article-PSScriptTest.aspx" -PublishingPage -TargetConnection $targetConn -Connection $spoConn `
    -Overwrite -LogType Console -LogVerbose -PageLayoutMapping C:\temp\spo-mapping-all-test.xml -TermMappingFile C:\temp\TestPS\term_mapping_sample.csv -ClearCache
```

I'll keep trying just may need second pair of eyes.

**Comment by jansenbe** [comment]
@pkbullock , I'll merge your PS PR and do some testing

**Comment by jansenbe** [comment]
Your PS pr has been merged

**Comment by pkbullock** [comment]
I've figured out how to debug the modernizer in PS and found the fault. Will issue PR soon.

**Comment by jansenbe** [comment]
Closing this one now that we're about to release. I'll message term mapping as a preview release and ask for feedback. This will give us some room in March to further refine where needed
