### ISSUE TITLE
Project summary web part and Site Users web part- Not available in Modern Page

### ISSUE THREAD

**Issue by InfosysAdmin** [SharePoint/sp-dev-modernization#438]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug
[* ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[*] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Not getting the equivalent replacement of Project summary and Site Users web part in Modern page after the classic page been converted using "ConvertTo-PnPClientSidePage -Identity PageName.aspx"

**Comment by jansenbe** [comment]
Hey @InfosysAdmin ,

The project summary web part is indeed not mapped on the modern page as there simply is no OOB modern web part that does the same. If this web part's functionality is important for your transformation you can opt to create a custom version yourselves and update the mapping file to use that one:

´´´Xml
 
      <WebPart Type="Microsoft.SharePoint.Portal.WebControls.ProjectSummaryWebPart, Microsoft.SharePoint.Portal, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
        <Properties>
          <Property Name="PrimaryTaskListUrl" Type="string" />
          <Property Name="ListId" Type="guid"/>
          <Property Name="ShowTimeline" Type="bool"/>
          <Property Name="Panels" Type="string"/>
        </Properties>
      </WebPart> 
´´´

In case of the site users web part the default approach for maintaining site users is via the `Gear Icon` > `Site Permissions`...so there's no need for custom modern web part for this.

Below is the default mapping for the site users web part: if you don't like the text being put on the page you can remove the full mappings element.

```Xml`

      <WebPart Type="Microsoft.SharePoint.WebPartPages.MembersWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" CrossSiteTransformationSupported="true">
        <Properties>
          <Property Name="IsIncluded" Type="bool"/>
          <Property Name="Dir" Type="string"/>
          <Property Name="PartImageSmall" Type="string"/>
          <Property Name="PartImageLarge" Type="string"/>
          <Property Name="IsIncludedFilter" Type="bool"/>
          <Property Name="DisplayType" Type="string"/>
          <Property Name="MembershipGroupId" Type="integer"/>
          <Property Name="Toolbar" Type="bool"/>
        </Properties>
        <Mappings>
          <Mapping Default="true" Name="default">
            
            <ClientSideText Order="10" Text="Managing site members now is done using the &lt;strong&gt;Settings -> Site Permissions pane&lt;/strong&gt;. No need anymore for this custom web part."/>
          </Mapping>
        </Mappings>
      </WebPart>
```

**Comment by jansenbe** [comment]
Hey @InfosysAdmin ,

Did my answer provide the clarity you needed? Can I close this issue?

**Comment by jansenbe** [comment]
Closing as there was no feedback, so I assume the answer provided was sufficient
