### ISSUE TITLE
Internal field broke transform "A2ODMountCount"

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#439]
This is an FYI, I am writing a temporary fix for this, but a new internal field called "A2OD Mount Count" broke transform specifically in the CopyPageMetadata method with the error:  "Error: Invalid data has been used to update the list item. The field you are trying to update may be read only."

I thought this was related to the taxonomy transform. 

This is new on my tenant not added by me, even on sites outside the scope of the my test rig and other demo environments located in the Site Pages library.

**Comment by sparkitect** [comment]
I've seen this new column in our tenant as well, with this page being the only result on Google with any reference to it (Bing was empty).

Any idea what it is?

**Comment by jansenbe** [comment]
This is a new (internal) lookup field that seems to be appearing in all lists. I've added this to our field exclusion list so we're not processing it.

**Comment by jansenbe** [comment]
@pkbullock : I've fixed things different than your pending PR...if the other changes in your PR are still needed can you then update the PR. If not then the PR can be closed.

**Comment by jansenbe** [comment]
Just noticed you've closed your PR @pkbullock , so I think we can safely close this issue now.

For reference: this fix will appear in the upcoming March release of page transformation, which will get released between March 6th and March 9th.

**Comment by SwapnaNethi** [comment]
Does this field has any impact on "Apply-PnPProvisioning Template"?
because, all of a sudden my powershell broke with error below when trying to apply for "Site Assets" , "Form Templates"  Libraries

Apply-PnPProvisioningTemplate : Cannot change Hidden attribute for this field.

**Comment by praveenneon** [comment]
> Does this field has any impact on "Apply-PnPProvisioning Template"?
> because, all of a sudden my powershell broke with error below when trying to apply for "Site Assets" , "Form Templates" Libraries
> 
> Apply-PnPProvisioningTemplate : Cannot change Hidden attribute for this field.

I'm seeing the same issue too.
Apply-PnPProvisioningTemplate  - Access denied on A2ODMountCount field.
Please help!

**Comment by pkbullock** [comment]
@praveenneon please can you report this to the PnP PowerShell issues list, https://github.com/pnp/PnP-PowerShell/issues - this project focuses around transformation of classic to modern sites.
