### ISSUE TITLE
Global Navigation-Unable to add/hide links using Navigation settings

### ISSUE THREAD

**Issue by InfosysAdmin** [SharePoint/sp-dev-modernization#442]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[*] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[*] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
After site upgradation, global navigation links should be able to edit using navigation settings
 
#### Observed Behavior

After Site upgradation to modern, global navigation links are changed.

**Comment by jansenbe** [comment]
Hey @InfosysAdmin , can you clarify more with what exactly has changed? When you do an in-place modernization and choose to give the modern pages the name of the previous classic page (the `-TakeSourcePageName` parameter of the `ConvertTo-PnPClientSidePage` cmdlet) then the tool updates the links in existing navigation entries...and that's the only thing we do with navigation. 

So this makes me think you're running into how things work OOB: 
- When you've used the `Site Settings` -> `Top link bar` option on classic team sites:  in a classic team site you then have both global (top) and current (left) navigation and you can edit them both from within the classic page. For modern pages in that same team site you can only edit the current (left) navigation, the top navigation is visible but cannot be edited from within the modern page. To edit that navigation one must go the via `Site Settings` -> `Top Link Bar` (the topnav.aspx page). 
- When you happen to have the classic publishing feature enabled at site collection level: in a classic team site you then have both global (top) and current (left) navigation and you can edit them both from within the classic page. For modern pages in that same team site you can only edit the current (left) navigation, the top navigation is visible but cannot be edited from within the modern page. To edit that navigation one must go the via `Site Settings` -> `Navigation` (the AreaNavigationSettings.aspx page). 

So I think what you see is how things are built in modern. If you feel there's a compelling reason to change this then I would recommend either creating a new entry in our SharePoint User Voice site or checking if there's already an entry for this and voting for that. You can find user voice here: https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration

**Comment by jansenbe** [comment]
Closing as this issue is not related to page transformation as such
