### ISSUE TITLE
Possible issues querying tenant admin center sites list

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#443]
Attempting to query using REST https://contoso-admin.sharepoint.com/_api/web/lists/GetByTitle('DO_NOT_DELETE_SPLIST_TENANTADMIN_AGGREGATED_SITECOLLECTIONS')/items?$select=*&$filter=TemplateName%20eq%20%27STS%230%27 

<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code>
-2147024860, Microsoft.SharePoint.SPQueryThrottledException
</m:code>
<m:message xml:lang="en-US">
The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator.
</m:message>
</m:error>

**Comment by jansenbe** [comment]
Actually, we already are using a page query. Above issue was not exactly related to the scanner code, so it can be closed

**Comment by vikassharmaatl** [comment]
Hi,
I'm currently getting this error, when I run the tool:
The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator.
How can I resolve it?

**Comment by jansenbe** [comment]
Sorry for the late reply, spotting changes on closed issues is hard. Anyway, the upcoming 2.11 release will provide a fix for this.

**Comment by vikassharmaatl** [comment]
thanks!
