### ISSUE TITLE
Custom Web Part Not showing on the page after transformation

### ISSUE THREAD

**Issue by MartinHatch** [SharePoint/sp-dev-modernization#451]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
The custom web part is displayed, in the location provided

#### Observed Behavior

There are TWO custom web parts in our mapping file. 

One of them (PFP.PageProperties) appears absolutely fine. 
The other web part (PFP.Breadcrumb) does not appear, and there are no errors. 

I can manually add both web parts to the page without errrors. 
Both web parts are added to the App Catalog and "globally" deployed. 

#### Steps to Reproduce
See mapping files in ZIP file as attached:
[MappingFiles.zip](https://github.com/SharePoint/sp-dev-modernization/files/4319233/MappingFiles.zip)

![image](https://user-images.githubusercontent.com/12050704/76437034-e1afa500-63b0-11ea-8e8b-574124fd0967.png)

**Comment by jansenbe** [comment]
@MartinHatch :

The provided files look fine. Can you do a run with verbose logging and share that as well?

**Comment by MartinHatch** [comment]
Bizarro .. came back the following day and it was working ?? 

I also updated my build of PnP PowerShell to the March edition - maybe that was related?

**Comment by jansenbe** [comment]
Not aware of anything specific in March release for this, but glad it works. Closing issue now.
