### ISSUE TITLE
Busy generating a modern version of Homepage.aspx... Error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by derLarsonaut** [SharePoint/sp-dev-modernization#46]
I receive this error message in the modernization center when i try to create a modern version:
Busy generating a modern version of Homepage.aspx...
Error: SyntaxError: Unexpected end of JSON input

**Comment by jansenbe** [comment]
Can you share the details of the error? Please press F12 and go to the console output and provide the text in red or a screenshot of the console window

**Comment by derLarsonaut** [comment]
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
(Fetch)GET - https://XXXXXXXXXXmod.azurewebsites.net/api/ModernizePage?SiteUrl=https%3A%2F%2FXXXXXXXXXX.sharepoint.com%2Fverwaltung%2Ftestumgebung%2F&PageUrl=https%3A%2F%2FXXXXXXXXXX.sharepoint.com%2Fverwaltung%2Ftestumgebung%2FSitePages%2FHomepage.aspx

**Comment by derLarsonaut** [comment]
an when i use edge i receive this error message: Busy generating a modern version of Homepage.aspx...
Error: SyntaxError: Fehler beim Lesen

**Comment by jansenbe** [comment]
This looks like the bug I've fixed yesterday. When you've enabled page transformation for a site did you use the same casing for the URL as the URL actually is shown in SharePoint. There's a string replacement that used to fail when not being case sensitive. 

Two ways to fix (both should work)
- Drop the latest solution from dev tree (https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/assets/sharepointpnp-pagetransformation-central.sppkg) in the app catalog and then go to the modernization center -> site contents -> click on the three dots next to the sharepointpnp-pagetransformation-central app and click on "Get it" to install the latest version in the modernization center site
- Use the web part in the modernization center and disable page transformation for your site and then re-enable it using the url written in the correct casing

**Comment by jansenbe** [comment]
Also can you please share the output of `Get-PnPStorageEntity` and check for any red error message in the browser debug console (press F12 on the page that hangs).

**Comment by derLarsonaut** [comment]
The update to the new version did not help.
Here ist the output og get-pnp…
Key                                      Value                                            Comment Description          
---                                      -----                                            ------- -----------          
Modernization_AzureADApp                 3f878259-13b1-44ca-91f8-e5a4074e529c                     ID of the Azure AD...
Modernization_FunctionHost               https://XXXXXXXXXXX.azurewebsites.net                    Host of the ShareP...
Modernization_PageTransformationEndpoint api/ModernizePage                                        Api endpoint for p...
Modernization_CenterUrl                  /sites/modernizationcenter                               Site relative URL ...
Modernization_FeedbackList               ModernizationFeedback                                    Name of the create...
Modernization_LearnMoreUrl               https://aka.ms/sppnp-pagetransformationui-manual         Url shown in the l...

**Comment by derLarsonaut** [comment]
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
(Fetch)GET - https://XXXXXXXXXX.azurewebsites.net/api/ModernizePage?SiteUrl=https%3A%2F%2FXXXXXXXXXX.sharepoint.com%2Fverwaltung%2Ftestumgebung&PageUrl=https%3A%2F%2XXXXXXXXXX.sharepoint.com%2Fverwaltung%2Ftestumgebung%2FSitePages%2FHomepage.aspx

modernizePageServiceCall() failed: SyntaxError: Fehler beim Lesen

in Render(). Errorstring = SyntaxError: Fehler beim Lesen

**Comment by jansenbe** [comment]
Hey @derLarsonaut ,

Can you check some more things:
- Did you get errors while provisioning the function? If you used upper case characters in the older versions of the script then this could result in errors when configuring the function app. If you go check the web settings of the function app and don't see properties like CLIENT_ID and CLIENT_SECRET then this needs to be corrected
- Go to https://http://aad.portal.azure.com, click on "Azure Active Directory", click on "App registrations", type in SharePoint and set the drop down to "All Apps". Click on "SharePointPnP.Modernization", click on "SharePointPnP.Modernization" underneath "Managed application in local directory", click on "Permissions". You should see 2 admin consented permissions, if that's not the case then the admin consent step was not yet done. You can do that then by clicking on the "Grant admin consent for..." button
- Third thing to check is if the permission was correctly granted, if the previous step is not done then this might have failed as well. Please run `Get-PnPTenantServicePrincipalPermissionGrants` and verify there's a permission returned with Resource = "SharePointPnP.Modernization" and Scope = "user_impersonation". If you don't see this permission grant then please run ` Grant-PnPTenantServicePrincipalPermission -Scope "user_impersonation" -Resource "SharePointPnP.Modernization"`

I'm currently writing a troubleshooting guide and have already improved the Azure setup process, but the permission grant in Azure stays a manual thing. Thanks for testing and let me know if this gets you unblocked. If not then let's set a quick call to verify things.

**Comment by jansenbe** [comment]
Hi @derLarsonaut,

I've created a troubleshooting guide over here: https://github.com/SharePoint/sp-dev-modernization/blob/master/Solutions/PageTransformationUI/docs/troubleshootingguide.md

Not sure if you still see the error, but that guide will help you troubleshoot the issue.

**Comment by derLarsonaut** [comment]
Hi @jansenbe Thanks a lot for your time.
I found the problem. The deploy of the service binaries to the azure function app was not successfull. I tried it again via Kudu and know it works!
Lars

**Comment by jansenbe** [comment]
Good news @derLarsonaut. 

Any idea why it failed in the first place? Did you use the setup script or did it manually? Any errors from that process that you recall?

**Comment by derLarsonaut** [comment]
@jansenbe I followed this page: https://github.com/SharePoint/sp-dev-modernization/blob/master/Solutions/PageTransformationUI/docs/manual%20setup/modernization-ui-manual-azure.md
I probably didn't read the message correctly after uploading via kudo.
