### ISSUE TITLE
Create Modern Version not visible 

### ISSUE THREAD

**Issue by Nahar09** [SharePoint/sp-dev-modernization#47]
I have installed and enabled the Page transformation UI on a site from the modernization center. I got the message "Modernization functionality added to site" message.  Yet , when I browse to the site the 'Create Modern Version' command is not visible in the Wiki Page ribbon. It is visible on a webpart page ribbon. 
Kindly Advise , how to debug the issue.

**Comment by jansenbe** [comment]
Hi @Nahar09,

Can you check the following:
- If you're user is having at least Contribute permissions on the site. If you're in the site members, owners or admins then this should be the case
- Ribbon XML is cached: clearing cache and logging in again does typically refresh that cache

**Comment by jansenbe** [comment]
Hi @Nahar09,

Did the above help?

**Comment by jansenbe** [comment]
Closing as there's no further response. @Nahar09 : feel free to re-open if you still have issues

**Comment by Nahar09** [comment]
Clearing cache helped
