### ISSUE TITLE
App.Config and Unit Test Files

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#54]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Error during the use of page transformation from PnP PowerShell
[X] Error during the use of page transformation from .Net
[ ] Page is not looking correct after transformation

#### Expected or Desired Behavior

Trying to compile and run tests for the code

#### Observed Behavior

Some of the App.Config files are missing, like the unit test project, are you able to provide app.config.sample files?

The unit tests rely on files in the C:\temp folder, can you include them in the project?

#### Questions?

Are you taking submissions? I am looking to contribute somewhere in the PnP program. I could look at helping test this and perhaps provide some submissions as well - Id would like to try to fix the issue if I can.

**Comment by jansenbe** [comment]
Hi @pkbullock,

For the Unit Test project you should copy the [app.config.sample](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework.Tests/App.config.sample) to app.config and update it.

**Comment by jansenbe** [comment]
Hi @pkbullock,

Did the above answer get you unblocked?

**Comment by pkbullock** [comment]
Sort of, I had some issues running the unit tests with references to different versions of SharePointPnP.IdentityModel.Extensions, which I've fixed. 

There are a few references to files outside of the project and your own tenant.

**Comment by jansenbe** [comment]
My tenant has a whole series of pages which I test against...hence it's normal that not all tests just work. I'll check the identitymodel reference and will close this issue. Thx for reporting this.

**Comment by pkbullock** [comment]
The issue was fixed by updating the SharePointPnP.Modernisation.Framework to reference package 1.2.4, currently its 1.2.3 or use Consolidate in NuGet Package manager.
