### ISSUE TITLE
Idea - Summary Web Part to One or Multiple Quick Links Web Part

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#55]
#### Category

[ ] Bug
[X] Enhancement

#### Problem Area

[ ] Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Error during the use of page transformation from PnP PowerShell
[ ] Error during the use of page transformation from .Net
[X] Page is not looking correct after transformation

None of the above really.

#### Expected or Desired Behavior

It would look nicer if these were Quick Links web parts or the option to. Maybe with the option in the mapping for selecting a style in the modern web part.

For the scenario with grouped links, maybe split into multiple quick links web parts.

#### Observed Behavior

This currently outputs into a Text Web Part.

#### Steps to Reproduce

Transform a page with summary links present.

**Comment by jansenbe** [comment]
Thx for this idea @pkbullock, transforming to one quicklinks web part should be possible. Going to multiple quicklinks web parts is not something that's today foreseen in the transformation architecture. I'll plan some research time on this and possibly plan implementation for a future release.

**Comment by jansenbe** [comment]
Hi @pkbullock ,
Will implement a solution where the headers are dropped and we get one quicklinks web part holding all the links. This configuration can be optionally set via a the new mapping properties in the PageTransformationInformation (see dev branch).

**Comment by jansenbe** [comment]
Hi @pkbullock ,

Implemented transformation to QuickLinks dev branch...working really nice but could use some additional testing coverage :-)
