### ISSUE TITLE
Cross-Site Asset Transfer

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#60]
### Category

[ ] Bug
[X] Enhancement

Reference: #59 - Implementation of "Verify individual web parts: web parts do tend to have references to the source site and therefore some of them will not work"

#### Problem Area

[ ] Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Error during the use of page transformation from PnP PowerShell
[ ] Error during the use of page transformation from .Net
[X] Page is not looking correct after transformation

#### Expected or Desired Behaviour

When we are transforming pages across site collections, the referenced files are included in the transfer, to the new sites.

#### Plan for implementation

Plan:

- Detect for referenced assets within the web parts
- Referenced assets should only be files e.g. not aspx pages and located in the pages, site pages libraries
- Ensure the referenced assets exist in the source location within the same site collection/web according to the level of transformation
- Multiple support the scenario where multiple web parts refer to a single asset
- With the modern destination, locate assets in the site assets library with in a folder using the same naming convention as SharePoint Comm Sites
- If SiteAssets library does not exist - create the library (in the case of vanilla Communication Sites)
- Add copy assets method to transfer the files to target site collection
- Store a dictionary of copied assets to update the URLs of the transferred web parts
- Phased approach for this:  Image Web Parts, Text Web Parts with inline images (need to determine how they are handled), TBC - expanded as testing progresses
- Not covering page to page links within the same site collection e.g. summary links to pages

@jansenbe - I wanted to list out my plans for implementing this, as its quite a large change. I will include unit tests. What are your thoughts on this? Do you think there is anything that you think might need adding to the capability?

**Comment by jansenbe** [comment]
Hi @pkbullock,

I really like that you reach out upfront to discuss these more fundamental changes! I'm more than happy to work together with you on this change.

Some inline comments to your proposed plan:
- Detect for referenced assets within the web parts
  - We need somehow be able to define this in a flexible manner. I was thinking of:
    - Adding a new optional attribute `CrossSiteTransformationSupported=true/false` to the `WebPart` element of the webpartmapping.xml file
    - Indicating in the webpartmapping.xml file which properties contain assets that might have to be transfered. Was thinking of something like a new collection under the `WebPart` element: `<TransferableAssets><Asset Property="ImageLink" Type="ServerRelativeUrl" Transform="CopyToSitePages"/></TransferableAssets>`. Using this model the core transformation engine can understand what assets are candidates for transformation, how they're defined and which transformation function should be used. The function approach allows to create different transformation functions and reuse these where needed (bit like the Functions we have in the current model). Also the transformation function run can then alter the earlier collected/calculated web part properties so when the actual transformation happens there's no need to update any of the existing builtin functions
- Referenced assets should only be files e.g. not aspx pages and located in the pages, site pages libraries
  - Will be covered by previous comment, meaning only assets defined in the model will be taken. I agree that we initially should focus on images
- Ensure the referenced assets exist in the source location within the same site collection/web according to the level of transformation
  - Will be implemented a transformation function. Transformation function can have parameters to make a single function behave differently when needed
- Multiple support the scenario where multiple web parts refer to a single asset
  - Yes, should be part of the above model. The transformation function should be avoiding unneeded duplicates
- With the modern destination, locate assets in the site assets library with in a folder using the same naming convention as SharePoint Comm Sites
  - Yes, let's come up with a model to store transfered assets in a central spot
- If SiteAssets library does not exist - create the library (in the case of vanilla Communication Sites)
  - Yes, that will be needed
- Add copy assets method to transfer the files to target site collection
  - See earlier comments
- Store a dictionary of copied assets to update the URLs of the transferred web parts
  - See earlier comments
- Phased approach for this:  Image Web Parts, Text Web Parts with inline images (need to determine how they are handled), TBC - expanded as testing progresses
- Not covering page to page links within the same site collection e.g. summary links to pages

So in general I do like your idea and I think it will be very valuable addition to the page transformation tech. If we push the core implementation into the model and engine then we do have generic extendable solution which potentially can serve additional purposes (like pre/post transformation actions). If you feel more comfortable having a meeting to discuss this then let me know, personally I think it would be good to brainstorm a bit more on this together.

**Comment by pkbullock** [comment]
Morning @jansenbe 

Great feedback, further brain storming would give us the opportunity to iron this out. What the best way of contacting you? I have a twitter handle @pkbullock we could exchange contact details privately.

**Comment by jansenbe** [comment]
Closing this issue as we do have a first level of support included which will go out in the March release.
