### ISSUE TITLE
Collapse/Merge Unused Sections in Target

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#64]
#### Category

[ ] Bug
[x] Enhancement

#### Problem Area

[ ] Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Error during the use of page transformation from PnP PowerShell
[ ] Error during the use of page transformation from .Net
[x] Page is not looking correct after transformation

#### Expected or Desired Behavior

In the transformed site, when you are transforming Web Part Page to Modern, unused sections are enforced by the fabric the layout then has blocks of white space. Consider removing the sections that do not contain web parts.

#### Observed Behavior

In Classic, because of the way the layout works, any unused sections allow the areas that have content to expand and fill the white space. This is observed in web part layouts with 2-3 columns.

This does not appear to happen with Wiki Pages.

**Comment by jansenbe** [comment]
Good idea @pkbullock, no point in retaining sections that are completely empty.

**Comment by jansenbe** [comment]
@pkbullock : implemented in dev branch
