### ISSUE TITLE
The file OfficeDevPnP.Core.resources is not found when executing ConvertTo-PnPClientSidePage

### ISSUE THREAD

**Issue by boby5555** [SharePoint/sp-dev-modernization#89]
Category
[x] Bug
[ ] Enhancement

Problem Area
[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our troubleshooting guide?)
[ x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

Observed Behavior
If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.

Steps to Reproduce
I tried with both **_february_** release and **_march_** release

```
Connect to the web holding the pages to modernize
Connect-PnPOnline -Url https://*****.sharepoint.com/

Get all the pages in the site pages library. SitePages is the only supported library for using modern pages
$pages = Get-PnPListItem -List sitepages

Iterate over the pages
foreach($page in $pages)
{


if (-not $page.FieldValues["FileLeafRef"].StartsWith(("Previous_")))
{

if ($page.FieldValues["ClientSideApplicationId"] -eq "b6917cb1-93a0-4b97-a84d-7cf49975d4ec" )
{
Write-Host Page $page.FieldValues["FileLeafRef"] is modern, no need to modernize it again
}
else
{

Write-Host Modernizing $page.FieldValues["FileLeafRef"]...
$modernPage = ConvertTo-PnPClientSidePage -Identity $page.FieldValues["FileLeafRef"] -Overwrite -TakeSourcePageName
Write-Host "Done" -ForegroundColor Green
}
}
}
```

**Comment by boby5555** [comment]
I solved it myself....You can't modernize the root classic site in SharePoint Online. Works great on any other sites.

**Comment by jansenbe** [comment]
@boby5555 : we'll soon enable you to modernize the root site, assuming it's not using publishing features. Glad you got it resolved ... but still kind of weird you got an exception

**Comment by boby5555** [comment]
If you have some time, you can try it yourself :) Just use the same code and replace the URL with the URL of the root site of your tenant.
