### ISSUE TITLE
Username is lowercase

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#97]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[X] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Casing is maintained during transform

#### Observed Behavior

![2019-04-03_22-19-04](https://user-images.githubusercontent.com/8781041/55513860-a6fca300-565e-11e9-904d-81a6d4ee9237.jpg)

#### Steps to Reproduce

Transform a page with the custom header and the mapping includes ToAuthors({PublishingContact})

Discovered fault in Line 92 PublishingFunctionProcessor.cs

Logged as need more test cases to validate impact to remove the ToLower()

**Comment by jansenbe** [comment]
Nice catch @pkbullock , there was no reason for applying a ToLower() in that place. Fixed in https://github.com/SharePoint/sp-dev-modernization/commit/8ee3dce996bfedca7bc5b96b6e149db9af42503a.
