### ISSUE TITLE
Fault with moderising publishing page with fixed web parts

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#98]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[X] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Transformation works

#### Observed Behavior

Unit test error:

Message: Test method SharePointPnP.Modernization.Framework.Tests.Transform.Publishing.PublishingPageTests.BasicPublishingPageTest threw exception: 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

For a fixed web part containing a content editor web part, the casing for the properties that the analyser produces defaults to upper case. 

Fault occurs in line 105 of the WikiTransformatorSimple class where the properties for the web parts is assumed to be "Content" rather than "CONTENT". 

In another point, AngleSharp reads the text of the page layout with either Upper or Lower Case, Analyser uses NodeName which is uppercase.

#### Steps to Reproduce

Use the provisioning test file (ArticleCustom.aspx) and add block to your test page layout, as a fixed web part:

```xml
<WebPartPages:ContentEditorWebPart webpart="true" runat="server" __WebPartId="{DB666743-4C5B-4A21-A9CF-7A199CE19A60}">
				<WebPart xmlns="http://schemas.microsoft.com/WebPart/v2">
					<Title>Example Embedded Web Content Editor</Title>
                    <FrameType>None</FrameType>
					<PartImageLarge>/_layouts/15/images/mscontl.gif</PartImageLarge>
					<ID>g_db666743_4c5b_4a21_a9cf_7a199ce19a60</ID>
					<Content xmlns="http://schemas.microsoft.com/WebPart/v2/ContentEditor"><![CDATA[Welcome to the home of all SharePoint modernization tools and solutions. Modernization means transforming current "classic" SharePoint usage into "modern" usage, e.g. using modern site pages instead of classic wiki pages or Office 365 Group connecting of classic sites. In this repository you'll find all the SharePoint PnP open source scripts, tools and solutions that will help you modernize your SharePoint environment.]]></Content>
				</WebPart>
			</WebPartPages:ContentEditorWebPart>
```

Then run transform tests.

**Comment by jansenbe** [comment]
Thanks for reporting this one @pkbullock . I've made the properties dictionary case insensitive + did some extra checking on property existance. See https://github.com/SharePoint/sp-dev-modernization/commit/43253446fcf65b34cfdf8258d94826c7d822224d
