### ISSUE TITLE
Insert New Web Parts in the transform process

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#99]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

Ability to add target web parts that didn't exist before in the source to be included in the creation of modern pages e.g. Spacer Web Parts, Text Web Parts for Titles, etc.

This help if pages have a defined look book or require other modern web parts with pre-defined configuration in addition to the transformed content.

**Comment by jansenbe** [comment]
Harder one to find and easy to use solution for...one option could be having a 'hook' after we've done all the work to translate the source page in a collection of web parts + provide some helper methods that ensure inserted web parts are defined correctly (types, properties, ordering). 

Alternative would be use PnP PS to update the created page...would that be an option for you as well?

**Comment by pkbullock** [comment]
@jansenbe I think given that PnP PS has this capability anyway we would just be duplicating. Happy to drop.

**Comment by jansenbe** [comment]
Sounds good, let's close for now.
